const highlights = [
        {id: 1, parkId: 1, parkName: "35TH STREET", features: "playground",},
        {id: 2, parkId: 2, parkName: "CRESCENT HILL", features: "swimming",},
        {id: 3, parkId: 1, parkName: "35th STREET", features: "basketball",},
        {id: 4, parkId: 2, parkName: "Crescent Hill", features: "picnic",},
        {id: 5, parkId: 2, parkName: "Crescent Hill", features: "playground",},
        {id: 6, parkId: 2, parkName: "Crescent Hill", features: "golf",},
        {id: 7, parkId: 2, parkName: "Crescent Hill", features: "tennis",},
        {id: 8, parkId: 2, parkName: "Crescent Hill", features: "sprayground",},
        {id: 9, parkId: 3, parkName: "Algonquin", features: "sprayground",},
        {id: 10, parkId: 101, parkName: "BAXTER SQUARE", features: "sprayground",},
        {id: 11, parkId: 126, parkName: "BEECHMONT TOT LOT", features: "sprayground",},
        {id: 12, parkId: 109, parkName: "BRESLIN", features: "sprayground",},
        {id: 13, parkId: 39, parkName: "CALIFORNIA LEISURE open space", features: "sprayground",},
        {id: 14, parkId: 86, parkName: "FARNSLEY", features: "sprayground",},
        {id: 15, parkId: 54, parkName: "G.G. MOORE", features: "sprayground",},
        {id: 16, parkId: 97, parkName: "IROQUOIS", features: "sprayground",},
        {id: 17, parkId: 41, parkName: "LAPORTE", features: "sprayground",},
        {id: 18, parkId: 102, parkName: "LONG RUN", features: "sprayground",},
        {id: 19, parkId: 25, parkName: "NELSON HORNBECK", features: "sprayground",},
        {id: 20, parkId: 117, parkName: "PETERSBURG", features: "sprayground",},
        {id: 21, parkId: 61, parkName: "RIVERVIEW", features: "sprayground",},
        {id: 22, parkId: 65, parkName: "SHELBY", features: "sprayground",},
        {id: 23, parkId: 120, parkName: "WYANDOTTE", features: "sprayground",},
        {id: 24, parkId: 6, parkName: "BINGHAM", features: "spraypads",},
        {id: 25, parkId: 45, parkName: "BOONE SQUARE", features: "spraypads",},
        {id: 26, parkId: 12, parkName: "CENTRAL", features: "spraypads",},
        {id: 27, parkId: 74, parkName: "CHEROKEE", features: "spraypads",},
        {id: 28, parkId: 13, parkName: "CHICKASAW", features: "spraypads",},
        {id: 29, parkId: 42, parkName: "ELLIOT SQUARE", features: "spraypads",},
        {id: 30, parkId: 54, parkName: "G.G. MOORE", features: "spraypads",},
        {id: 31, parkId: 58, parkName: "HUSTON QUIN", features: "spraypads",},
        {id: 32, parkId: 55, parkName: "PARKHILL", features: "spraypads",},
        {id: 33, parkId: 80, parkName: "PORTLAND", features: "spraypads",},
        {id: 34, parkId: 160, parkName: "ROBSION PARK", features: "spraypads",},
        {id: 35, parkId: 48, parkName: "RUSSELL LEE", features: "spraypads",},
        {id: 36, parkId: 69, parkName: "TYLER", features: "spraypads",},
        {id: 37, parkId: 88, parkName: "VICTORY", features: "spraypads",},
        {id: 38, parkId: 23, parkName: "WILLIAM HARRISON", features: "spraypads",},
        {id: 39, parkId: 3, parkName: "ALGONQUIN", features: "swimming",},
        {id: 40, parkId: 9, parkName: "CAMP TAYLOR", features: "swimming",},
        {id: 41, parkId: 2, parkName: "CRESCENT HILL", features: "swimming",},
        {id: 42, parkId: 25, parkName: "NELSON HORNBECK", features: "swimming",},
        {id: 43, parkId: 93, parkName: "Sun Valley", features: "swimming",},
        {id: 44, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "sprayground",},
        {id: 45, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "playground",},
        {id: 46, parkId: 148, parkName: "BROAD RUN", features: "sprayground",},
        {id: 47, parkId: 148, parkName: "BROAD RUN", features: "playground",},
        {id: 48, parkId: 124, parkName: "A.B. SAWYER", features: "baseball",},
        {id: 49, parkId: 8, parkName: "BUECHEL", features: "baseball",},
        {id: 50, parkId: 39, parkName: "CALIFORNIA", features: "baseball",},
        {id: 51, parkId: 9, parkName: "CAMP TAYLOR", features: "baseball",},
        {id: 52, parkId: 10, parkName: "CANE RUN", features: "baseball",},
        {id: 53, parkId: 157, parkName: "Community Park", features: "baseball",},
        {id: 54, parkId: 42, parkName: "ELLIOT SQUARE", features: "baseball",},
        {id: 55, parkId: 29, parkName: "HAYS KENNEDY", features: "baseball",},
        {id: 56, parkId: 26, parkName: "HOUNZ LANE", features: "baseball",},
        {id: 57, parkId: 31, parkName: "KLONDIKE", features: "baseball",},
        {id: 58, parkId: 25, parkName: "NELSON HORNBECK", features: "baseball",},
        {id: 59, parkId: 46, parkName: "OLD WALNUT / BEECHER", features: "baseball",},
        {id: 60, parkId: 117, parkName: "PETERSBURG", features: "baseball",},
        {id: 61, parkId: 3, parkName: "ALGONQUIN", features: "basketball",},
        {id: 62, parkId: 104, parkName: "BALLARD", features: "basketball",},
        {id: 63, parkId: 101, parkName: "BAXTER SQUARE", features: "basketball",},
        {id: 64, parkId: 126, parkName: "BEECHMONT TOT LOT", features: "basketball",},
        {id: 65, parkId: 105, parkName: "BERRYTOWN", features: "basketball",},
        {id: 66, parkId: 6, parkName: "BINGHAM", features: "basketball",},
        {id: 67, parkId: 106, parkName: "BLACK MUDD", features: "basketball",},
        {id: 68, parkId: 8, parkName: "BUECHEL", features: "basketball",},
        {id: 69, parkId: 9, parkName: "CAMP TAYLOR", features: "basketball",},
        {id: 70, parkId: 96, parkName: "CHARLIE VETTINER", features: "basketball",},
        {id: 71, parkId: 74, parkName: "CHEROKEE", features: "basketball",},
        {id: 72, parkId: 13, parkName: "CHICKASAW", features: "basketball",},
        {id: 73, parkId: 157, parkName: "Community Park", features: "basketball",},
        {id: 74, parkId: 90, parkName: "DES PRES", features: "basketball",},
        {id: 75, parkId: 17, parkName: "DOUGLASS", features: "basketball",},
        {id: 76, parkId: 76, parkName: "E. LELAND TAYLOR", features: "basketball",},
        {id: 77, parkId: 112, parkName: "FARMAN", features: "basketball",},
        {id: 78, parkId: 86, parkName: "FARNSLEY", features: "basketball",},
        {id: 79, parkId: 54, parkName: "G.G. MOORE", features: "basketball",},
        {id: 80, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "basketball",},
        {id: 81, parkId: 59, parkName: "GINNY REICHARD", features: "basketball",},
        {id: 82, parkId: 29, parkName: "HAYS KENNEDY", features: "basketball",},
        {id: 83, parkId: 82, parkName: "HIGHVIEW", features: "basketball",},
        {id: 84, parkId: 58, parkName: "HUSTON QUIN", features: "basketball",},
        {id: 85, parkId: 27, parkName: "IRISH HILL", features: "basketball",},
        {id: 86, parkId: 97, parkName: "IROQUOIS", features: "basketball",},
        {id: 87, parkId: 33, parkName: "LAKE DREAMLAND", features: "basketball",},
        {id: 88, parkId: 116, parkName: "LANNAN", features: "basketball",},
        {id: 89, parkId: 41, parkName: "LAPORTE", features: "basketball",},
        {id: 90, parkId: 102, parkName: "LONG RUN", features: "basketball",},
        {id: 91, parkId: 44, parkName: "MCNEELY LAKE", features: "basketball",},
        {id: 92, parkId: 52, parkName: "MEDORA", features: "basketball",},
        {id: 93, parkId: 25, parkName: "NELSON HORNBECK", features: "basketball",},
        {id: 94, parkId: 38, parkName: "NORFOLK ACRES", features: "basketball",},
        {id: 95, parkId: 84, parkName: "OKOLONA", features: "basketball",},
        {id: 96, parkId: 55, parkName: "PARKHILL", features: "basketball",},
        {id: 97, parkId: 80, parkName: "PORTLAND", features: "basketball",},
        {id: 98, parkId: 60, parkName: "RIVERSIDE GARDENS", features: "basketball",},
        {id: 99, parkId: 61, parkName: "RIVERVIEW", features: "basketball",},
        {id: 100, parkId: 63, parkName: "RUBEL", features: "basketball",},
        {id: 101, parkId: 48, parkName: "RUSSELL LEE", features: "basketball",},
        {id: 102, parkId: 98, parkName: "SENECA", features: "basketball",},
        {id: 103, parkId: 64, parkName: "SHAWNEE", features: "basketball",},
        {id: 104, parkId: 65, parkName: "SHELBY", features: "basketball",},
        {id: 105, parkId: 83, parkName: "SHEPPARD", features: "basketball",},
        {id: 106, parkId: 118, parkName: "SOUTH CENTRAL", features: "basketball",},
        {id: 107, parkId: 89, parkName: "ST LOUIS", features: "basketball",},
        {id: 108, parkId: 66, parkName: "STORY AVENUE", features: "basketball",},
        {id: 109, parkId: 93, parkName: "SUN VALLEY", features: "basketball",},
        {id: 110, parkId: 67, parkName: "SYLVANIA", features: "basketball",},
        {id: 111, parkId: 69, parkName: "TYLER", features: "basketball",},
        {id: 112, parkId: 88, parkName: "VICTORY", features: "basketball",},
        {id: 113, parkId: 81, parkName: "WESTONIA", features: "basketball",},
        {id: 114, parkId: 23, parkName: "WILLIAM HARRISON", features: "basketball",},
        {id: 115, parkId: 120, parkName: "WYANDOTTE", features: "basketball",},
        {id: 116, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "camping",},
        {id: 117, parkId: 157, parkName: "Community Park", features: "conference",},
        {id: 118, parkId: 16, parkName: "CARRIE GAULBERT COX", features: "fishing",},
        {id: 119, parkId: 96, parkName: "CHARLIE VETTINER", features: "fishing",},
        {id: 120, parkId: 74, parkName: "CHEROKEE", features: "fishing",},
        {id: 121, parkId: 13, parkName: "CHICKASAW", features: "fishing",},
        {id: 122, parkId: 114, parkName: "FISHERMAN'S", features: "fishing",},
        {id: 123, parkId: 97, parkName: "IROQUOIS", features: "fishing",},
        {id: 124, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "fishing",},
        {id: 125, parkId: 102, parkName: "LONG RUN", features: "fishing",},
        {id: 126, parkId: 44, parkName: "MCNEELY LAKE", features: "fishing",},
        {id: 127, parkId: 100, parkName: "THURMAN HUTCHINS", features: "fishing",},
        {id: 128, parkId: 95, parkName: "WAVERLY", features: "fishing",},
        {id: 129, parkId: 70, parkName: "WATTERSON LAKE", features: "fishing",},
        {id: 130, parkId: 94, parkName: "CHARLIE VETTINER golf course", features: "golf",},
        {id: 131, parkId: 2, parkName: "CRESCENT HILL golf course", features: "golf",},
        {id: 132, parkId: 154, parkName: "QUAIL CHASE golf course ", features: "golf",},
        {id: 133, parkId: 34, parkName: "SENECA golf course", features: "golf",},
        {id: 134, parkId: 77, parkName: "SHAWNEE golf course", features: "golf",},
        {id: 135, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "hiking",},
        {id: 136, parkId: 146, parkName: "POPE LICK PARK", features: "hiking",},
        {id: 137, parkId: 147, parkName: "TURKEY RUN", features: "hiking",},
        {id: 138, parkId: 148, parkName: "BROAD RUN", features: "hiking",},
        {id: 139, parkId: 11, parkName: "CAPERTON SWAMP", features: "hiking",},
        {id: 140, parkId: 74, parkName: "CHEROKEE", features: "hiking",},
        {id: 141, parkId: 111, parkName: "FAIRMONT FALLS", features: "hiking",},
        {id: 142, parkId: 113, parkName: "FERN CREEK", features: "hiking",},
        {id: 143, parkId: 97, parkName: "IROQUOIS", features: "hiking",},
        {id: 144, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "hiking",},
        {id: 145, parkId: 115, parkName: "JOE CREASON", features: "hiking",},
        {id: 146, parkId: 44, parkName: "MCNEELY LAKE", features: "hiking",},
        {id: 147, parkId: 95, parkName: "WAVERLY", features: "hiking",},
        {id: 148, parkId: 97, parkName: "IROQUOIS", features: "horseback",},
        {id: 149, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "horseback",},
        {id: 150, parkId: 102, parkName: "LONG RUN", features: "horseback",},
        {id: 151, parkId: 44, parkName: "MCNEELY LAKE", features: "horseback",},
        {id: 152, parkId: 98, parkName: "SENECA", features: "horseback",},
        {id: 153, parkId: 146, parkName: "POPE LICK PARK", features: "multiifield",},
        {id: 154, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "multiifield",},
        {id: 155, parkId: 148, parkName: "BROAD RUN", features: "multiifield",},
        {id: 156, parkId: 124, parkName: "A.B. SAWYER", features: "multiifield",},
        {id: 157, parkId: 3, parkName: "ALGONQUIN", features: "multiifield",},
        {id: 158, parkId: 109, parkName: "BRESLIN", features: "multiifield",},
        {id: 159, parkId: 39, parkName: "CALIFORNIA", features: "multiifield",},
        {id: 160, parkId: 10, parkName: "CANE RUN", features: "multiifield",},
        {id: 161, parkId: 74, parkName: "CHEROKEE", features: "multiifield",},
        {id: 162, parkId: 76, parkName: "E. LELAND TAYLOR", features: "multiifield",},
        {id: 163, parkId: 86, parkName: "FARNSLEY", features: "multiifield",},
        {id: 164, parkId: 113, parkName: "FERN CREEK", features: "multiifield",},
        {id: 165, parkId: 20, parkName: "FLAGET FIELD", features: "multiifield",},
        {id: 166, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "multiifield",},
        {id: 167, parkId: 29, parkName: "HAYS KENNEDY", features: "multiifield",},
        {id: 168, parkId: 26, parkName: "HOUNZ LANE", features: "multiifield",},
        {id: 169, parkId: 115, parkName: "JOE CREASON", features: "multiifield",},
        {id: 170, parkId: 116, parkName: "LANNAN", features: "multiifield",},
        {id: 171, parkId: 102, parkName: "LONG RUN", features: "multiifield",},
        {id: 172, parkId: 151, parkName: "LOUISVILLE CHAMPIONS", features: "multiifield",},
        {id: 173, parkId: 44, parkName: "MCNEELY LAKE", features: "multiifield",},
        {id: 174, parkId: 38, parkName: "NORFOLK ACRES", features: "multiifield",},
        {id: 175, parkId: 84, parkName: "OKOLONA", features: "multiifield",},
        {id: 176, parkId: 46, parkName: "OLD WALNUT / BEECHER", features: "multiifield",},
        {id: 177, parkId: 117, parkName: "PETERSBURG", features: "multiifield",},
        {id: 178, parkId: 48, parkName: "RUSSELL LEE", features: "multiifield",},
        {id: 179, parkId: 98, parkName: "SENECA", features: "multiifield",},
        {id: 180, parkId: 64, parkName: "SHAWNEE", features: "multiifield",},
        {id: 181, parkId: 83, parkName: "SHEPPARD", features: "multiifield",},
        {id: 182, parkId: 118, parkName: "SOUTH CENTRAL", features: "multiifield",},
        {id: 183, parkId: 66, parkName: "STORY AVENUE", features: "multiifield",},
        {id: 184, parkId: 93, parkName: "SUN VALLEY", features: "multiifield",},
        {id: 185, parkId: 100, parkName: "THURMAN HUTCHINS", features: "multiifield",},
        {id: 186, parkId: 119, parkName: "TOONERVILLE TROLLEY", features: "multiifield",},
        {id: 187, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "picnic",},
        {id: 188, parkId: 146, parkName: "POPE LICK PARK", features: "picnic",},
        {id: 189, parkId: 147, parkName: "TURKEY RUN", features: "picnic",},
        {id: 190, parkId: 148, parkName: "BROAD RUN", features: "picnic",},
        {id: 191, parkId: 160, parkName: "ROBSION PARK", features: "picnic",},
        {id: 192, parkId: 159, parkName: "Hal Warheim", features: "picnic",},
        {id: 193, parkId: 158, parkName: "Warwick Park", features: "picnic",},
        {id: 194, parkId: 157, parkName: "Community Park", features: "picnic",},
        {id: 195, parkId: 155, parkName: "ARTHUR K. DRAUT PARK", features: "picnic",},
        {id: 196, parkId: 156, parkName: "Brown Park", features: "picnic",},
        {id: 197, parkId: 6, parkName: "BINGHAM", features: "picnic",},
        {id: 198, parkId: 106, parkName: "BLACK MUDD", features: "picnic",},
        {id: 199, parkId: 107, parkName: "BLUE LICK", features: "picnic",},
        {id: 200, parkId: 45, parkName: "BOONE SQUARE", features: "picnic",},
        {id: 201, parkId: 7, parkName: "BRADLEY", features: "picnic",},
        {id: 202, parkId: 109, parkName: "BRESLIN", features: "picnic",},
        {id: 203, parkId: 8, parkName: "BUECHEL", features: "picnic",},
        {id: 204, parkId: 9, parkName: "CAMP TAYLOR", features: "picnic",},
        {id: 205, parkId: 16, parkName: "CARRIE GAULBERT COX", features: "picnic",},
        {id: 206, parkId: 12, parkName: "CENTRAL", features: "picnic",},
        {id: 207, parkId: 96, parkName: "CHARLIE VETTINER", features: "picnic",},
        {id: 208, parkId: 74, parkName: "CHEROKEE", features: "picnic",},
        {id: 209, parkId: 13, parkName: "CHICKASAW", features: "picnic",},
        {id: 210, parkId: 15, parkName: "CLIFTON", features: "picnic",},
        {id: 211, parkId: 87, parkName: "CROSBY", features: "picnic",},
        {id: 212, parkId: 90, parkName: "DES PRES", features: "picnic",},
        {id: 213, parkId: 17, parkName: "DOUGLASS", features: "picnic",},
        {id: 214, parkId: 76, parkName: "E. LELAND TAYLOR", features: "picnic",},
        {id: 215, parkId: 42, parkName: "ELLIOT SQUARE", features: "picnic",},
        {id: 216, parkId: 43, parkName: "EMERSON", features: "picnic",},
        {id: 217, parkId: 19, parkName: "FAIRDALE MINI", features: "picnic",},
        {id: 218, parkId: 112, parkName: "FARMAN", features: "picnic",},
        {id: 219, parkId: 86, parkName: "FARNSLEY", features: "picnic",},
        {id: 220, parkId: 113, parkName: "FERN CREEK", features: "picnic",},
        {id: 221, parkId: 114, parkName: "FISHERMAN'S", features: "picnic",},
        {id: 222, parkId: 54, parkName: "G.G. MOORE", features: "picnic",},
        {id: 223, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "picnic",},
        {id: 224, parkId: 29, parkName: "HAYS KENNEDY", features: "picnic",},
        {id: 225, parkId: 82, parkName: "HIGHVIEW", features: "picnic",},
        {id: 226, parkId: 26, parkName: "HOUNZ LANE", features: "picnic",},
        {id: 227, parkId: 58, parkName: "HUSTON QUIN", features: "picnic",},
        {id: 228, parkId: 97, parkName: "IROQUOIS", features: "picnic",},
        {id: 229, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "picnic",},
        {id: 230, parkId: 115, parkName: "JOE CREASON", features: "picnic",},
        {id: 231, parkId: 30, parkName: "KENNEDY COURT", features: "picnic",},
        {id: 232, parkId: 31, parkName: "KLONDIKE", features: "picnic",},
        {id: 233, parkId: 32, parkName: "KULMER RESERVE", features: "picnic",},
        {id: 234, parkId: 33, parkName: "LAKE DREAMLAND", features: "picnic",},
        {id: 235, parkId: 116, parkName: "LANNAN", features: "picnic",},
        {id: 236, parkId: 102, parkName: "LONG RUN", features: "picnic",},
        {id: 237, parkId: 51, parkName: "MAGNOLIA", features: "picnic",},
        {id: 238, parkId: 44, parkName: "MCNEELY LAKE", features: "picnic",},
        {id: 239, parkId: 38, parkName: "NORFOLK ACRES", features: "picnic",},
        {id: 240, parkId: 84, parkName: "OKOLONA", features: "picnic",},
        {id: 241, parkId: 55, parkName: "PARKHILL", features: "picnic",},
        {id: 242, parkId: 57, parkName: "PEEWEE", features: "picnic",},
        {id: 243, parkId: 117, parkName: "PETERSBURG", features: "picnic",},
        {id: 244, parkId: 80, parkName: "PORTLAND", features: "picnic",},
        {id: 245, parkId: 60, parkName: "RIVERSIDE GARDENS", features: "picnic",},
        {id: 246, parkId: 61, parkName: "RIVERVIEW", features: "picnic",},
        {id: 247, parkId: 63, parkName: "RUBEL", features: "picnic",},
        {id: 248, parkId: 48, parkName: "RUSSELL LEE", features: "picnic",},
        {id: 249, parkId: 98, parkName: "SENECA", features: "picnic",},
        {id: 250, parkId: 64, parkName: "SHAWNEE", features: "picnic",},
        {id: 251, parkId: 65, parkName: "SHELBY", features: "picnic",},
        {id: 252, parkId: 83, parkName: "SHEPPARD", features: "picnic",},
        {id: 253, parkId: 118, parkName: "SOUTH CENTRAL", features: "picnic",},
        {id: 254, parkId: 93, parkName: "SUN VALLEY", features: "picnic",},
        {id: 255, parkId: 67, parkName: "SYLVANIA", features: "picnic",},
        {id: 256, parkId: 100, parkName: "THURMAN HUTCHINS", features: "picnic",},
        {id: 257, parkId: 69, parkName: "TYLER", features: "picnic",},
        {id: 258, parkId: 88, parkName: "VICTORY", features: "picnic",},
        {id: 259, parkId: 70, parkName: "WATTERSON LAKE", features: "picnic",},
        {id: 260, parkId: 95, parkName: "WAVERLY", features: "picnic",},
        {id: 261, parkId: 23, parkName: "WILLIAM HARRISON", features: "picnic",},
        {id: 262, parkId: 72, parkName: "WILLOW", features: "picnic",},
        {id: 263, parkId: 120, parkName: "WYANDOTTE", features: "picnic",},
        {id: 264, parkId: 3, parkName: "ALGONQUIN", features: "volleyball",},
        {id: 265, parkId: 39, parkName: "CALIFORNIA", features: "volleyball",},
        {id: 266, parkId: 12, parkName: "CENTRAL", features: "volleyball",},
        {id: 267, parkId: 96, parkName: "CHARLIE VETTINER", features: "volleyball",},
        {id: 268, parkId: 13, parkName: "CHICKASAW", features: "volleyball",},
        {id: 269, parkId: 90, parkName: "DES PRES", features: "volleyball",},
        {id: 270, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "volleyball",},
        {id: 271, parkId: 97, parkName: "IROQUOIS", features: "volleyball",},
        {id: 272, parkId: 115, parkName: "JOE CREASON", features: "volleyball",},
        {id: 273, parkId: 116, parkName: "LANNAN", features: "volleyball",},
        {id: 274, parkId: 102, parkName: "LONG RUN", features: "volleyball",},
        {id: 275, parkId: 46, parkName: "OLD WALNUT / BEECHER", features: "volleyball",},
        {id: 276, parkId: 80, parkName: "PORTLAND", features: "volleyball",},
        {id: 277, parkId: 98, parkName: "SENECA", features: "volleyball",},
        {id: 278, parkId: 93, parkName: "SUN VALLEY", features: "volleyball",},
        {id: 279, parkId: 69, parkName: "TYLER", features: "volleyball",},
        {id: 280, parkId: 81, parkName: "WESTONIA", features: "volleyball",},
        {id: 281, parkId: 120, parkName: "WYANDOTTE", features: "volleyball",},
        {id: 282, parkId: 109, parkName: "BRESLIN", features: "skatepark",},
        {id: 283, parkId: 50, parkName: "DAVID ARMSTRONG EXTREME ", features: "skatepark",},
        {id: 284, parkId: 124, parkName: "A.B. SAWYER", features: "tennis",},
        {id: 285, parkId: 3, parkName: "ALGONQUIN", features: "tennis",},
        {id: 286, parkId: 103, parkName: "AUBURNDALE", features: "tennis",},
        {id: 287, parkId: 101, parkName: "BAXTER SQUARE", features: "tennis",},
        {id: 288, parkId: 105, parkName: "BERRYTOWN", features: "tennis",},
        {id: 289, parkId: 106, parkName: "BLACK MUDD", features: "tennis",},
        {id: 290, parkId: 107, parkName: "BLUE LICK", features: "tennis",},
        {id: 291, parkId: 8, parkName: "BUECHEL", features: "tennis",},
        {id: 292, parkId: 39, parkName: "CALIFORNIA", features: "tennis",},
        {id: 293, parkId: 12, parkName: "CENTRAL", features: "tennis",},
        {id: 294, parkId: 96, parkName: "CHARLIE VETTINER", features: "tennis",},
        {id: 295, parkId: 74, parkName: "CHEROKEE", features: "tennis",},
        {id: 296, parkId: 13, parkName: "CHICKASAW", features: "tennis",},
        {id: 297, parkId: 15, parkName: "CLIFTON", features: "tennis",},
        {id: 298, parkId: 87, parkName: "CROSBY", features: "tennis",},
        {id: 299, parkId: 90, parkName: "DES PRES", features: "tennis",},
        {id: 300, parkId: 86, parkName: "FARNSLEY", features: "tennis",},
        {id: 301, parkId: 113, parkName: "FERN CREEK", features: "tennis",},
        {id: 302, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "tennis",},
        {id: 303, parkId: 29, parkName: "HAYS KENNEDY", features: "tennis",},
        {id: 304, parkId: 82, parkName: "HIGHVIEW", features: "tennis",},
        {id: 305, parkId: 26, parkName: "HOUNZ LANE", features: "tennis",},
        {id: 306, parkId: 97, parkName: "IROQUOIS", features: "tennis",},
        {id: 307, parkId: 115, parkName: "JOE CREASON", features: "tennis",},
        {id: 308, parkId: 31, parkName: "KLONDIKE", features: "tennis",},
        {id: 309, parkId: 116, parkName: "LANNAN", features: "tennis",},
        {id: 310, parkId: 102, parkName: "LONG RUN", features: "tennis",},
        {id: 311, parkId: 44, parkName: "MCNEELY LAKE", features: "tennis",},
        {id: 312, parkId: 25, parkName: "NELSON HORNBECK", features: "tennis",},
        {id: 313, parkId: 84, parkName: "OKOLONA", features: "tennis",},
        {id: 314, parkId: 46, parkName: "OLD WALNUT / BEECHER", features: "tennis",},
        {id: 315, parkId: 117, parkName: "PETERSBURG", features: "tennis",},
        {id: 316, parkId: 48, parkName: "RUSSELL LEE", features: "tennis",},
        {id: 317, parkId: 98, parkName: "SENECA", features: "tennis",},
        {id: 318, parkId: 64, parkName: "SHAWNEE", features: "tennis",},
        {id: 319, parkId: 65, parkName: "SHELBY", features: "tennis",},
        {id: 320, parkId: 93, parkName: "SUN VALLEY", features: "tennis",},
        {id: 321, parkId: 67, parkName: "SYLVANIA", features: "tennis",},
        {id: 322, parkId: 119, parkName: "TOONERVILLE TROLLEY", features: "tennis",},
        {id: 323, parkId: 69, parkName: "TYLER", features: "tennis",},
        {id: 324, parkId: 95, parkName: "WAVERLY", features: "tennis",},
        {id: 325, parkId: 120, parkName: "WYANDOTTE", features: "tennis",},
        {id: 326, parkId: 124, parkName: "A.B. SAWYER", features: "restroom",},
        {id: 327, parkId: 3, parkName: "ALGONQUIN", features: "restroom",},
        {id: 328, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "restroom",},
        {id: 329, parkId: 105, parkName: "BERRYTOWN", features: "restroom",},
        {id: 330, parkId: 6, parkName: "BINGHAM", features: "restroom",},
        {id: 331, parkId: 45, parkName: "BOONE SQUARE", features: "restroom",},
        {id: 332, parkId: 109, parkName: "BRESLIN", features: "restroom",},
        {id: 333, parkId: 156, parkName: "Brown Park", features: "restroom",},
        {id: 334, parkId: 9, parkName: "CAMP TAYLOR", features: "restroom",},
        {id: 335, parkId: 16, parkName: "CARRIE GAULBERT COX", features: "restroom",},
        {id: 336, parkId: 12, parkName: "CENTRAL", features: "restroom",},
        {id: 337, parkId: 96, parkName: "CHARLIE VETTINER", features: "restroom",},
        {id: 338, parkId: 74, parkName: "CHEROKEE", features: "restroom",},
        {id: 339, parkId: 13, parkName: "CHICKASAW", features: "restroom",},
        {id: 340, parkId: 157, parkName: "Community Park", features: "restroom",},
        {id: 341, parkId: 87, parkName: "CROSBY", features: "restroom",},
        {id: 342, parkId: 50, parkName: "DAVID ARMSTRONG EXTREME ", features: "restroom",},
        {id: 343, parkId: 90, parkName: "DES PRES", features: "restroom",},
        {id: 344, parkId: 42, parkName: "ELLIOT SQUARE", features: "restroom",},
        {id: 345, parkId: 86, parkName: "FARNSLEY", features: "restroom",},
        {id: 346, parkId: 113, parkName: "FERN CREEK", features: "restroom",},
        {id: 347, parkId: 20, parkName: "FLAGET FIELD", features: "restroom",},
        {id: 348, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "restroom",},
        {id: 349, parkId: 29, parkName: "HAYS KENNEDY", features: "restroom",},
        {id: 350, parkId: 97, parkName: "IROQUOIS", features: "restroom",},
        {id: 351, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "restroom",},
        {id: 352, parkId: 115, parkName: "JOE CREASON", features: "restroom",},
        {id: 353, parkId: 116, parkName: "LANNAN", features: "restroom",},
        {id: 354, parkId: 125, parkName: "LOCUST GROVE", features: "restroom",},
        {id: 355, parkId: 102, parkName: "LONG RUN", features: "restroom",},
        {id: 356, parkId: 150, parkName: "LOUISVILLE CHAMPIONS soccer", features: "restroom",},
        {id: 357, parkId: 44, parkName: "MCNEELY LAKE", features: "restroom",},
        {id: 358, parkId: 25, parkName: "NELSON HORNBECK", features: "restroom",},
        {id: 359, parkId: 84, parkName: "OKOLONA", features: "restroom",},
        {id: 360, parkId: 117, parkName: "PETERSBURG", features: "restroom",},
        {id: 361, parkId: 80, parkName: "PORTLAND", features: "restroom",},
        {id: 362, parkId: 154, parkName: "QUAIL CHASE golf course ", features: "restroom",},
        {id: 363, parkId: 60, parkName: "RIVERSIDE GARDENS", features: "restroom",},
        {id: 364, parkId: 62, parkName: "RIVERSIDE, THE FARNSLEY-MOREMAN LANDING", features: "restroom",},
        {id: 365, parkId: 61, parkName: "RIVERVIEW", features: "restroom",},
        {id: 366, parkId: 160, parkName: "ROBSION PARK", features: "restroom",},
        {id: 367, parkId: 48, parkName: "RUSSELL LEE", features: "restroom",},
        {id: 368, parkId: 98, parkName: "SENECA", features: "restroom",},
        {id: 369, parkId: 64, parkName: "SHAWNEE", features: "restroom",},
        {id: 370, parkId: 65, parkName: "SHELBY", features: "restroom",},
        {id: 371, parkId: 93, parkName: "SUN VALLEY", features: "restroom",},
        {id: 372, parkId: 100, parkName: "THURMAN HUTCHINS", features: "restroom",},
        {id: 373, parkId: 69, parkName: "TYLER", features: "restroom",},
        {id: 374, parkId: 88, parkName: "VICTORY", features: "restroom",},
        {id: 375, parkId: 158, parkName: "Warwick Park", features: "restroom",},
        {id: 376, parkId: 81, parkName: "WESTONIA", features: "restroom",},
        {id: 377, parkId: 72, parkName: "WILLOW", features: "restroom",},
        {id: 378, parkId: 120, parkName: "WYANDOTTE", features: "restroom",},
        {id: 379, parkId: 157, parkName: "Community Park", features: "playground",},
        {id: 380, parkId: 87, parkName: "CROSBY", features: "playground",},
        {id: 381, parkId: 90, parkName: "DES PRES", features: "playground",},
        {id: 382, parkId: 17, parkName: "DOUGLASS", features: "playground",},
        {id: 383, parkId: 76, parkName: "E. LELAND TAYLOR", features: "playground",},
        {id: 384, parkId: 18, parkName: "EASTOVER", features: "playground",},
        {id: 385, parkId: 42, parkName: "ELLIOT SQUARE", features: "playground",},
        {id: 386, parkId: 43, parkName: "EMERSON", features: "playground",},
        {id: 387, parkId: 112, parkName: "FARMAN", features: "playground",},
        {id: 388, parkId: 86, parkName: "FARNSLEY", features: "playground",},
        {id: 389, parkId: 114, parkName: "FERN CREEK", features: "playground",},
        {id: 390, parkId: 20, parkName: "FLAGET FIELD", features: "playground",},
        {id: 391, parkId: 73, parkName: "GEORGE ROGERS CLARK", features: "playground",},
        {id: 392, parkId: 21, parkName: "GERMAN-PARISTOWN", features: "playground",},
        {id: 393, parkId: 59, parkName: "GINNY REICHARD", features: "playground",},
        {id: 394, parkId: 159, parkName: "Hal Warheim", features: "playground",},
        {id: 395, parkId: 29, parkName: "HAYS KENNEDY", features: "playground",},
        {id: 396, parkId: 82, parkName: "HIGHVIEW", features: "playground",},
        {id: 397, parkId: 24, parkName: "HOPEWELL", features: "playground",},
        {id: 398, parkId: 26, parkName: "HOUNZ LANE", features: "playground",},
        {id: 399, parkId: 58, parkName: "HUSTON QUIN", features: "playground",},
        {id: 400, parkId: 97, parkName: "IROQUOIS", features: "playground",},
        {id: 401, parkId: 91, parkName: "IVY COURT", features: "playground",},
        {id: 402, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "playground",},
        {id: 403, parkId: 115, parkName: "JOE CREASON", features: "playground",},
        {id: 404, parkId: 30, parkName: "KENNEDY COURT", features: "playground",},
        {id: 405, parkId: 31, parkName: "KLONDIKE", features: "playground",},
        {id: 406, parkId: 33, parkName: "LAKE DREAMLAND", features: "playground",},
        {id: 407, parkId: 116, parkName: "LANNAN", features: "playground",},
        {id: 408, parkId: 41, parkName: "LAPORTE", features: "playground",},
        {id: 409, parkId: 102, parkName: "LONG RUN", features: "playground",},
        {id: 410, parkId: 28, parkName: "LOUIS B. ISRAEL", features: "playground",},
        {id: 411, parkId: 51, parkName: "MAGNOLIA", features: "playground",},
        {id: 412, parkId: 44, parkName: "MCNEELY LAKE", features: "playground",},
        {id: 413, parkId: 52, parkName: "MEDORA", features: "playground",},
        {id: 414, parkId: 25, parkName: "NELSON HORNBECK", features: "playground",},
        {id: 415, parkId: 38, parkName: "NORFOLK ACRES", features: "playground",},
        {id: 416, parkId: 84, parkName: "OKOLONA", features: "playground",},
        {id: 417, parkId: 46, parkName: "OLD WALNUT / BEECHER", features: "playground",},
        {id: 418, parkId: 55, parkName: "PARKHILL", features: "playground",},
        {id: 419, parkId: 129, parkName: "PARKLAND playground", features: "playground",},
        {id: 420, parkId: 56, parkName: "PATTERSON", features: "playground",},
        {id: 421, parkId: 57, parkName: "PEEWEE", features: "playground",},
        {id: 422, parkId: 117, parkName: "PETERSBURG", features: "playground",},
        {id: 423, parkId: 80, parkName: "PORTLAND", features: "playground",},
        {id: 424, parkId: 60, parkName: "RIVERSIDE GARDENS", features: "playground",},
        {id: 425, parkId: 61, parkName: "RIVERVIEW", features: "playground",},
        {id: 426, parkId: 160, parkName: "ROBSION PARK", features: "playground",},
        {id: 427, parkId: 63, parkName: "RUBEL", features: "playground",},
        {id: 428, parkId: 48, parkName: "RUSSELL LEE", features: "playground",},
        {id: 429, parkId: 98, parkName: "SENECA", features: "playground",},
        {id: 430, parkId: 64, parkName: "SHAWNEE", features: "playground",},
        {id: 431, parkId: 65, parkName: "SHELBY", features: "playground",},
        {id: 432, parkId: 83, parkName: "SHEPPARD", features: "playground",},
        {id: 433, parkId: 47, parkName: "SLEVIN", features: "playground",},
        {id: 434, parkId: 118, parkName: "SOUTH CENTRAL", features: "playground",},
        {id: 435, parkId: 89, parkName: "ST LOUIS", features: "playground",},
        {id: 436, parkId: 66, parkName: "STORY AVENUE", features: "playground",},
        {id: 437, parkId: 93, parkName: "SUN VALLEY", features: "playground",},
        {id: 438, parkId: 67, parkName: "SYLVANIA", features: "playground",},
        {id: 439, parkId: 100, parkName: "THURMAN HUTCHINS", features: "playground",},
        {id: 440, parkId: 119, parkName: "TOONERVILLE TROLLEY", features: "playground",},
        {id: 441, parkId: 69, parkName: "TYLER", features: "playground",},
        {id: 442, parkId: 88, parkName: "VICTORY", features: "playground",},
        {id: 443, parkId: 158, parkName: "Warwick Park", features: "playground",},
        {id: 444, parkId: 95, parkName: "WAVERLY", features: "playground",},
        {id: 445, parkId: 81, parkName: "WESTONIA", features: "playground",},
        {id: 446, parkId: 23, parkName: "WILLIAM HARRISON", features: "playground",},
        {id: 447, parkId: 72, parkName: "WILLOW", features: "playground",},
        {id: 448, parkId: 120, parkName: "WYANDOTTE", features: "playground",},
        {id: 449, parkId: 150, parkName: "LOUISVILLE CHAMPIONS soccer", features: "soccer",},
        {id: 450, parkId: 44, parkName: "MCNEELY LAKE", features: "soccer",},
        {id: 451, parkId: 160, parkName: "ROBSION PARK", features: "soccer",},
        {id: 452, parkId: 64, parkName: "SHAWNEE", features: "soccer",},
        {id: 453, parkId: 93, parkName: "SUN VALLEY", features: "soccer",},
        {id: 454, parkId: 146, parkName: "POPE LICK PARK", features: "soccer",},
        {id: 455, parkId: 149, parkName: "A.B. SAWYER GREENWAY", features: "walking",},
        {id: 456, parkId: 3, parkName: "ALGONQUIN", features: "walking",},
        {id: 457, parkId: 122, parkName: "BEARGRASS CREEK GREENWAY AT IRISH HILL", features: "walking",},
        {id: 458, parkId: 135, parkName: "BECKLEY CREEK PARK", features: "walking",},
        {id: 459, parkId: 4, parkName: "BELLEVUE", features: "walking",},
        {id: 460, parkId: 107, parkName: "BLUE LICK", features: "walking",},
        {id: 461, parkId: 109, parkName: "BRESLIN", features: "walking",},
        {id: 462, parkId: 8, parkName: "BUECHEL", features: "walking",},
        {id: 463, parkId: 9, parkName: "CAMP TAYLOR", features: "walking",},
        {id: 464, parkId: 10, parkName: "CANE RUN", features: "walking",},
        {id: 465, parkId: 16, parkName: "CARRIE GAULBERT COX", features: "walking",},
        {id: 466, parkId: 12, parkName: "CENTRAL", features: "walking",},
        {id: 467, parkId: 96, parkName: "CHARLIE VETTINER", features: "walking",},
        {id: 468, parkId: 74, parkName: "CHEROKEE", features: "walking",},
        {id: 469, parkId: 13, parkName: "CHICKASAW", features: "walking",},
        {id: 470, parkId: 157, parkName: "Community Park", features: "walking",},
        {id: 471, parkId: 43, parkName: "EMERSON", features: "walking",},
        {id: 472, parkId: 19, parkName: "FAIRDALE MINI", features: "walking",},
        {id: 473, parkId: 113, parkName: "FERN CREEK", features: "walking",},
        {id: 474, parkId: 114, parkName: "FISHERMAN'S", features: "walking",},
        {id: 475, parkId: 20, parkName: "FLAGET FIELD", features: "walking",},
        {id: 476, parkId: 159, parkName: "Hal Warheim", features: "walking",},
        {id: 477, parkId: 29, parkName: "HAYS KENNEDY", features: "walking",},
        {id: 478, parkId: 82, parkName: "HIGHVIEW", features: "walking",},
        {id: 479, parkId: 97, parkName: "IROQUOIS", features: "walking",},
        {id: 480, parkId: 75, parkName: "JEFFERSON MEMORIAL FOREST", features: "walking",},
        {id: 481, parkId: 115, parkName: "JOE CREASON", features: "walking",},
        {id: 482, parkId: 30, parkName: "KENNEDY COURT", features: "walking",},
        {id: 483, parkId: 31, parkName: "KLONDIKE", features: "walking",},
        {id: 484, parkId: 32, parkName: "KULMER RESERVE", features: "walking",},
        {id: 485, parkId: 116, parkName: "LANNAN", features: "walking",},
        {id: 486, parkId: 102, parkName: "LONG RUN", features: "walking",},
        {id: 487, parkId: 44, parkName: "MCNEELY LAKE", features: "walking",},
        {id: 488, parkId: 38, parkName: "NORFOLK ACRES", features: "walking",},
        {id: 489, parkId: 136, parkName: "PATRIOTS PEACE MEMORIAL", features: "walking",},
        {id: 490, parkId: 79, parkName: "PORTLAND WHARF", features: "walking",},
        {id: 491, parkId: 36, parkName: "ROBERSON RUN", features: "walking",},
        {id: 492, parkId: 160, parkName: "ROBSION PARK", features: "walking",},
        {id: 493, parkId: 132, parkName: "SCHUFF LANE GREENWAY", features: "walking",},
        {id: 494, parkId: 98, parkName: "SENECA", features: "walking",},
        {id: 495, parkId: 64, parkName: "SHAWNEE", features: "walking",},
        {id: 496, parkId: 65, parkName: "SHELBY", features: "walking",},
        {id: 497, parkId: 83, parkName: "SHEPPARD", features: "walking",},
        {id: 498, parkId: 118, parkName: "SOUTH CENTRAL", features: "walking",},
        {id: 499, parkId: 100, parkName: "THURMAN HUTCHINS", features: "walking",},
        {id: 500, parkId: 69, parkName: "TYLER", features: "walking",},
        {id: 501, parkId: 88, parkName: "VICTORY", features: "walking",},
        {id: 502, parkId: 131, parkName: "WATSON LANE TRAILHEAD", features: "walking",},
        {id: 503, parkId: 70, parkName: "WATTERSON LAKE", features: "walking",},
        {id: 504, parkId: 78, parkName: "WILLIAM BRITT", features: "walking",},
        {id: 505, parkId: 72, parkName: "WILLOW", features: "walking",},
        {id: 506, parkId: 120, parkName: "WYANDOTTE", features: "walking",},
        {id: 507, parkId: 153, parkName: "THE STRAND", features: "walking",},
        {id: 508, parkId: 153, parkName: "THE STRAND", features: "picnic",},
        {id: 509, parkId: 147, parkName: "TURKEY RUN", features: "fishing",},
        {id: 510, parkId: 153, parkName: "THE STRAND", features: "restroom",},
        {id: 511, parkId: 161, parkName: "AUBURN PARK", features: "picnic",},
        {id: 512, parkId: 162, parkName: "AUBURN PARK", features: "playground",},
        {id: 513, parkId: 87, parkName: "CROSBY", features: "little library",},
        {id: 514, parkId: 43, parkName: "EMERSON", features: "little library",},
        {id: 515, parkId: 159, parkName: "Hal Warheim", features: "little library",},
        {id: 516, parkId: 160, parkName: "ROBSION PARK", features: "little library",},
        {id: 517, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "basketball",},
        {id: 518, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "multiifield",},
        {id: 519, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "playground",},
        {id: 520, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "sprayground",},
        {id: 521, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "restroom",},
        {id: 522, parkId: 123, parkName: "WILLIAM B. STANSBURY", features: "tennis",},
        {id: 523, parkId: 59, parkName: "GINNY REICHARD", features: "no swings",},
        {id: 524, parkId: 22, parkName: "GNADINGER", features: "benches",},
        {id: 525, parkId: 167, parkName: "Mount Washington Community Park", features: "little library",},
        {id: 526, parkId: 167, parkName: "Mount Washington Community Park", features: "walking",},
        {id: 527, parkId: 167, parkName: "Mount Washington Community Park", features: "tennis",},
        {id: 528, parkId: 167, parkName: "Mount Washington Community Park", features: "basketball",},
        {id: 529, parkId: 167, parkName: "Mount Washington Community Park", features: "volleyball",},
        {id: 530, parkId: 167, parkName: "Mount Washington Community Park", features: "soccer",},
        {id: 531, parkId: 167, parkName: "Mount Washington Community Park", features: "baseball",},
        {id: 532, parkId: 167, parkName: "Mount Washington Community Park", features: "dog park",},
        {id: 533, parkId: 167, parkName: "Mount Washington Community Park", features: "amphitheatre",},
        {id: 534, parkId: 97, parkName: "IROQUOIS", features: "amphitheatre",},
        {id: 535, parkId: 168, parkName: "Lindsay Duvall", features: "playground",},
        {id: 536, parkId: 168, parkName: "Lindsay Duvall", features: "tennis",},
        {id: 537, parkId: 168, parkName: "Lindsay Duvall", features: "skatepark",},
        {id: 538, parkId: 169, parkName: "Cornell Park", features: "playground",},
        {id: 539, parkId: 169, parkName: "Cornell Park", features: "multiifield",},
        {id: 540, parkId: 170, parkName: "Maples Park", features: "playground",},
        {id: 541, parkId: 170, parkName: "Maples Park", features: "picnic",},
        {id: 542, parkId: 170, parkName: "Maples Park", features: "sprayground",},
        {id: 543, parkId: 170, parkName: "Maples Park", features: "swings",},
        {id: 544, parkId: 170, parkName: "Maples Park", features: "restroom",},
        {id: 545, parkId: 171, parkName: "Briar Hill Park", features: "restroom",},
        {id: 546, parkId: 171, parkName: "Briar Hill Park", features: "picnic",},
        {id: 547, parkId: 171, parkName: "Briar Hill Park", features: "playground",},
        {id: 548, parkId: 171, parkName: "Briar Hill Park", features: "basketball",},
        {id: 549, parkId: 171, parkName: "Briar Hill Park", features: "walking",},
        {id: 550, parkId: 171, parkName: "Briar Hill Park", features: "volleyball",},
        {id: 551, parkId: 171, parkName: "Briar Hill Park", features: "tennis",},
        {id: 552, parkId: 171, parkName: "Briar Hill Park", features: "hiking",},
        {id: 553, parkId: 171, parkName: "Briar Hill Park", features: "little library",},
        {id: 554, parkId: 172, parkName: "Wendell Moore Park", features: "community center",},
        {id: 555, parkId: 172, parkName: "Wendell Moore Park", features: "football",},
        {id: 556, parkId: 172, parkName: "Wendell Moore Park", features: "softball",},
        {id: 557, parkId: 172, parkName: "Wendell Moore Park", features: "fishing",},
        {id: 558, parkId: 172, parkName: "Wendell Moore Park", features: "picnic",},
        {id: 559, parkId: 172, parkName: "Wendell Moore Park", features: "archery",},
        {id: 560, parkId: 172, parkName: "Wendell Moore Park", features: "walking",},
        {id: 561, parkId: 172, parkName: "Wendell Moore Park", features: "tennis",},
        {id: 562, parkId: 172, parkName: "Wendell Moore Park", features: "dog park",},
        {id: 563, parkId: 172, parkName: "Wendell Moore Park", features: "disc golf",},
        {id: 564, parkId: 172, parkName: "Wendell Moore Park", features: "restroom",},
        {id: 565, parkId: 172, parkName: "Wendell Moore Park", features: "playground",},
        {id: 566, parkId: 172, parkName: "Wendell Moore Park", features: "swimming",},
        {id: 567, parkId: 74, parkName: "CHEROKEE", features: "archery",},
        {id: 568, parkId: 97, parkName: "IROQUOIS", features: "disc golf",},
        {id: 569, parkId: 96, parkName: "CHARLIE VETTINER", features: "disc golf",},
        {id: 570, parkId: 173, parkName: "Schamback Park", features: "picnic",},
        {id: 571, parkId: 173, parkName: "Schamback Park", features: "restroom",},
        {id: 572, parkId: 173, parkName: "Schamback Park", features: "playground",},
        {id: 573, parkId: 173, parkName: "Schamback Park", features: "basketball",},
        {id: 574, parkId: 173, parkName: "Schamback Park", features: "fishing",},
        {id: 575, parkId: 174, parkName: "Peggy E. Baker Park", features: "picnic",},
        {id: 576, parkId: 174, parkName: "Peggy E. Baker Park", features: "restroom",},
        {id: 577, parkId: 174, parkName: "Peggy E. Baker Park", features: "playground",},
        {id: 578, parkId: 174, parkName: "Peggy E. Baker Park", features: "basketball",},
        {id: 579, parkId: 174, parkName: "Peggy E. Baker Park", features: "baseball",},
        {id: 580, parkId: 174, parkName: "Peggy E. Baker Park", features: "dog park",},
        {id: 581, parkId: 174, parkName: "Peggy E. Baker Park", features: "walking",},
        {id: 582, parkId: 174, parkName: "Peggy E. Baker Park", features: "little library",},
        {id: 583, parkId: 175, parkName: "Morgan Conservation Park", features: "hiking",},
        {id: 584, parkId: 175, parkName: "Morgan Conservation Park", features: "picnic",},
        {id: 585, parkId: 175, parkName: "Morgan Conservation Park", features: "restroom",},
        {id: 586, parkId: 176, parkName: "54 Acre multii-Use Park", features: "soccer",},
        {id: 587, parkId: 176, parkName: "54 Acre multii-Use Park", features: "multiifield",},
        {id: 588, parkId: 177, parkName: "Celebration Park", features: "",},
        {id: 589, parkId: 178, parkName: "Creasey Mahan Nature Preserve", features: "Manor",},
        {id: 590, parkId: 178, parkName: "Creasey Mahan Nature Preserve", features: "nature center",},
        {id: 591, parkId: 178, parkName: "Creasey Mahan Nature Preserve", features: "Gardens",},
        {id: 592, parkId: 178, parkName: "Creasey Mahan Nature Preserve", features: "hiking",},
        {id: 593, parkId: 178, parkName: "Creasey Mahan Nature Preserve", features: "Park",},
        {id: 594, parkId: 179, parkName: "PeeWEE Valley Central Park", features: "walking",},
        {id: 595, parkId: 180, parkName: "Walsh Park", features: "playground",},
        {id: 596, parkId: 180, parkName: "Walsh Park", features: "swings",},
        {id: 597, parkId: 180, parkName: "Walsh Park", features: "picnic",},
        {id: 598, parkId: 180, parkName: "Walsh Park", features: "restroom",},
        {id: 599, parkId: 180, parkName: "Walsh Park", features: "baseball",},
        {id: 600, parkId: 181, parkName: "Wilborn Park", features: "playground",},
        {id: 601, parkId: 181, parkName: "Wilborn Park", features: "swings",},
        {id: 602, parkId: 181, parkName: "Wilborn Park", features: "fishing",},
        {id: 603, parkId: 181, parkName: "Wilborn Park", features: "walking",},
        {id: 604, parkId: 181, parkName: "Wilborn Park", features: "hiking",},
        {id: 605, parkId: 181, parkName: "Wilborn Park", features: "restroom",},
        {id: 606, parkId: 181, parkName: "Wilborn Park", features: "picnic",},
        {id: 607, parkId: 182, parkName: "Shirley's Arbor", features: "retention pond",},
        {id: 608, parkId: 182, parkName: "Shirley's Arbor", features: "exercise stations",},
        {id: 609, parkId: 182, parkName: "Shirley's Arbor", features: "Park benches",},
        {id: 610, parkId: 182, parkName: "Shirley's Arbor", features: "walking",},
        {id: 611, parkId: 182, parkName: "Shirley's Arbor", features: "multiifield",},
        {id: 612, parkId: 183, parkName: "Chapel Lake Park", features: "fishing",},
        {id: 613, parkId: 183, parkName: "Chapel Lake Park", features: "picnic",},
        {id: 614, parkId: 183, parkName: "Chapel Lake Park", features: "playground",},
        {id: 615, parkId: 183, parkName: "Chapel Lake Park", features: "walking",},
        {id: 616, parkId: 183, parkName: "Chapel Lake Park", features: "hiking",},
        {id: 617, parkId: 183, parkName: "Chapel Lake Park", features: "restroom",},
        {id: 618, parkId: 184, parkName: "Perrin Family Park", features: "Catherine's Teddy Bear Place",},
        {id: 619, parkId: 184, parkName: "Perrin Family Park", features: "Sandbox",},
        {id: 620, parkId: 184, parkName: "Perrin Family Park", features: "playground",},
        {id: 621, parkId: 184, parkName: "Perrin Family Park", features: "picnic",},
        {id: 622, parkId: 184, parkName: "Perrin Family Park", features: "walking",},
        {id: 623, parkId: 185, parkName: "Glossbrenner Public Garden", features: "Gardens",},
        {id: 624, parkId: 185, parkName: "Glossbrenner Public Garden", features: "benches",},
        {id: 625, parkId: 186, parkName: "Harmony Park", features: "Musical Instruments",},
        {id: 626, parkId: 186, parkName: "Harmony Park", features: "Murals",},
        {id: 627, parkId: 186, parkName: "Harmony Park", features: "stage",},
        {id: 628, parkId: 187, parkName: "Big 4 Station Park", features: "Farmers Market",},
        {id: 629, parkId: 187, parkName: "Big 4 Station Park", features: "playground",},
        {id: 630, parkId: 187, parkName: "Big 4 Station Park", features: "benches",},
        {id: 631, parkId: 187, parkName: "Big 4 Station Park", features: "picnic",},
        {id: 632, parkId: 187, parkName: "Big 4 Station Park", features: "walking",},
        {id: 633, parkId: 188, parkName: "Jeffersonville skate Park", features: "skatepark",},
        {id: 634, parkId: 188, parkName: "Jeffersonville skate Park", features: "walking",},
        {id: 635, parkId: 189, parkName: "Shirley Hall Park", features: "football",},
        {id: 636, parkId: 189, parkName: "Shirley Hall Park", features: "walking",},
        {id: 637, parkId: 189, parkName: "Shirley Hall Park", features: "restroom",},
        {id: 638, parkId: 189, parkName: "Shirley Hall Park", features: "concessions",},
        {id: 639, parkId: 190, parkName: "Woehrle Athletic Complex", features: "concessions",},
        {id: 640, parkId: 190, parkName: "Woehrle Athletic Complex", features: "soccer",},
        {id: 641, parkId: 190, parkName: "Woehrle Athletic Complex", features: "football",},
        {id: 642, parkId: 190, parkName: "Woehrle Athletic Complex", features: "playground",},
        {id: 643, parkId: 190, parkName: "Woehrle Athletic Complex", features: "drinking fountain",},
        {id: 644, parkId: 190, parkName: "Woehrle Athletic Complex", features: "conference",},
        {id: 645, parkId: 191, parkName: "Riverstage", features: "stage",},
        {id: 646, parkId: 191, parkName: "Riverstage", features: "walking",},
        {id: 647, parkId: 191, parkName: "Riverstage", features: "benches",},
        {id: 648, parkId: 192, parkName: "Nachand Fieldhouse", features: "exercise stations",},
        {id: 649, parkId: 192, parkName: "Nachand Fieldhouse", features: "volleyball",},
        {id: 650, parkId: 192, parkName: "Nachand Fieldhouse", features: "basketball",},
        {id: 651, parkId: 192, parkName: "Nachand Fieldhouse", features: "walking",},
        {id: 652, parkId: 192, parkName: "Nachand Fieldhouse", features: "restroom",},
        {id: 653, parkId: 193, parkName: "Jeffersonville Aquatic Center", features: "swimming",},
        {id: 654, parkId: 193, parkName: "Jeffersonville Aquatic Center", features: "restroom",},
        {id: 655, parkId: 194, parkName: "Veterans Memorial Park", features: "Memorials",},
        {id: 656, parkId: 194, parkName: "Veterans Memorial Park", features: "benches",},
        {id: 657, parkId: 195, parkName: "W.F. Throckmorton Park", features: "benches",},
        {id: 658, parkId: 195, parkName: "W.F. Throckmorton Park", features: "picnic",},
        {id: 659, parkId: 195, parkName: "W.F. Throckmorton Park", features: "playground",},
        {id: 660, parkId: 195, parkName: "W.F. Throckmorton Park", features: "tennis",},
        {id: 661, parkId: 196, parkName: "Samuel G. Shannon Memorial Park", features: "baseball",},
        {id: 662, parkId: 196, parkName: "Samuel G. Shannon Memorial Park", features: "restroom",},
        {id: 663, parkId: 197, parkName: "Richard L. Vissing Park", features: "walking",},
        {id: 664, parkId: 197, parkName: "Richard L. Vissing Park", features: "baseball",},
        {id: 665, parkId: 197, parkName: "Richard L. Vissing Park", features: "restroom",},
        {id: 666, parkId: 197, parkName: "Richard L. Vissing Park", features: "playground",},
        {id: 667, parkId: 197, parkName: "Richard L. Vissing Park", features: "basketball",},
        {id: 668, parkId: 217, parkName: "Allison Brook Park", features: "benches",},
        {id: 669, parkId: 217, parkName: "Allison Brook Park", features: "playground",},
        {id: 670, parkId: 217, parkName: "Allison Brook Park", features: "walking",},
        {id: 671, parkId: 198, parkName: "Highland dog park", features: "dog park",},
        {id: 672, parkId: 198, parkName: "Highland dog park", features: "benches",},
        {id: 673, parkId: 198, parkName: "Highland dog park", features: "picnic",},
        {id: 674, parkId: 198, parkName: "Highland dog park", features: "basketball",},
        {id: 675, parkId: 198, parkName: "Highland dog park", features: "playground",},
        {id: 676, parkId: 199, parkName: "John Wilcoxson Park", features: "playground",},
        {id: 677, parkId: 199, parkName: "John Wilcoxson Park", features: "picnic",},
        {id: 678, parkId: 199, parkName: "John Wilcoxson Park", features: "benches",},
        {id: 679, parkId: 200, parkName: "Richard B. Wathen Park", features: "playground",},
        {id: 680, parkId: 200, parkName: "Richard B. Wathen Park", features: "restroom",},
        {id: 681, parkId: 200, parkName: "Richard B. Wathen Park", features: "pond",},
        {id: 682, parkId: 200, parkName: "Richard B. Wathen Park", features: "picnic",},
        {id: 683, parkId: 201, parkName: "Luther F. Warder Park", features: "gazebo",},
        {id: 684, parkId: 201, parkName: "Luther F. Warder Park", features: "statue",},
        {id: 685, parkId: 201, parkName: "Luther F. Warder Park", features: "walking",},
        {id: 686, parkId: 202, parkName: "Steamboat Park", features: "little library",},
        {id: 687, parkId: 202, parkName: "Steamboat Park", features: "picnic",},
        {id: 688, parkId: 202, parkName: "Steamboat Park", features: "benches",},
        {id: 689, parkId: 203, parkName: "S. Harlan Vogt Park", features: "picnic",},
        {id: 690, parkId: 203, parkName: "S. Harlan Vogt Park", features: "benches",},
        {id: 691, parkId: 204, parkName: "Preservation Park", features: "benches",},
        {id: 692, parkId: 204, parkName: "Preservation Park", features: "train station",},
        {id: 693, parkId: 205, parkName: "Port Fulton Park", features: "playground",},
        {id: 694, parkId: 205, parkName: "Port Fulton Park", features: "picnic",},
        {id: 695, parkId: 205, parkName: "Port Fulton Park", features: "restroom",},
        {id: 696, parkId: 205, parkName: "Port Fulton Park", features: "benches",},
        {id: 697, parkId: 206, parkName: "Poppy Park", features: "playground",},
        {id: 698, parkId: 208, parkName: "Lottie Oglesby Park", features: "walking",},
        {id: 699, parkId: 208, parkName: "Lottie Oglesby Park", features: "basketball",},
        {id: 700, parkId: 208, parkName: "Lottie Oglesby Park", features: "benches",},
        {id: 701, parkId: 209, parkName: "Kyle Vissing Park", features: "basketball",},
        {id: 702, parkId: 209, parkName: "Kyle Vissing Park", features: "pond",},
        {id: 703, parkId: 209, parkName: "Kyle Vissing Park", features: "playground",},
        {id: 704, parkId: 210, parkName: "Pamela J Inman Park", features: "playground",},
        {id: 705, parkId: 210, parkName: "Pamela J Inman Park", features: "picnic",},
        {id: 706, parkId: 211, parkName: "Henry Landsen Park", features: "benches",},
        {id: 707, parkId: 211, parkName: "Henry Landsen Park", features: "gazebo",},
        {id: 708, parkId: 211, parkName: "Henry Landsen Park", features: "walking",},
        {id: 709, parkId: 211, parkName: "Henry Landsen Park", features: "restroom",},
        {id: 710, parkId: 212, parkName: "Gaither Park", features: "sculpture",},
        {id: 711, parkId: 212, parkName: "Gaither Park", features: "benches",},
        {id: 712, parkId: 213, parkName: "Forest Park", features: "benches",},
        {id: 713, parkId: 213, parkName: "Forest Park", features: "picnic",},
        {id: 714, parkId: 213, parkName: "Forest Park", features: "playground",},
        {id: 715, parkId: 214, parkName: "James T. Duffy Landing", features: "boat ramp",},
        {id: 716, parkId: 214, parkName: "James T. Duffy Landing", features: "restroom",},
        {id: 717, parkId: 214, parkName: "James T. Duffy Landing", features: "playground",},
        {id: 718, parkId: 215, parkName: "Connie Sellmer Park", features: "playground",},
        {id: 719, parkId: 215, parkName: "Connie Sellmer Park", features: "benches",},
        {id: 720, parkId: 215, parkName: "Connie Sellmer Park", features: "picnic",},
        {id: 721, parkId: 216, parkName: "Bob Hedge Park", features: "playground",},
        {id: 722, parkId: 216, parkName: "Bob Hedge Park", features: "exercise stations",},
        {id: 723, parkId: 216, parkName: "Bob Hedge Park", features: "picnic",},
        {id: 724, parkId: 216, parkName: "Bob Hedge Park", features: "little library",},
        {id: 725, parkId: 218, parkName: "Ashland Park", features: "playground",},
        {id: 726, parkId: 218, parkName: "Ashland Park", features: "picnic",},
        {id: 727, parkId: 218, parkName: "Ashland Park", features: "walking",},
        {id: 728, parkId: 219, parkName: "Beechwood Park", features: "playground",},
        {id: 729, parkId: 219, parkName: "Beechwood Park", features: "basketball",},
        {id: 730, parkId: 219, parkName: "Beechwood Park", features: "picnic",},
        {id: 731, parkId: 220, parkName: "Cedar Park", features: "basketball",},
        {id: 732, parkId: 220, parkName: "Cedar Park", features: "playground",},
        {id: 733, parkId: 221, parkName: "Colgate Park", features: "basketball",},
        {id: 734, parkId: 221, parkName: "Colgate Park", features: "playground",},
        {id: 735, parkId: 221, parkName: "Colgate Park", features: "tennis",},
        {id: 736, parkId: 221, parkName: "Colgate Park", features: "picnic",},
        {id: 737, parkId: 221, parkName: "Colgate Park", features: "swimming",},
        {id: 738, parkId: 222, parkName: "Gaskell Park", features: "picnic",},
        {id: 739, parkId: 222, parkName: "Gaskell Park", features: "playground",},
        {id: 740, parkId: 222, parkName: "Gaskell Park", features: "basketball",},
        {id: 741, parkId: 223, parkName: "Gateway Park", features: "restroom",},
        {id: 742, parkId: 223, parkName: "Gateway Park", features: "playground",},
        {id: 743, parkId: 223, parkName: "Gateway Park", features: "splash pad",},
        {id: 744, parkId: 223, parkName: "Gateway Park", features: "event lawn",},
        {id: 745, parkId: 223, parkName: "Gateway Park", features: "stage",},
        {id: 746, parkId: 223, parkName: "Gateway Park", features: "baseball",},
        {id: 747, parkId: 223, parkName: "Gateway Park", features: "walking",},
        {id: 748, parkId: 224, parkName: "Lapping Park", features: "golf",},
        {id: 749, parkId: 224, parkName: "Lapping Park", features: "softball",},
        {id: 750, parkId: 224, parkName: "Lapping Park", features: "concessions",},
        {id: 751, parkId: 224, parkName: "Lapping Park", features: "restroom",},
        {id: 752, parkId: 224, parkName: "Lapping Park", features: "walking",},
        {id: 753, parkId: 224, parkName: "Lapping Park", features: "disc golf",},
        {id: 754, parkId: 224, parkName: "Lapping Park", features: "basketball",},
        {id: 755, parkId: 224, parkName: "Lapping Park", features: "horseshoes",},
        {id: 756, parkId: 224, parkName: "Lapping Park", features: "volleyball",},
        {id: 757, parkId: 224, parkName: "Lapping Park", features: "picnic",},
        {id: 758, parkId: 224, parkName: "Lapping Park", features: "amphitheatre",},
        {id: 759, parkId: 225, parkName: "Lewis and Clark Park", features: "george rogers clark cabin",},
        {id: 760, parkId: 226, parkName: "Parkwood Park", features: "baseball",},
        {id: 761, parkId: 226, parkName: "Parkwood Park", features: "football",},
        {id: 762, parkId: 226, parkName: "Parkwood Park", features: "soccer",},
        {id: 763, parkId: 226, parkName: "Parkwood Park", features: "playground",},
        {id: 764, parkId: 227, parkName: "Ray Lawrence Park", features: "tennis",},
        {id: 765, parkId: 227, parkName: "Ray Lawrence Park", features: "picnic",},
        {id: 766, parkId: 227, parkName: "Ray Lawrence Park", features: "tennis",},
        {id: 767, parkId: 227, parkName: "Ray Lawrence Park", features: "Pickleball",},
        {id: 768, parkId: 227, parkName: "Ray Lawrence Park", features: "playground",},
        {id: 769, parkId: 228, parkName: "Anderson Park", features: "softball",},
        {id: 770, parkId: 228, parkName: "Anderson Park", features: "restroom",},
        {id: 771, parkId: 228, parkName: "Anderson Park", features: "concessions",},
        {id: 772, parkId: 229, parkName: "Bicknell Park", features: "picnic",},
        {id: 773, parkId: 229, parkName: "Bicknell Park", features: "basketball",},
        {id: 774, parkId: 229, parkName: "Bicknell Park", features: "walking",},
        {id: 775, parkId: 229, parkName: "Bicknell Park", features: "playground",},
        {id: 776, parkId: 229, parkName: "Bicknell Park", features: "restroom",},
        {id: 777, parkId: 229, parkName: "Bicknell Park", features: "multiifield",},
        {id: 778, parkId: 230, parkName: "Billy Herman Park", features: "baseball",},
        {id: 779, parkId: 230, parkName: "Billy Herman Park", features: "walking",},
        {id: 780, parkId: 230, parkName: "Billy Herman Park", features: "restroom",},
        {id: 781, parkId: 230, parkName: "Billy Herman Park", features: "concessions",},
        {id: 782, parkId: 231, parkName: "Binford Park", features: "concessions",},
        {id: 783, parkId: 231, parkName: "Binford Park", features: "restroom",},
        {id: 784, parkId: 231, parkName: "Binford Park", features: "basketball",},
        {id: 785, parkId: 231, parkName: "Binford Park", features: "playground",},
        {id: 786, parkId: 231, parkName: "Binford Park", features: "soccer",},
        {id: 787, parkId: 232, parkName: "Cannon Acres soccer Field", features: "soccer",},
        {id: 788, parkId: 234, parkName: "Divison Street Park", features: "basketball",},
        {id: 789, parkId: 233, parkName: "Cherry Valley golf course", features: "golf",},
        {id: 790, parkId: 235, parkName: "Fairmont Park", features: "picnic",},
        {id: 791, parkId: 235, parkName: "Fairmont Park", features: "baseball",},
        {id: 792, parkId: 235, parkName: "Fairmont Park", features: "playground",},
        {id: 793, parkId: 235, parkName: "Fairmont Park", features: "basketball",},
        {id: 794, parkId: 235, parkName: "Fairmont Park", features: "walking",},
        {id: 795, parkId: 236, parkName: "Griffin Receration Center", features: "restroom",},
        {id: 796, parkId: 236, parkName: "Griffin Receration Center", features: "exercise stations",},
        {id: 797, parkId: 236, parkName: "Griffin Receration Center", features: "softball",},
        {id: 798, parkId: 236, parkName: "Griffin Receration Center", features: "basketball",},
        {id: 799, parkId: 236, parkName: "Griffin Receration Center", features: "volleyball",},
        {id: 800, parkId: 236, parkName: "Griffin Receration Center", features: "disc golf",},
        {id: 801, parkId: 236, parkName: "Griffin Receration Center", features: "horseshoes",},
        {id: 802, parkId: 237, parkName: "Joe Kraft Park", features: "playground",},
        {id: 803, parkId: 237, parkName: "Joe Kraft Park", features: "baseball",},
        {id: 804, parkId: 237, parkName: "Joe Kraft Park", features: "basketball",},
        {id: 805, parkId: 238, parkName: "Millerwood Park", features: "basketball",},
        {id: 806, parkId: 238, parkName: "Millerwood Park", features: "walking",},
        {id: 807, parkId: 238, parkName: "Millerwood Park", features: "playground",},
        {id: 808, parkId: 239, parkName: "New Albany dog park", features: "dog park",},
        {id: 809, parkId: 239, parkName: "New Albany dog park", features: "swings",},
        {id: 810, parkId: 239, parkName: "New Albany dog park", features: "gazebo",},
        {id: 811, parkId: 239, parkName: "New Albany dog park", features: "benches",},
        {id: 812, parkId: 240, parkName: "Ritter Park", features: "playground",},
        {id: 813, parkId: 240, parkName: "Ritter Park", features: "picnic",},
        {id: 814, parkId: 240, parkName: "Ritter Park", features: "basketball",},
        {id: 815, parkId: 240, parkName: "Ritter Park", features: "benches",},
        {id: 816, parkId: 240, parkName: "Ritter Park", features: "volleyball",},
        {id: 817, parkId: 240, parkName: "Ritter Park", features: "walking",},
        {id: 818, parkId: 240, parkName: "Ritter Park", features: "multiifield",},
        {id: 819, parkId: 241, parkName: "River Run Family Waterpark", features: "swimming",},
        {id: 820, parkId: 241, parkName: "River Run Family Waterpark", features: "splash pad",},
        {id: 821, parkId: 241, parkName: "River Run Family Waterpark", features: "lazy river",},
        {id: 822, parkId: 242, parkName: "Sertoma Park", features: "picnic",},
        {id: 823, parkId: 242, parkName: "Sertoma Park", features: "playground",},
        {id: 824, parkId: 242, parkName: "Sertoma Park", features: "basketball",},
        {id: 825, parkId: 242, parkName: "Sertoma Park", features: "volleyball",},
        {id: 826, parkId: 242, parkName: "Sertoma Park", features: "baseball",},
        {id: 827, parkId: 242, parkName: "Sertoma Park", features: "restroom",},
        {id: 828, parkId: 243, parkName: "Silver Street Park", features: "football",},
        {id: 829, parkId: 243, parkName: "Silver Street Park", features: "soccer",},
        {id: 830, parkId: 243, parkName: "Silver Street Park", features: "basketball",},
        {id: 831, parkId: 243, parkName: "Silver Street Park", features: "skatepark",},
        {id: 832, parkId: 243, parkName: "Silver Street Park", features: "splash pad",},
        {id: 833, parkId: 243, parkName: "Silver Street Park", features: "playground",},
        {id: 834, parkId: 243, parkName: "Silver Street Park", features: "walking",},
        {id: 835, parkId: 243, parkName: "Silver Street Park", features: "picnic",},
        {id: 836, parkId: 243, parkName: "Silver Street Park", features: "baseball",},
        {id: 837, parkId: 243, parkName: "Silver Street Park", features: "entertainment pavillion",},
        {id: 838, parkId: 244, parkName: "Valley View golf Club", features: "golf",},
        {id: 839, parkId: 247, parkName: "Campbell Woodland Nature Trails", features: "walking",},
        {id: 840, parkId: 247, parkName: "Campbell Woodland Nature Trails", features: "hiking",},
        {id: 841, parkId: 247, parkName: "Campbell Woodland Nature Trails", features: "benches",},
        {id: 842, parkId: 247, parkName: "Campbell Woodland Nature Trails", features: "gazebo",},
        {id: 843, parkId: 245, parkName: "Bicentennial Park", features: "stage",},
        {id: 844, parkId: 246, parkName: "Riverfront Amphitheater", features: "amphitheatre",},
        {id: 845, parkId: 248, parkName: "Galena-Lamb Park", features: "picnic",},
        {id: 846, parkId: 248, parkName: "Galena-Lamb Park", features: "restroom",},
        {id: 847, parkId: 248, parkName: "Galena-Lamb Park", features: "softball",},
        {id: 848, parkId: 248, parkName: "Galena-Lamb Park", features: "basketball",},
        {id: 849, parkId: 248, parkName: "Galena-Lamb Park", features: "football",},
        {id: 850, parkId: 248, parkName: "Galena-Lamb Park", features: "soccer",},
        {id: 851, parkId: 248, parkName: "Galena-Lamb Park", features: "playground",},
        {id: 852, parkId: 249, parkName: "Garry E. Cavan Park", features: "picnic",},
        {id: 853, parkId: 249, parkName: "Garry E. Cavan Park", features: "disc golf",},
        {id: 854, parkId: 249, parkName: "Garry E. Cavan Park", features: "tennis",},
        {id: 855, parkId: 249, parkName: "Garry E. Cavan Park", features: "playground",},
        {id: 856, parkId: 249, parkName: "Garry E. Cavan Park", features: "horseshoes",},
        {id: 857, parkId: 249, parkName: "Garry E. Cavan Park", features: "restroom",},
        {id: 858, parkId: 249, parkName: "Garry E. Cavan Park", features: "basketball",},
        {id: 859, parkId: 249, parkName: "Garry E. Cavan Park", features: "multiifield",},
        {id: 860, parkId: 250, parkName: "Greenville Park", features: "picnic",},
        {id: 861, parkId: 250, parkName: "Greenville Park", features: "restroom",},
        {id: 862, parkId: 250, parkName: "Greenville Park", features: "playground",},
        {id: 863, parkId: 250, parkName: "Greenville Park", features: "basketball",},
        {id: 864, parkId: 250, parkName: "Greenville Park", features: "Pickleball",},
        {id: 865, parkId: 250, parkName: "Greenville Park", features: "walking",},
        {id: 866, parkId: 250, parkName: "Greenville Park", features: "softball",},
        {id: 867, parkId: 251, parkName: "Herman Collier Park", features: "basketball",},
        {id: 868, parkId: 251, parkName: "Herman Collier Park", features: "restroom",},
        {id: 869, parkId: 251, parkName: "Herman Collier Park", features: "picnic",},
        {id: 870, parkId: 251, parkName: "Herman Collier Park", features: "horseshoes",},
        {id: 871, parkId: 252, parkName: "Letty Walter Park", features: "basketball",},
        {id: 872, parkId: 252, parkName: "Letty Walter Park", features: "football",},
        {id: 873, parkId: 252, parkName: "Letty Walter Park", features: "soccer",},
        {id: 874, parkId: 252, parkName: "Letty Walter Park", features: "picnic",},
        {id: 875, parkId: 252, parkName: "Letty Walter Park", features: "baseball",},
        {id: 876, parkId: 252, parkName: "Letty Walter Park", features: "tennis",},
        {id: 877, parkId: 252, parkName: "Letty Walter Park", features: "playground",},
        {id: 878, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "picnic",},
        {id: 879, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "basketball",},
        {id: 880, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "amphitheatre",},
        {id: 881, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "baseball",},
        {id: 882, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "playground",},
        {id: 883, parkId: 253, parkName: "Kevin Hammersmith Memorial Park", features: "walking",},
        {id: 884, parkId: 254, parkName: "Sam Peden Community Park", features: "fishing",},
        {id: 885, parkId: 254, parkName: "Sam Peden Community Park", features: "picnic",},
        {id: 886, parkId: 254, parkName: "Sam Peden Community Park", features: "walking",},
        {id: 887, parkId: 254, parkName: "Sam Peden Community Park", features: "horseshoes",},
        {id: 888, parkId: 254, parkName: "Sam Peden Community Park", features: "volleyball",},
        {id: 889, parkId: 254, parkName: "Sam Peden Community Park", features: "soccer",},
        {id: 890, parkId: 254, parkName: "Sam Peden Community Park", features: "tennis",},
        {id: 891, parkId: 254, parkName: "Sam Peden Community Park", features: "basketball",},
        {id: 892, parkId: 254, parkName: "Sam Peden Community Park", features: "restroom",},
        {id: 893, parkId: 254, parkName: "Sam Peden Community Park", features: "playground",},
        {id: 894, parkId: 255, parkName: "Southern IN Sports Center", features: "basketball",},
        {id: 895, parkId: 255, parkName: "Southern IN Sports Center", features: "volleyball",},
        {id: 896, parkId: 255, parkName: "Southern IN Sports Center", features: "exercise stations",},
        {id: 897, parkId: 255, parkName: "Southern IN Sports Center", features: "restroom",},
        {id: 898, parkId: 256, parkName: "Falls of the Ohio State Park", features: "education center",},
        {id: 899, parkId: 256, parkName: "Falls of the Ohio State Park", features: "fossils",},
        {id: 900, parkId: 256, parkName: "Falls of the Ohio State Park", features: "hiking",},
        {id: 901, parkId: 256, parkName: "Falls of the Ohio State Park", features: "fishing",},
        {id: 902, parkId: 256, parkName: "Falls of the Ohio State Park", features: "walking",},
        {id: 903, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "hiking",},
        {id: 904, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "picnic",},
        {id: 905, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "camping",},
        {id: 906, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "Rowboats",},
        {id: 907, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "fishing",},
        {id: 908, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "hunting",},
        {id: 909, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "beach",},
        {id: 910, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "swimming",},
        {id: 911, parkId: 257, parkName: "Deam Lake State Recreational Area", features: "education center",},
        {id: 912, parkId: 258, parkName: "Charlestown State Park", features: "hiking",},
        {id: 913, parkId: 258, parkName: "Charlestown State Park", features: "picnic",},
        {id: 914, parkId: 258, parkName: "Charlestown State Park", features: "fishing",},
        {id: 915, parkId: 258, parkName: "Charlestown State Park", features: "playground",},
        {id: 916, parkId: 258, parkName: "Charlestown State Park", features: "camping",},
        {id: 917, parkId: 259, parkName: "Clark State Forest", features: "camping",},
        {id: 918, parkId: 259, parkName: "Clark State Forest", features: "hunting",},
        {id: 919, parkId: 259, parkName: "Clark State Forest", features: "fishing",},
        {id: 920, parkId: 259, parkName: "Clark State Forest", features: "shooting range",},
        {id: 921, parkId: 259, parkName: "Clark State Forest", features: "playground",},
        {id: 922, parkId: 259, parkName: "Clark State Forest", features: "baseball",},
        {id: 923, parkId: 259, parkName: "Clark State Forest", features: "tennis",},
        {id: 924, parkId: 259, parkName: "Clark State Forest", features: "basketball",},
        {id: 925, parkId: 259, parkName: "Clark State Forest", features: "picnic",},
        {id: 926, parkId: 259, parkName: "Clark State Forest", features: "Firetower",},
        {id: 927, parkId: 260, parkName: "Harrison-Crawford State Forest", features: "camping",},
        {id: 928, parkId: 260, parkName: "Harrison-Crawford State Forest", features: "fishing",},
        {id: 929, parkId: 260, parkName: "Harrison-Crawford State Forest", features: "boat ramp",},
        {id: 930, parkId: 260, parkName: "Harrison-Crawford State Forest", features: "hunting",},
        {id: 931, parkId: 261, parkName: "O'Bannon Woods State Park", features: "caves",},
        {id: 932, parkId: 261, parkName: "O'Bannon Woods State Park", features: "pioneer farmstead",},
        {id: 933, parkId: 261, parkName: "O'Bannon Woods State Park", features: "swimming",},
        {id: 934, parkId: 261, parkName: "O'Bannon Woods State Park", features: "education center",},
        {id: 935, parkId: 261, parkName: "O'Bannon Woods State Park", features: "picnic",},
        {id: 936, parkId: 261, parkName: "O'Bannon Woods State Park", features: "horse Trails",},
        {id: 937, parkId: 261, parkName: "O'Bannon Woods State Park", features: "fishing",},
        {id: 938, parkId: 261, parkName: "O'Bannon Woods State Park", features: "boat ramp",},
        {id: 939, parkId: 261, parkName: "O'Bannon Woods State Park", features: "hiking",},
        {id: 940, parkId: 261, parkName: "O'Bannon Woods State Park", features: "mountain biking ",},
        {id: 941, parkId: 261, parkName: "O'Bannon Woods State Park", features: "camping",},
        {id: 942, parkId: 262, parkName: "Hayswood Nature Reserve", features: "hiking",},
        {id: 943, parkId: 262, parkName: "Hayswood Nature Reserve", features: "picnic",},
        {id: 944, parkId: 262, parkName: "Hayswood Nature Reserve", features: "restroom",},
        {id: 945, parkId: 262, parkName: "Hayswood Nature Reserve", features: "fishing",},
        {id: 946, parkId: 262, parkName: "Hayswood Nature Reserve", features: "walking",},
        {id: 947, parkId: 262, parkName: "Hayswood Nature Reserve", features: "playground",},
        {id: 948, parkId: 262, parkName: "Hayswood Nature Reserve", features: "horseshoes",},
        {id: 949, parkId: 262, parkName: "Hayswood Nature Reserve", features: "multiifield",},
        {id: 950, parkId: 263, parkName: "Rhoads Pool", features: "swimming",},
        {id: 951, parkId: 263, parkName: "Rhoads Pool", features: "basketball",},
        {id: 952, parkId: 263, parkName: "Rhoads Pool", features: "tennis",},
        {id: 953, parkId: 263, parkName: "Rhoads Pool", features: "volleyball",},
        {id: 954, parkId: 263, parkName: "Rhoads Pool", features: "playground",},
        {id: 955, parkId: 263, parkName: "Rhoads Pool", features: "picnic",},
        {id: 956, parkId: 264, parkName: "South Harrison", features: "camping",},
        {id: 957, parkId: 264, parkName: "South Harrison", features: "swimming",},
        {id: 958, parkId: 264, parkName: "South Harrison", features: "basketball",},
        {id: 959, parkId: 264, parkName: "South Harrison", features: "baseball",},
        {id: 960, parkId: 264, parkName: "South Harrison", features: "tennis",},
        {id: 961, parkId: 264, parkName: "South Harrison", features: "playground",},
        {id: 962, parkId: 264, parkName: "South Harrison", features: "walking",},
        {id: 963, parkId: 264, parkName: "South Harrison", features: "picnic",},
        {id: 964, parkId: 264, parkName: "South Harrison", features: "restroom",},
        {id: 965, parkId: 264, parkName: "South Harrison", features: "observatory",},
        {id: 966, parkId: 265, parkName: "Buffalo Trace", features: "camping",},
        {id: 967, parkId: 265, parkName: "Buffalo Trace", features: "Inn",},
        {id: 968, parkId: 265, parkName: "Buffalo Trace", features: "swimming",},
        {id: 969, parkId: 265, parkName: "Buffalo Trace", features: "fishing",},
        {id: 970, parkId: 265, parkName: "Buffalo Trace", features: "boat ramp",},
        {id: 971, parkId: 265, parkName: "Buffalo Trace", features: "basketball",},
        {id: 972, parkId: 265, parkName: "Buffalo Trace", features: "tennis",},
        {id: 973, parkId: 265, parkName: "Buffalo Trace", features: "baseball",},
        {id: 974, parkId: 265, parkName: "Buffalo Trace", features: "volleyball",},
        {id: 975, parkId: 265, parkName: "Buffalo Trace", features: "disc golf",},
        {id: 976, parkId: 265, parkName: "Buffalo Trace", features: "mountain biking ",},
        {id: 977, parkId: 265, parkName: "Buffalo Trace", features: "walking",},
        {id: 978, parkId: 265, parkName: "Buffalo Trace", features: "playground",},
        {id: 979, parkId: 265, parkName: "Buffalo Trace", features: "petting zoo",},
        {id: 980, parkId: 265, parkName: "Buffalo Trace", features: "picnic",},
        {id: 981, parkId: 265, parkName: "Buffalo Trace", features: "restroom",},
        {id: 982, parkId: 266, parkName: "Noe's", features: "basketball",},
        {id: 983, parkId: 266, parkName: "Noe's", features: "playground",},
        {id: 984, parkId: 266, parkName: "Noe's", features: "picnic",},
        {id: 985, parkId: 267, parkName: "Gresham", features: "playground",},
        {id: 986, parkId: 267, parkName: "Gresham", features: "picnic",},
        {id: 987, parkId: 268, parkName: "Battle of Corydon", features: "walking",},
        {id: 988, parkId: 269, parkName: "The Hubbard House", features: "log cabin",},
        {id: 989, parkId: 270, parkName: "Morvin's Landing", features: "historical",},
        {id: 990, parkId: 270, parkName: "Morvin's Landing", features: "boat ramp",},
        {id: 991, parkId: 270, parkName: "Morvin's Landing", features: "underground railroad site",},
        {id: 992, parkId: 271, parkName: "The Overlook Park", features: "picnic",},
        {id: 993, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "camping",},
        {id: 994, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "picnic",},
        {id: 995, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "canoeing",},
        {id: 996, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "fishing",},
        {id: 997, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "walking",},
        {id: 998, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "hiking",},
        {id: 999, parkId: 279, parkName: "Lake Shelby Park & Campground", features: "playground",},
        {id: 1000, parkId: 278, parkName: "Shelbyville Greenway", features: "biking",},
        {id: 1001, parkId: 278, parkName: "Shelbyville Greenway", features: "hiking",},
        {id: 1002, parkId: 278, parkName: "Shelbyville Greenway", features: "walking",},
        {id: 1003, parkId: 277, parkName: "Shelbyville skate Park", features: "skatepark",},
        {id: 1004, parkId: 276, parkName: "Finchville Park", features: "hiking",},
        {id: 1005, parkId: 276, parkName: "Finchville Park", features: "kite flying",},
        {id: 1006, parkId: 276, parkName: "Finchville Park", features: "picnic",},
        {id: 1007, parkId: 276, parkName: "Finchville Park", features: "walking",},
        {id: 1008, parkId: 276, parkName: "Finchville Park", features: "playground",},
        {id: 1009, parkId: 275, parkName: "Shelby Trails Park", features: "hiking",},
        {id: 1010, parkId: 275, parkName: "Shelby Trails Park", features: "horseback riding",},
        {id: 1011, parkId: 274, parkName: "Red Orchard Park", features: "playground",},
        {id: 1012, parkId: 274, parkName: "Red Orchard Park", features: "kite flying",},
        {id: 1013, parkId: 274, parkName: "Red Orchard Park", features: "horseback riding",},
        {id: 1014, parkId: 274, parkName: "Red Orchard Park", features: "hiking",},
        {id: 1015, parkId: 274, parkName: "Red Orchard Park", features: "walking",},
        {id: 1016, parkId: 274, parkName: "Red Orchard Park", features: "dog park",},
        {id: 1017, parkId: 273, parkName: "Clear Creek Park", features: "golf",},
        {id: 1018, parkId: 273, parkName: "Clear Creek Park", features: "camping",},
        {id: 1019, parkId: 273, parkName: "Clear Creek Park", features: "canoeing",},
        {id: 1020, parkId: 273, parkName: "Clear Creek Park", features: "Concerts",},
        {id: 1021, parkId: 273, parkName: "Clear Creek Park", features: "Fireworks",},
        {id: 1022, parkId: 273, parkName: "Clear Creek Park", features: "dog park",},
        {id: 1023, parkId: 273, parkName: "Clear Creek Park", features: "fishing",},
        {id: 1024, parkId: 273, parkName: "Clear Creek Park", features: "exercise stations",},
        {id: 1025, parkId: 273, parkName: "Clear Creek Park", features: "walking",},
        {id: 1026, parkId: 273, parkName: "Clear Creek Park", features: "hiking",},
        {id: 1027, parkId: 273, parkName: "Clear Creek Park", features: "horseback riding",},
        {id: 1028, parkId: 273, parkName: "Clear Creek Park", features: "kite flying",},
        {id: 1029, parkId: 280, parkName: "Battletown Park", features: "picnic",},
        {id: 1030, parkId: 280, parkName: "Battletown Park", features: "playground",},
        {id: 1031, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "playground",},
        {id: 1032, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "walking",},
        {id: 1033, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "soccer",},
        {id: 1034, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "amphitheatre",},
        {id: 1035, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "bandstand",},
        {id: 1036, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "picnic",},
        {id: 1037, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "chess",},
        {id: 1038, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "re-enactment",},
        {id: 1039, parkId: 281, parkName: "Brandenburg Riverfront Park", features: "christmas decorations",},
        {id: 1040, parkId: 156, parkName: "Brown Park", features: "christmas decorations",},
        {id: 1041, parkId: 97, parkName: "IROQUOIS", features: "halloween decorations",},
        {id: 1042, parkId: 97, parkName: "IROQUOIS", features: "christmas decorations",},
        {id: 1043, parkId: 282, parkName: "Buttermilk Falls Trail", features: "walking",},
        {id: 1044, parkId: 282, parkName: "Buttermilk Falls Trail", features: "hiking",},
        {id: 1045, parkId: 282, parkName: "Buttermilk Falls Trail", features: "biking",},
        {id: 1046, parkId: 282, parkName: "Buttermilk Falls Trail", features: "benches",},
        {id: 1047, parkId: 282, parkName: "Buttermilk Falls Trail", features: "picnic",},
        {id: 1048, parkId: 283, parkName: "Concordia Park", features: "boat ramp",},
        {id: 1049, parkId: 283, parkName: "Concordia Park", features: "picnic",},
        {id: 1050, parkId: 283, parkName: "Concordia Park", features: "camping",},
        {id: 1051, parkId: 284, parkName: "Dianna's Park", features: "playground",},
        {id: 1052, parkId: 285, parkName: "Flaherty Community Park", features: "baseball",},
        {id: 1053, parkId: 285, parkName: "Flaherty Community Park", features: "picnic",},
        {id: 1054, parkId: 286, parkName: "Meade-Olin Park", features: "baseball",},
        {id: 1055, parkId: 286, parkName: "Meade-Olin Park", features: "basketball",},
        {id: 1056, parkId: 286, parkName: "Meade-Olin Park", features: "soccer",},
        {id: 1057, parkId: 286, parkName: "Meade-Olin Park", features: "picnic",},
        {id: 1058, parkId: 286, parkName: "Meade-Olin Park", features: "restroom",},
        {id: 1059, parkId: 286, parkName: "Meade-Olin Park", features: "disc golf",},
        {id: 1060, parkId: 286, parkName: "Meade-Olin Park", features: "playground",},
        {id: 1061, parkId: 288, parkName: "Wolf Creek Park", features: "boat ramp",},
        {id: 1062, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "sculpture",},
        {id: 1063, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "playground",},
        {id: 1064, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "restroom",},
        {id: 1065, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "picnic",},
        {id: 1066, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "education center",},
        {id: 1067, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "walking",},
        {id: 1068, parkId: 290, parkName: "Bernheim Arboretum and Research Forest", features: "hiking",},
        {id: 1069, parkId: 5, parkName: "BEN WASHER", features: "picnic",},
        {id: 1070, parkId: 5, parkName: "BEN WASHER", features: "playground",},
        {id: 1071, parkId: 14, parkName: "CLIFF", features: "playground",},
        {id: 1072, parkId: 35, parkName: "CHARLES YOUNG", features: "playground",},
        {id: 1073, parkId: 37, parkName: "IROQUOIS golf course", features: "golf",},
        {id: 1074, parkId: 40, parkName: "SUN VALLEY golf course", features: "golf",},
        {id: 1075, parkId: 49, parkName: "LONG RUN cemetary", features: "cemetary",},
        {id: 1076, parkId: 53, parkName: "MEMORIAL", features: "bench",},
        {id: 1077, parkId: 68, parkName: "TWIN PARK", features: "open space",},
        {id: 1078, parkId: 71, parkName: "WAYSIDE", features: "bench",},
        {id: 1079, parkId: 85, parkName: "CRESCENT HILL golf course", features: "golf",},
        {id: 1080, parkId: 92, parkName: "LONG RUN golf course", features: "golf",},
        {id: 1081, parkId: 99, parkName: "CHEROKEE golf course", features: "golf",},
        {id: 1082, parkId: 108, parkName: "BOBBY NICHOLS golf course", features: "golf",},
        {id: 1083, parkId: 110, parkName: "CHURCHILL", features: "playground",},
        {id: 1084, parkId: 121, parkName: "EVA BANDMAN", features: "cyclocross course",},
        {id: 1085, parkId: 127, parkName: "CASTLEWOOD open space", features: "open space",},
        {id: 1086, parkId: 128, parkName: "CALIFORNIA open space", features: "open space",},
        {id: 1087, parkId: 130, parkName: "ROSE FARM", features: "bench",},
        {id: 1088, parkId: 133, parkName: "CLIFTON HEIGHTS GREENWAY", features: "walking",},
        {id: 1089, parkId: 134, parkName: "CYRILL ALLGEIER community center", features: "community center",},
        {id: 1090, parkId: 134, parkName: "CYRILL ALLGEIER community center", features: "baseball",},
        {id: 1091, parkId: 136, parkName: "PATRIOTS PEACE MEMORIAL", features: "Memorial",},
        {id: 1092, parkId: 137, parkName: "BUECHEL PARCEL", features: "natural area",},
        {id: 1093, parkId: 138, parkName: "MAHONEY", features: "future development",},
        {id: 1094, parkId: 139, parkName: "PETERSON", features: "natural area",},
        {id: 1095, parkId: 140, parkName: "JEFFERSON MEMORIAL PARCEL 22", features: "natural area",},
        {id: 1096, parkId: 141, parkName: "SOUTHERN PARKWAY", features: "olmsted",},
        {id: 1097, parkId: 142, parkName: "EASTERN PARKWAY", features: "olmsted",},
        {id: 1098, parkId: 143, parkName: "NORTHWESTERN PARKWAY", features: "olmsted",},
        {id: 1099, parkId: 144, parkName: "SOUTHWESTERN PARKWAY", features: "olmsted",},
        {id: 1100, parkId: 145, parkName: "ALGONQUIN PARKWAY", features: "olmsted",},
        {id: 1101, parkId: 152, parkName: "GALVIN COURT", features: "natural area",},
        {id: 1102, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "restroom",},
        {id: 1103, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "picnic",},
        {id: 1104, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "playground",},
        {id: 1105, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "baseball",},
        {id: 1106, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "basketball",},
        {id: 1107, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "walking",},
        {id: 1108, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "veteran memorial",},
        {id: 1109, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "helicopter",},
        {id: 1110, parkId: 162, parkName: "Jeffersontown Memorial Park", features: "tank",},
        {id: 1111, parkId: 163, parkName: "David L Armstrong Recreation Center", features: "restroom",},
        {id: 1112, parkId: 163, parkName: "David L Armstrong Recreation Center", features: "basketball",},
        {id: 1113, parkId: 164, parkName: "Skyview", features: "baseball",},
        {id: 1114, parkId: 164, parkName: "Skyview", features: "spraypad",},
        {id: 1115, parkId: 164, parkName: "Skyview", features: "walking",},
        {id: 1116, parkId: 164, parkName: "Skyview", features: "running",},
        {id: 1117, parkId: 164, parkName: "Skyview", features: "restroom",},
        {id: 1118, parkId: 164, parkName: "Skyview", features: "football",},
        {id: 1119, parkId: 165, parkName: "Plainview Swim Center", features: "swimming",},
        {id: 1120, parkId: 165, parkName: "Plainview Swim Center", features: "restrooms",},
        {id: 1121, parkId: 166, parkName: "Waterfront", features: "running",},
        {id: 1122, parkId: 166, parkName: "Waterfront", features: "walking",},
        {id: 1123, parkId: 166, parkName: "Waterfront", features: "playground",},
        {id: 1124, parkId: 166, parkName: "Waterfront", features: "sculpture",},
        {id: 1125, parkId: 166, parkName: "Waterfront", features: "multiifield",},
        {id: 1126, parkId: 166, parkName: "Waterfront", features: "picnic",},
        {id: 1127, parkId: 166, parkName: "Waterfront", features: "canoeing",},
        {id: 1128, parkId: 166, parkName: "Waterfront", features: "concert venue",},
        {id: 1129, parkId: 207, parkName: "Meadows Park", features: "natural area",},
        



        
        
]