const highlights = [
        {id: 1, parkid: 1, parkName: "35th street", features: "playground",},
        {id: 2, parkid: 2, parkName: "crescent hill", features: "swimming",},
        {id: 3, parkid: 1, parkName: "35th street", features: "basketball",},
        {id: 4, parkid: 2, parkName: "crescent hill", features: "picnic",},
        {id: 5, parkid: 2, parkName: "crescent hill", features: "playground",},
        {id: 6, parkid: 2, parkName: "crescent hill", features: "golf",},
        {id: 7, parkid: 2, parkName: "crescent hill", features: "tennis",},
        {id: 8, parkid: 2, parkName: "crescent hill", features: "sprayground",},
        {id: 9, parkid: 3, parkName: "algonquin", features: "sprayground",},
        {id: 10, parkid: 101, parkName: "baxter square", features: "sprayground",},
        {id: 11, parkid: 126, parkName: "beechmont tot lot", features: "sprayground",},
        {id: 12, parkid: 109, parkName: "breslin", features: "sprayground",},
        {id: 13, parkid: 39, parkName: "california leisure open space", features: "sprayground",},
        {id: 14, parkid: 86, parkName: "farnsley", features: "sprayground",},
        {id: 15, parkid: 54, parkName: "g. g. moore", features: "sprayground",},
        {id: 16, parkid: 97, parkName: "iroquois", features: "sprayground",},
        {id: 17, parkid: 41, parkName: "laporte", features: "sprayground",},
        {id: 18, parkid: 102, parkName: "long run", features: "sprayground",},
        {id: 19, parkid: 25, parkName: "nelson hornbeck", features: "sprayground",},
        {id: 20, parkid: 117, parkName: "petersburg", features: "sprayground",},
        {id: 21, parkid: 61, parkName: "riverview", features: "sprayground",},
        {id: 22, parkid: 65, parkName: "shelby", features: "sprayground",},
        {id: 23, parkid: 120, parkName: "wyandotte", features: "sprayground",},
        {id: 24, parkid: 6, parkName: "bingham", features: "spraypads",},
        {id: 25, parkid: 45, parkName: "boone square", features: "spraypads",},
        {id: 26, parkid: 12, parkName: "central", features: "spraypads",},
        {id: 27, parkid: 74, parkName: "cherokee", features: "spraypads",},
        {id: 28, parkid: 13, parkName: "chickasaw", features: "spraypads",},
        {id: 29, parkid: 42, parkName: "elliot square", features: "spraypads",},
        {id: 30, parkid: 54, parkName: "g. g. moore", features: "spraypads",},
        {id: 31, parkid: 58, parkName: "huston quin", features: "spraypads",},
        {id: 32, parkid: 55, parkName: "parkhill", features: "spraypads",},
        {id: 33, parkid: 80, parkName: "portland", features: "spraypads",},
        {id: 34, parkid: 160, parkName: "robsion park", features: "spraypads",},
        {id: 35, parkid: 48, parkName: "russell lee", features: "spraypads",},
        {id: 36, parkid: 69, parkName: "tyler", features: "spraypads",},
        {id: 37, parkid: 88, parkName: "victory", features: "spraypads",},
        {id: 38, parkid: 23, parkName: "william harrison", features: "spraypads",},
        {id: 39, parkid: 3, parkName: "algonquin", features: "swimming",},
        {id: 40, parkid: 9, parkName: "camp taylor", features: "swimming",},
        {id: 41, parkid: 2, parkName: "crescent hill", features: "swimming",},
        {id: 42, parkid: 25, parkName: "nelson hornbeck", features: "swimming",},
        {id: 43, parkid: 93, parkName: "sun valley", features: "swimming",},
        {id: 44, parkid: 135, parkName: "beckley creek park", features: "sprayground",},
        {id: 45, parkid: 135, parkName: "beckley creek park", features: "playground",},
        {id: 46, parkid: 148, parkName: "broad run", features: "sprayground",},
        {id: 47, parkid: 148, parkName: "broad run", features: "playground",},
        {id: 48, parkid: 124, parkName: "a. b. sawyer", features: "baseball",},
        {id: 49, parkid: 8, parkName: "buechel", features: "baseball",},
        {id: 50, parkid: 39, parkName: "california", features: "baseball",},
        {id: 51, parkid: 9, parkName: "camp taylor", features: "baseball",},
        {id: 52, parkid: 10, parkName: "cane run", features: "baseball",},
        {id: 53, parkid: 157, parkName: "community park", features: "baseball",},
        {id: 54, parkid: 42, parkName: "elliot square", features: "baseball",},
        {id: 55, parkid: 29, parkName: "hays kennedy", features: "baseball",},
        {id: 56, parkid: 26, parkName: "hounz lane", features: "baseball",},
        {id: 57, parkid: 31, parkName: "klondike", features: "baseball",},
        {id: 58, parkid: 25, parkName: "nelson hornbeck", features: "baseball",},
        {id: 59, parkid: 46, parkName: "old walnut / beecher", features: "baseball",},
        {id: 60, parkid: 117, parkName: "petersburg", features: "baseball",},
        {id: 61, parkid: 3, parkName: "algonquin", features: "basketball",},
        {id: 62, parkid: 104, parkName: "ballard", features: "basketball",},
        {id: 63, parkid: 101, parkName: "baxter square", features: "basketball",},
        {id: 64, parkid: 126, parkName: "beechmont tot lot", features: "basketball",},
        {id: 65, parkid: 105, parkName: "berrytown", features: "basketball",},
        {id: 66, parkid: 6, parkName: "bingham", features: "basketball",},
        {id: 67, parkid: 106, parkName: "black mudd", features: "basketball",},
        {id: 68, parkid: 8, parkName: "buechel", features: "basketball",},
        {id: 69, parkid: 9, parkName: "camp taylor", features: "basketball",},
        {id: 70, parkid: 96, parkName: "charlie vettiner", features: "basketball",},
        {id: 71, parkid: 74, parkName: "cherokee", features: "basketball",},
        {id: 72, parkid: 13, parkName: "chickasaw", features: "basketball",},
        {id: 73, parkid: 157, parkName: "community park", features: "basketball",},
        {id: 74, parkid: 90, parkName: "des pres", features: "basketball",},
        {id: 75, parkid: 17, parkName: "douglass", features: "basketball",},
        {id: 76, parkid: 76, parkName: "e. leland taylor", features: "basketball",},
        {id: 77, parkid: 112, parkName: "farman", features: "basketball",},
        {id: 78, parkid: 86, parkName: "farnsley", features: "basketball",},
        {id: 79, parkid: 54, parkName: "g. g. moore", features: "basketball",},
        {id: 80, parkid: 73, parkName: "george rogers clark", features: "basketball",},
        {id: 81, parkid: 59, parkName: "ginny reichard", features: "basketball",},
        {id: 82, parkid: 29, parkName: "hays kennedy", features: "basketball",},
        {id: 83, parkid: 82, parkName: "highview", features: "basketball",},
        {id: 84, parkid: 58, parkName: "huston quin", features: "basketball",},
        {id: 85, parkid: 27, parkName: "irish hill", features: "basketball",},
        {id: 86, parkid: 97, parkName: "iroquois", features: "basketball",},
        {id: 87, parkid: 33, parkName: "lake dreamland", features: "basketball",},
        {id: 88, parkid: 116, parkName: "lannan", features: "basketball",},
        {id: 89, parkid: 41, parkName: "laporte", features: "basketball",},
        {id: 90, parkid: 102, parkName: "long run", features: "basketball",},
        {id: 91, parkid: 44, parkName: "mcneely lake", features: "basketball",},
        {id: 92, parkid: 52, parkName: "medora", features: "basketball",},
        {id: 93, parkid: 25, parkName: "nelson hornbeck", features: "basketball",},
        {id: 94, parkid: 38, parkName: "norfolk acres", features: "basketball",},
        {id: 95, parkid: 84, parkName: "okolona", features: "basketball",},
        {id: 96, parkid: 55, parkName: "parkhill", features: "basketball",},
        {id: 97, parkid: 80, parkName: "portland", features: "basketball",},
        {id: 98, parkid: 60, parkName: "riverside gardens", features: "basketball",},
        {id: 99, parkid: 61, parkName: "riverview", features: "basketball",},
        {id: 100, parkid: 63, parkName: "rubel", features: "basketball",},
        {id: 101, parkid: 48, parkName: "russell lee", features: "basketball",},
        {id: 102, parkid: 98, parkName: "seneca", features: "basketball",},
        {id: 103, parkid: 64, parkName: "shawnee", features: "basketball",},
        {id: 104, parkid: 65, parkName: "shelby", features: "basketball",},
        {id: 105, parkid: 83, parkName: "sheppard", features: "basketball",},
        {id: 106, parkid: 118, parkName: "south central", features: "basketball",},
        {id: 107, parkid: 89, parkName: "st louis", features: "basketball",},
        {id: 108, parkid: 66, parkName: "story avenue", features: "basketball",},
        {id: 109, parkid: 93, parkName: "sun valley", features: "basketball",},
        {id: 110, parkid: 67, parkName: "sylvania", features: "basketball",},
        {id: 111, parkid: 69, parkName: "tyler", features: "basketball",},
        {id: 112, parkid: 88, parkName: "victory", features: "basketball",},
        {id: 113, parkid: 81, parkName: "westonia", features: "basketball",},
        {id: 114, parkid: 23, parkName: "william harrison", features: "basketball",},
        {id: 115, parkid: 120, parkName: "wyandotte", features: "basketball",},
        {id: 116, parkid: 75, parkName: "jefferson memorial forest", features: "camping",},
        {id: 117, parkid: 157, parkName: "community park", features: "conference",},
        {id: 118, parkid: 16, parkName: "carrie gaulbert cox", features: "fishing",},
        {id: 119, parkid: 96, parkName: "charlie vettiner", features: "fishing",},
        {id: 120, parkid: 74, parkName: "cherokee", features: "fishing",},
        {id: 121, parkid: 13, parkName: "chickasaw", features: "fishing",},
        {id: 122, parkid: 114, parkName: "fisherman's", features: "fishing",},
        {id: 123, parkid: 97, parkName: "iroquois", features: "fishing",},
        {id: 124, parkid: 75, parkName: "jefferson memorial forest", features: "fishing",},
        {id: 125, parkid: 102, parkName: "long run", features: "fishing",},
        {id: 126, parkid: 44, parkName: "mcneely lake", features: "fishing",},
        {id: 127, parkid: 100, parkName: "thurman hutchins", features: "fishing",},
        {id: 128, parkid: 95, parkName: "waverly", features: "fishing",},
        {id: 129, parkid: 70, parkName: "watterson lake", features: "fishing",},
        {id: 130, parkid: 94, parkName: "charlie vettiner golf course", features: "golf",},
        {id: 131, parkid: 2, parkName: "crescent hill golf course", features: "golf",},
        {id: 132, parkid: 154, parkName: "quail chase golf course ", features: "golf",},
        {id: 133, parkid: 34, parkName: "seneca golf course", features: "golf",},
        {id: 134, parkid: 77, parkName: "shawnee golf course", features: "golf",},
        {id: 135, parkid: 135, parkName: "beckley creek park", features: "hiking",},
        {id: 136, parkid: 146, parkName: "pope lick park", features: "hiking",},
        {id: 137, parkid: 147, parkName: "turkey run", features: "hiking",},
        {id: 138, parkid: 148, parkName: "broad run", features: "hiking",},
        {id: 139, parkid: 11, parkName: "caperton swap", features: "hiking",},
        {id: 140, parkid: 74, parkName: "cherokee", features: "hiking",},
        {id: 141, parkid: 111, parkName: "fairmont falls", features: "hiking",},
        {id: 142, parkid: 113, parkName: "fern creek", features: "hiking",},
        {id: 143, parkid: 97, parkName: "iroquois", features: "hiking",},
        {id: 144, parkid: 75, parkName: "jefferson memorial forest", features: "hiking",},
        {id: 145, parkid: 115, parkName: "joe creason", features: "hiking",},
        {id: 146, parkid: 44, parkName: "mcneely lake", features: "hiking",},
        {id: 147, parkid: 95, parkName: "waverly", features: "hiking",},
        {id: 148, parkid: 97, parkName: "iroquois", features: "horseback",},
        {id: 149, parkid: 75, parkName: "jefferson memorial forest", features: "horseback",},
        {id: 150, parkid: 102, parkName: "long run", features: "horseback",},
        {id: 151, parkid: 44, parkName: "mcneely lake", features: "horseback",},
        {id: 152, parkid: 98, parkName: "seneca", features: "horseback",},
        {id: 153, parkid: 146, parkName: "pope lick park", features: "multiifield",},
        {id: 154, parkid: 135, parkName: "beckley creek park", features: "multiifield",},
        {id: 155, parkid: 148, parkName: "broad run", features: "multiifield",},
        {id: 156, parkid: 124, parkName: "a.b. sawyer", features: "multiifield",},
        {id: 157, parkid: 3, parkName: "algonquin", features: "multiifield",},
        {id: 158, parkid: 109, parkName: "breslin", features: "multiifield",},
        {id: 159, parkid: 39, parkName: "california", features: "multiifield",},
        {id: 160, parkid: 10, parkName: "cane run", features: "multiifield",},
        {id: 161, parkid: 74, parkName: "cherokee", features: "multiifield",},
        {id: 162, parkid: 76, parkName: "e. leland taylor", features: "multiifield",},
        {id: 163, parkid: 86, parkName: "farnsley", features: "multiifield",},
        {id: 164, parkid: 113, parkName: "fern creek", features: "multiifield",},
        {id: 165, parkid: 20, parkName: "flaget field", features: "multiifield",},
        {id: 166, parkid: 73, parkName: "george rogers clark", features: "multiifield",},
        {id: 167, parkid: 29, parkName: "hays kennedy", features: "multiifield",},
        {id: 168, parkid: 26, parkName: "hounz lane", features: "multiifield",},
        {id: 169, parkid: 115, parkName: "joe creason", features: "multiifield",},
        {id: 170, parkid: 116, parkName: "lannan", features: "multiifield",},
        {id: 171, parkid: 102, parkName: "long run", features: "multiifield",},
        {id: 172, parkid: 151, parkName: "louisville champions", features: "multiifield",},
        {id: 173, parkid: 44, parkName: "mcneely lake", features: "multiifield",},
        {id: 174, parkid: 38, parkName: "norfolk acres", features: "multiifield",},
        {id: 175, parkid: 84, parkName: "okolona", features: "multiifield",},
        {id: 176, parkid: 46, parkName: "old walnut / beecher", features: "multiifield",},
        {id: 177, parkid: 117, parkName: "petersburg", features: "multiifield",},
        {id: 178, parkid: 48, parkName: "russell lee", features: "multiifield",},
        {id: 179, parkid: 98, parkName: "seneca", features: "multiifield",},
        {id: 180, parkid: 64, parkName: "shawnee", features: "multiifield",},
        {id: 181, parkid: 83, parkName: "sheppard", features: "multiifield",},
        {id: 182, parkid: 118, parkName: "south central", features: "multiifield",},
        {id: 183, parkid: 66, parkName: "story avenue", features: "multiifield",},
        {id: 184, parkid: 93, parkName: "sun valley", features: "multiifield",},
        {id: 185, parkid: 100, parkName: "thurman hutchins", features: "multiifield",},
        {id: 186, parkid: 119, parkName: "toonerville trolley", features: "multiifield",},
        {id: 187, parkid: 135, parkName: "beckley creek park", features: "picnic",},
        {id: 188, parkid: 146, parkName: "pope lick park", features: "picnic",},
        {id: 189, parkid: 147, parkName: "turkey run", features: "picnic",},
        {id: 190, parkid: 148, parkName: "broad run", features: "picnic",},
        {id: 191, parkid: 160, parkName: "robsion park", features: "picnic",},
        {id: 192, parkid: 159, parkName: "hal warheim", features: "picnic",},
        {id: 193, parkid: 158, parkName: "warwick park", features: "picnic",},
        {id: 194, parkid: 157, parkName: "community park", features: "picnic",},
        {id: 195, parkid: 155, parkName: "arthur k. draut park", features: "picnic",},
        {id: 196, parkid: 156, parkName: "brown park", features: "picnic",},
        {id: 197, parkid: 6, parkName: "bingham", features: "picnic",},
        {id: 198, parkid: 106, parkName: "black mudd", features: "picnic",},
        {id: 199, parkid: 107, parkName: "blue lick", features: "picnic",},
        {id: 200, parkid: 45, parkName: "boone square", features: "picnic",},
        {id: 201, parkid: 7, parkName: "bradley", features: "picnic",},
        {id: 202, parkid: 109, parkName: "breslin", features: "picnic",},
        {id: 203, parkid: 8, parkName: "buechel", features: "picnic",},
        {id: 204, parkid: 9, parkName: "camp taylor", features: "picnic",},
        {id: 205, parkid: 16, parkName: "carrie gaulbert cox", features: "picnic",},
        {id: 206, parkid: 12, parkName: "central", features: "picnic",},
        {id: 207, parkid: 96, parkName: "charlie vettiner", features: "picnic",},
        {id: 208, parkid: 74, parkName: "cherokee", features: "picnic",},
        {id: 209, parkid: 13, parkName: "chickasaw", features: "picnic",},
        {id: 210, parkid: 15, parkName: "clifton", features: "picnic",},
        {id: 211, parkid: 87, parkName: "crosby", features: "picnic",},
        {id: 212, parkid: 90, parkName: "des pres", features: "picnic",},
        {id: 213, parkid: 17, parkName: "douglass", features: "picnic",},
        {id: 214, parkid: 76, parkName: "e. leland taylor", features: "picnic",},
        {id: 215, parkid: 42, parkName: "elliot square", features: "picnic",},
        {id: 216, parkid: 43, parkName: "emerson", features: "picnic",},
        {id: 217, parkid: 19, parkName: "fairdale mini", features: "picnic",},
        {id: 218, parkid: 112, parkName: "farman", features: "picnic",},
        {id: 219, parkid: 86, parkName: "farnsley", features: "picnic",},
        {id: 220, parkid: 113, parkName: "fern creek", features: "picnic",},
        {id: 221, parkid: 114, parkName: "fisherman's", features: "picnic",},
        {id: 222, parkid: 54, parkName: "g. g. moore", features: "picnic",},
        {id: 223, parkid: 73, parkName: "george rogers clark", features: "picnic",},
        {id: 224, parkid: 29, parkName: "hays kennedy", features: "picnic",},
        {id: 225, parkid: 82, parkName: "highview", features: "picnic",},
        {id: 226, parkid: 26, parkName: "hounz lane", features: "picnic",},
        {id: 227, parkid: 58, parkName: "huston quin", features: "picnic",},
        {id: 228, parkid: 97, parkName: "iroquois", features: "picnic",},
        {id: 229, parkid: 75, parkName: "jefferson memorial forest", features: "picnic",},
        {id: 230, parkid: 115, parkName: "joe creason", features: "picnic",},
        {id: 231, parkid: 30, parkName: "kennedy court", features: "picnic",},
        {id: 232, parkid: 31, parkName: "klondike", features: "picnic",},
        {id: 233, parkid: 32, parkName: "kulmer reserve", features: "picnic",},
        {id: 234, parkid: 33, parkName: "lake dreamland", features: "picnic",},
        {id: 235, parkid: 116, parkName: "lannan", features: "picnic",},
        {id: 236, parkid: 102, parkName: "long run", features: "picnic",},
        {id: 237, parkid: 51, parkName: "magnolia", features: "picnic",},
        {id: 238, parkid: 44, parkName: "mcneely lake", features: "picnic",},
        {id: 239, parkid: 38, parkName: "norfolk acres", features: "picnic",},
        {id: 240, parkid: 84, parkName: "okolona", features: "picnic",},
        {id: 241, parkid: 55, parkName: "parkhill", features: "picnic",},
        {id: 242, parkid: 57, parkName: "peewee", features: "picnic",},
        {id: 243, parkid: 117, parkName: "petersburg", features: "picnic",},
        {id: 244, parkid: 80, parkName: "portland", features: "picnic",},
        {id: 245, parkid: 60, parkName: "riverside gardens", features: "picnic",},
        {id: 246, parkid: 61, parkName: "riverview", features: "picnic",},
        {id: 247, parkid: 63, parkName: "rubel", features: "picnic",},
        {id: 248, parkid: 48, parkName: "russell lee", features: "picnic",},
        {id: 249, parkid: 98, parkName: "seneca", features: "picnic",},
        {id: 250, parkid: 64, parkName: "shawnee", features: "picnic",},
        {id: 251, parkid: 65, parkName: "shelby", features: "picnic",},
        {id: 252, parkid: 83, parkName: "sheppard", features: "picnic",},
        {id: 253, parkid: 118, parkName: "south central", features: "picnic",},
        {id: 254, parkid: 93, parkName: "sun valley", features: "picnic",},
        {id: 255, parkid: 67, parkName: "sylvania", features: "picnic",},
        {id: 256, parkid: 100, parkName: "thurman hutchins", features: "picnic",},
        {id: 257, parkid: 69, parkName: "tyler", features: "picnic",},
        {id: 258, parkid: 88, parkName: "victory", features: "picnic",},
        {id: 259, parkid: 70, parkName: "watterson lake", features: "picnic",},
        {id: 260, parkid: 95, parkName: "waverly", features: "picnic",},
        {id: 261, parkid: 23, parkName: "william harrison", features: "picnic",},
        {id: 262, parkid: 72, parkName: "willow", features: "picnic",},
        {id: 263, parkid: 120, parkName: "wyandotte", features: "picnic",},
        {id: 264, parkid: 3, parkName: "algonquin", features: "volleyball",},
        {id: 265, parkid: 39, parkName: "california", features: "volleyball",},
        {id: 266, parkid: 12, parkName: "central", features: "volleyball",},
        {id: 267, parkid: 96, parkName: "charlie vettiner", features: "volleyball",},
        {id: 268, parkid: 13, parkName: "chickasaw", features: "volleyball",},
        {id: 269, parkid: 90, parkName: "des pres", features: "volleyball",},
        {id: 270, parkid: 73, parkName: "george rogers clark", features: "volleyball",},
        {id: 271, parkid: 97, parkName: "iroquois", features: "volleyball",},
        {id: 272, parkid: 115, parkName: "joe creason", features: "volleyball",},
        {id: 273, parkid: 116, parkName: "lannan", features: "volleyball",},
        {id: 274, parkid: 102, parkName: "long run", features: "volleyball",},
        {id: 275, parkid: 46, parkName: "old walnut / beecher", features: "volleyball",},
        {id: 276, parkid: 80, parkName: "portland", features: "volleyball",},
        {id: 277, parkid: 98, parkName: "seneca", features: "volleyball",},
        {id: 278, parkid: 93, parkName: "sun valley", features: "volleyball",},
        {id: 279, parkid: 69, parkName: "tyler", features: "volleyball",},
        {id: 280, parkid: 81, parkName: "westonia", features: "volleyball",},
        {id: 281, parkid: 120, parkName: "wyandotte", features: "volleyball",},
        {id: 282, parkid: 109, parkName: "breslin", features: "skatepark",},
        {id: 283, parkid: 50, parkName: "david armstroNg eXtreme ", features: "skatepark",},
        {id: 284, parkid: 124, parkName: "a.b. sawyer", features: "tennis",},
        {id: 285, parkid: 3, parkName: "algonquin", features: "tennis",},
        {id: 286, parkid: 103, parkName: "auburndale", features: "tennis",},
        {id: 287, parkid: 101, parkName: "baxter square", features: "tennis",},
        {id: 288, parkid: 105, parkName: "berrytown", features: "tennis",},
        {id: 289, parkid: 106, parkName: "black mudd", features: "tennis",},
        {id: 290, parkid: 107, parkName: "blue lick", features: "tennis",},
        {id: 291, parkid: 8, parkName: "buechel", features: "tennis",},
        {id: 292, parkid: 39, parkName: "california", features: "tennis",},
        {id: 293, parkid: 12, parkName: "central", features: "tennis",},
        {id: 294, parkid: 96, parkName: "charlie vettiner", features: "tennis",},
        {id: 295, parkid: 74, parkName: "cherokee", features: "tennis",},
        {id: 296, parkid: 13, parkName: "chickasaw", features: "tennis",},
        {id: 297, parkid: 15, parkName: "clifton", features: "tennis",},
        {id: 298, parkid: 87, parkName: "crosby", features: "tennis",},
        {id: 299, parkid: 90, parkName: "des pres", features: "tennis",},
        {id: 300, parkid: 86, parkName: "farnsley", features: "tennis",},
        {id: 301, parkid: 113, parkName: "fern creek", features: "tennis",},
        {id: 302, parkid: 73, parkName: "george rogers clark", features: "tennis",},
        {id: 303, parkid: 29, parkName: "hays kennedy", features: "tennis",},
        {id: 304, parkid: 82, parkName: "highview", features: "tennis",},
        {id: 305, parkid: 26, parkName: "hounz lane", features: "tennis",},
        {id: 306, parkid: 97, parkName: "iroquois", features: "tennis",},
        {id: 307, parkid: 115, parkName: "joe creason", features: "tennis",},
        {id: 308, parkid: 31, parkName: "klondike", features: "tennis",},
        {id: 309, parkid: 116, parkName: "lannan", features: "tennis",},
        {id: 310, parkid: 102, parkName: "long run", features: "tennis",},
        {id: 311, parkid: 44, parkName: "mcneely lake", features: "tennis",},
        {id: 312, parkid: 25, parkName: "nelson hornbeck", features: "tennis",},
        {id: 313, parkid: 84, parkName: "okolona", features: "tennis",},
        {id: 314, parkid: 46, parkName: "old walnut / beecher", features: "tennis",},
        {id: 315, parkid: 117, parkName: "petersburg", features: "tennis",},
        {id: 316, parkid: 48, parkName: "russell lee", features: "tennis",},
        {id: 317, parkid: 98, parkName: "seneca", features: "tennis",},
        {id: 318, parkid: 64, parkName: "shawnee", features: "tennis",},
        {id: 319, parkid: 65, parkName: "shelby", features: "tennis",},
        {id: 320, parkid: 93, parkName: "sun valley", features: "tennis",},
        {id: 321, parkid: 67, parkName: "sylvania", features: "tennis",},
        {id: 322, parkid: 119, parkName: "toonerville trolley", features: "tennis",},
        {id: 323, parkid: 69, parkName: "tyler", features: "tennis",},
        {id: 324, parkid: 95, parkName: "waverly", features: "tennis",},
        {id: 325, parkid: 120, parkName: "wyandotte", features: "tennis",},
        {id: 326, parkid: 124, parkName: "a.b. sawyer", features: "restroom",},
        {id: 327, parkid: 3, parkName: "algonquin", features: "restroom",},
        {id: 328, parkid: 135, parkName: "beckley creek park", features: "restroom",},
        {id: 329, parkid: 105, parkName: "berrytown", features: "restroom",},
        {id: 330, parkid: 6, parkName: "bingham", features: "restroom",},
        {id: 331, parkid: 45, parkName: "boone square", features: "restroom",},
        {id: 332, parkid: 109, parkName: "breslin", features: "restroom",},
        {id: 333, parkid: 156, parkName: "brown park", features: "restroom",},
        {id: 334, parkid: 9, parkName: "camp taylor", features: "restroom",},
        {id: 335, parkid: 16, parkName: "carrie gaulbert cox", features: "restroom",},
        {id: 336, parkid: 12, parkName: "central", features: "restroom",},
        {id: 337, parkid: 96, parkName: "charlie vettiner", features: "restroom",},
        {id: 338, parkid: 74, parkName: "cherokee", features: "restroom",},
        {id: 339, parkid: 13, parkName: "chickasaw", features: "restroom",},
        {id: 340, parkid: 157, parkName: "community park", features: "restroom",},
        {id: 341, parkid: 87, parkName: "crosby", features: "restroom",},
        {id: 342, parkid: 50, parkName: "david armstroNg eXtreme ", features: "restroom",},
        {id: 343, parkid: 90, parkName: "des pres", features: "restroom",},
        {id: 344, parkid: 42, parkName: "elliot square", features: "restroom",},
        {id: 345, parkid: 86, parkName: "farnsley", features: "restroom",},
        {id: 346, parkid: 113, parkName: "fern creek", features: "restroom",},
        {id: 347, parkid: 20, parkName: "flaget field", features: "restroom",},
        {id: 348, parkid: 73, parkName: "george rogers clark", features: "restroom",},
        {id: 349, parkid: 29, parkName: "hays kennedy", features: "restroom",},
        {id: 350, parkid: 97, parkName: "iroquois", features: "restroom",},
        {id: 351, parkid: 75, parkName: "jefferson memorial forest", features: "restroom",},
        {id: 352, parkid: 115, parkName: "joe creason", features: "restroom",},
        {id: 353, parkid: 116, parkName: "lannan", features: "restroom",},
        {id: 354, parkid: 125, parkName: "locust grove", features: "restroom",},
        {id: 355, parkid: 102, parkName: "long run", features: "restroom",},
        {id: 356, parkid: 150, parkName: "louisville champions soccer", features: "restroom",},
        {id: 357, parkid: 44, parkName: "mcneely lake", features: "restroom",},
        {id: 358, parkid: 25, parkName: "nelson hornbeck", features: "restroom",},
        {id: 359, parkid: 84, parkName: "okolona", features: "restroom",},
        {id: 360, parkid: 117, parkName: "petersburg", features: "restroom",},
        {id: 361, parkid: 80, parkName: "portland", features: "restroom",},
        {id: 362, parkid: 154, parkName: "quail chase golf course ", features: "restroom",},
        {id: 363, parkid: 60, parkName: "riverside gardens", features: "restroom",},
        {id: 364, parkid: 62, parkName: "riverside, the farnsley-moremaN laNdiNg", features: "restroom",},
        {id: 365, parkid: 61, parkName: "riverview", features: "restroom",},
        {id: 366, parkid: 160, parkName: "robsion park", features: "restroom",},
        {id: 367, parkid: 48, parkName: "russell lee", features: "restroom",},
        {id: 368, parkid: 98, parkName: "seneca", features: "restroom",},
        {id: 369, parkid: 64, parkName: "shawnee", features: "restroom",},
        {id: 370, parkid: 65, parkName: "shelby", features: "restroom",},
        {id: 371, parkid: 93, parkName: "sun valley", features: "restroom",},
        {id: 372, parkid: 100, parkName: "thurman hutchins", features: "restroom",},
        {id: 373, parkid: 69, parkName: "tyler", features: "restroom",},
        {id: 374, parkid: 88, parkName: "victory", features: "restroom",},
        {id: 375, parkid: 158, parkName: "warwick park", features: "restroom",},
        {id: 376, parkid: 81, parkName: "westonia", features: "restroom",},
        {id: 377, parkid: 72, parkName: "willow", features: "restroom",},
        {id: 378, parkid: 120, parkName: "wyandotte", features: "restroom",},
        {id: 379, parkid: 157, parkName: "community park", features: "playground",},
        {id: 380, parkid: 87, parkName: "crosby", features: "playground",},
        {id: 381, parkid: 90, parkName: "des pres", features: "playground",},
        {id: 382, parkid: 17, parkName: "douglass", features: "playground",},
        {id: 383, parkid: 76, parkName: "e. leland taylor", features: "playground",},
        {id: 384, parkid: 18, parkName: "eastover", features: "playground",},
        {id: 385, parkid: 42, parkName: "elliot square", features: "playground",},
        {id: 386, parkid: 43, parkName: "emerson", features: "playground",},
        {id: 387, parkid: 112, parkName: "farman", features: "playground",},
        {id: 388, parkid: 86, parkName: "farnsley", features: "playground",},
        {id: 389, parkid: 114, parkName: "fern creek", features: "playground",},
        {id: 390, parkid: 20, parkName: "flaget field", features: "playground",},
        {id: 391, parkid: 73, parkName: "george rogers clark", features: "playground",},
        {id: 392, parkid: 21, parkName: "german-paristown", features: "playground",},
        {id: 393, parkid: 59, parkName: "ginny reichard", features: "playground",},
        {id: 394, parkid: 159, parkName: "hal warheim", features: "playground",},
        {id: 395, parkid: 29, parkName: "hays kennedy", features: "playground",},
        {id: 396, parkid: 82, parkName: "highview", features: "playground",},
        {id: 397, parkid: 24, parkName: "hopewell", features: "playground",},
        {id: 398, parkid: 26, parkName: "hounz lane", features: "playground",},
        {id: 399, parkid: 58, parkName: "huston quin", features: "playground",},
        {id: 400, parkid: 97, parkName: "iroquois", features: "playground",},
        {id: 401, parkid: 91, parkName: "ivy court", features: "playground",},
        {id: 402, parkid: 75, parkName: "jefferson memorial forest", features: "playground",},
        {id: 403, parkid: 115, parkName: "joe creason", features: "playground",},
        {id: 404, parkid: 30, parkName: "kennedy court", features: "playground",},
        {id: 405, parkid: 31, parkName: "klondike", features: "playground",},
        {id: 406, parkid: 33, parkName: "lake dreamland", features: "playground",},
        {id: 407, parkid: 116, parkName: "lannan", features: "playground",},
        {id: 408, parkid: 41, parkName: "laporte", features: "playground",},
        {id: 409, parkid: 102, parkName: "long run", features: "playground",},
        {id: 410, parkid: 28, parkName: "louis b. israel", features: "playground",},
        {id: 411, parkid: 51, parkName: "magnolia", features: "playground",},
        {id: 412, parkid: 44, parkName: "mcneely lake", features: "playground",},
        {id: 413, parkid: 52, parkName: "medora", features: "playground",},
        {id: 414, parkid: 25, parkName: "nelson hornbeck", features: "playground",},
        {id: 415, parkid: 38, parkName: "norfolk acres", features: "playground",},
        {id: 416, parkid: 84, parkName: "okolona", features: "playground",},
        {id: 417, parkid: 46, parkName: "old walnut / beecher", features: "playground",},
        {id: 418, parkid: 55, parkName: "parkhill", features: "playground",},
        {id: 419, parkid: 129, parkName: "parklaNd playground", features: "playground",},
        {id: 420, parkid: 56, parkName: "patterson", features: "playground",},
        {id: 421, parkid: 57, parkName: "peewee", features: "playground",},
        {id: 422, parkid: 117, parkName: "petersburg", features: "playground",},
        {id: 423, parkid: 80, parkName: "portland", features: "playground",},
        {id: 424, parkid: 60, parkName: "riverside gardens", features: "playground",},
        {id: 425, parkid: 61, parkName: "riverview", features: "playground",},
        {id: 426, parkid: 160, parkName: "robsion park", features: "playground",},
        {id: 427, parkid: 63, parkName: "rubel", features: "playground",},
        {id: 428, parkid: 48, parkName: "russell lee", features: "playground",},
        {id: 429, parkid: 98, parkName: "seneca", features: "playground",},
        {id: 430, parkid: 64, parkName: "shawnee", features: "playground",},
        {id: 431, parkid: 65, parkName: "shelby", features: "playground",},
        {id: 432, parkid: 83, parkName: "sheppard", features: "playground",},
        {id: 433, parkid: 47, parkName: "slevin", features: "playground",},
        {id: 434, parkid: 118, parkName: "south central", features: "playground",},
        {id: 435, parkid: 89, parkName: "st louis", features: "playground",},
        {id: 436, parkid: 66, parkName: "story avenue", features: "playground",},
        {id: 437, parkid: 93, parkName: "sun valley", features: "playground",},
        {id: 438, parkid: 67, parkName: "sylvania", features: "playground",},
        {id: 439, parkid: 100, parkName: "thurman hutchins", features: "playground",},
        {id: 440, parkid: 119, parkName: "toonerville trolley", features: "playground",},
        {id: 441, parkid: 69, parkName: "tyler", features: "playground",},
        {id: 442, parkid: 88, parkName: "victory", features: "playground",},
        {id: 443, parkid: 158, parkName: "warwick park", features: "playground",},
        {id: 444, parkid: 95, parkName: "waverly", features: "playground",},
        {id: 445, parkid: 81, parkName: "westonia", features: "playground",},
        {id: 446, parkid: 23, parkName: "william harrison", features: "playground",},
        {id: 447, parkid: 72, parkName: "willow", features: "playground",},
        {id: 448, parkid: 120, parkName: "wyandotte", features: "playground",},
        {id: 449, parkid: 150, parkName: "louisville champions soccer", features: "soccer",},
        {id: 450, parkid: 44, parkName: "mcneely lake", features: "soccer",},
        {id: 451, parkid: 160, parkName: "robsion park", features: "soccer",},
        {id: 452, parkid: 64, parkName: "shawnee", features: "soccer",},
        {id: 453, parkid: 93, parkName: "sun valley", features: "soccer",},
        {id: 454, parkid: 146, parkName: "pope lick park", features: "soccer",},
        {id: 455, parkid: 149, parkName: "a.b. sawyer greenway", features: "walking",},
        {id: 456, parkid: 3, parkName: "algonquin", features: "walking",},
        {id: 457, parkid: 122, parkName: "beargrass creek greenway at irish hill", features: "walking",},
        {id: 458, parkid: 135, parkName: "beckley creek park", features: "walking",},
        {id: 459, parkid: 4, parkName: "bellevue", features: "walking",},
        {id: 460, parkid: 107, parkName: "blue lick", features: "walking",},
        {id: 461, parkid: 109, parkName: "breslin", features: "walking",},
        {id: 462, parkid: 8, parkName: "buechel", features: "walking",},
        {id: 463, parkid: 9, parkName: "camp taylor", features: "walking",},
        {id: 464, parkid: 10, parkName: "cane run", features: "walking",},
        {id: 465, parkid: 16, parkName: "carrie gaulbert cox", features: "walking",},
        {id: 466, parkid: 12, parkName: "central", features: "walking",},
        {id: 467, parkid: 96, parkName: "charlie vettiner", features: "walking",},
        {id: 468, parkid: 74, parkName: "cherokee", features: "walking",},
        {id: 469, parkid: 13, parkName: "chickasaw", features: "walking",},
        {id: 470, parkid: 157, parkName: "community park", features: "walking",},
        {id: 471, parkid: 43, parkName: "emerson", features: "walking",},
        {id: 472, parkid: 19, parkName: "fairdale mini", features: "walking",},
        {id: 473, parkid: 113, parkName: "fern creek", features: "walking",},
        {id: 474, parkid: 114, parkName: "fisherman's", features: "walking",},
        {id: 475, parkid: 20, parkName: "flaget field", features: "walking",},
        {id: 476, parkid: 159, parkName: "hal warheim", features: "walking",},
        {id: 477, parkid: 29, parkName: "hays kennedy", features: "walking",},
        {id: 478, parkid: 82, parkName: "highview", features: "walking",},
        {id: 479, parkid: 97, parkName: "iroquois", features: "walking",},
        {id: 480, parkid: 75, parkName: "jefferson memorial forest", features: "walking",},
        {id: 481, parkid: 115, parkName: "joe creason", features: "walking",},
        {id: 482, parkid: 30, parkName: "kennedy court", features: "walking",},
        {id: 483, parkid: 31, parkName: "klondike", features: "walking",},
        {id: 484, parkid: 32, parkName: "kulmer reserve", features: "walking",},
        {id: 485, parkid: 116, parkName: "lannan", features: "walking",},
        {id: 486, parkid: 102, parkName: "long run", features: "walking",},
        {id: 487, parkid: 44, parkName: "mcneely lake", features: "walking",},
        {id: 488, parkid: 38, parkName: "norfolk acres", features: "walking",},
        {id: 489, parkid: 136, parkName: "patriots peace memorial", features: "walking",},
        {id: 490, parkid: 79, parkName: "portland wharf", features: "walking",},
        {id: 491, parkid: 36, parkName: "roberson run", features: "walking",},
        {id: 492, parkid: 160, parkName: "robsion park", features: "walking",},
        {id: 493, parkid: 132, parkName: "schuff lane greenway", features: "walking",},
        {id: 494, parkid: 98, parkName: "seneca", features: "walking",},
        {id: 495, parkid: 64, parkName: "shawnee", features: "walking",},
        {id: 496, parkid: 65, parkName: "shelby", features: "walking",},
        {id: 497, parkid: 83, parkName: "sheppard", features: "walking",},
        {id: 498, parkid: 118, parkName: "south central", features: "walking",},
        {id: 499, parkid: 100, parkName: "thurman hutchins", features: "walking",},
        {id: 500, parkid: 69, parkName: "tyler", features: "walking",},
        {id: 501, parkid: 88, parkName: "victory", features: "walking",},
        {id: 502, parkid: 131, parkName: "watson lane trailhead", features: "walking",},
        {id: 503, parkid: 70, parkName: "watterson lake", features: "walking",},
        {id: 504, parkid: 78, parkName: "william britt", features: "walking",},
        {id: 505, parkid: 72, parkName: "willow", features: "walking",},
        {id: 506, parkid: 120, parkName: "wyandotte", features: "walking",},
        {id: 507, parkid: 153, parkName: "the strand", features: "walking",},
        {id: 508, parkid: 153, parkName: "the strand", features: "picnic",},
        {id: 509, parkid: 147, parkName: "turkey run", features: "fishing",},
        {id: 510, parkid: 153, parkName: "the strand", features: "restroom",},
        {id: 511, parkid: 161, parkName: "auburn park", features: "picnic",},
        {id: 512, parkid: 162, parkName: "auburn park", features: "playground",},
        {id: 513, parkid: 87, parkName: "crosby", features: "little library",},
        {id: 514, parkid: 43, parkName: "emerson", features: "little library",},
        {id: 515, parkid: 159, parkName: "hal warheim", features: "little library",},
        {id: 516, parkid: 160, parkName: "robsion park", features: "little library",},
        {id: 517, parkid: 123, parkName: "william b. stansbury", features: "basketball",},
        {id: 518, parkid: 123, parkName: "william b. stansbury", features: "multiifield",},
        {id: 519, parkid: 123, parkName: "william b. stansbury", features: "playground",},
        {id: 520, parkid: 123, parkName: "william b. stansbury", features: "sprayground",},
        {id: 521, parkid: 123, parkName: "william b. stansbury", features: "restroom",},
        {id: 522, parkid: 123, parkName: "william b. stansbury", features: "tennis",},
        {id: 523, parkid: 59, parkName: "ginny reichard", features: "no swings",},
        {id: 524, parkid: 22, parkName: "gnadinger", features: "benches",},
        {id: 525, parkid: 167, parkName: "mount washington community park", features: "little library",},
        {id: 526, parkid: 167, parkName: "mount washington community park", features: "walking",},
        {id: 527, parkid: 167, parkName: "mount washington community park", features: "tennis",},
        {id: 528, parkid: 167, parkName: "mount washington community park", features: "basketball",},
        {id: 529, parkid: 167, parkName: "mount washington community park", features: "volleyball",},
        {id: 530, parkid: 167, parkName: "mount washington community park", features: "soccer",},
        {id: 531, parkid: 167, parkName: "mount washington community park", features: "baseball",},
        {id: 532, parkid: 167, parkName: "mount washington community park", features: "dog park",},
        {id: 533, parkid: 167, parkName: "mount washington community park", features: "amphitheatre",},
        {id: 534, parkid: 97, parkName: "iroquois", features: "amphitheatre",},
        {id: 535, parkid: 168, parkName: "lindsay duvall", features: "playground",},
        {id: 536, parkid: 168, parkName: "lindsay duvall", features: "tennis",},
        {id: 537, parkid: 168, parkName: "lindsay duvall", features: "skatepark",},
        {id: 538, parkid: 169, parkName: "cornell park", features: "playground",},
        {id: 539, parkid: 169, parkName: "cornell park", features: "multiifield",},
        {id: 540, parkid: 170, parkName: "maples park", features: "playground",},
        {id: 541, parkid: 170, parkName: "maples park", features: "picnic",},
        {id: 542, parkid: 170, parkName: "maples park", features: "sprayground",},
        {id: 543, parkid: 170, parkName: "maples park", features: "swings",},
        {id: 544, parkid: 170, parkName: "maples park", features: "restroom",},
        {id: 545, parkid: 171, parkName: "briar hill park", features: "restroom",},
        {id: 546, parkid: 171, parkName: "briar hill park", features: "picnic",},
        {id: 547, parkid: 171, parkName: "briar hill park", features: "playground",},
        {id: 548, parkid: 171, parkName: "briar hill park", features: "basketball",},
        {id: 549, parkid: 171, parkName: "briar hill park", features: "walking",},
        {id: 550, parkid: 171, parkName: "briar hill park", features: "volleyball",},
        {id: 551, parkid: 171, parkName: "briar hill park", features: "tennis",},
        {id: 552, parkid: 171, parkName: "briar hill park", features: "hiking",},
        {id: 553, parkid: 171, parkName: "briar hill park", features: "little library",},
        {id: 554, parkid: 172, parkName: "wendell moore park", features: "community center",},
        {id: 555, parkid: 172, parkName: "wendell moore park", features: "football",},
        {id: 556, parkid: 172, parkName: "wendell moore park", features: "softball",},
        {id: 557, parkid: 172, parkName: "wendell moore park", features: "fishing",},
        {id: 558, parkid: 172, parkName: "wendell moore park", features: "picnic",},
        {id: 559, parkid: 172, parkName: "wendell moore park", features: "archery",},
        {id: 560, parkid: 172, parkName: "wendell moore park", features: "walking",},
        {id: 561, parkid: 172, parkName: "wendell moore park", features: "tennis",},
        {id: 562, parkid: 172, parkName: "wendell moore park", features: "dog park",},
        {id: 563, parkid: 172, parkName: "wendell moore park", features: "disc golf",},
        {id: 564, parkid: 172, parkName: "wendell moore park", features: "restroom",},
        {id: 565, parkid: 172, parkName: "wendell moore park", features: "playground",},
        {id: 566, parkid: 172, parkName: "wendell moore park", features: "swimming",},
        {id: 567, parkid: 74, parkName: "cherokee", features: "archery",},
        {id: 568, parkid: 97, parkName: "iroquois", features: "disc golf",},
        {id: 569, parkid: 96, parkName: "charlie vettiner", features: "disc golf",},
        {id: 570, parkid: 173, parkName: "schamback park", features: "picnic",},
        {id: 571, parkid: 173, parkName: "schamback park", features: "restroom",},
        {id: 572, parkid: 173, parkName: "schamback park", features: "playground",},
        {id: 573, parkid: 173, parkName: "schamback park", features: "basketball",},
        {id: 574, parkid: 173, parkName: "schamback park", features: "fishing",},
        {id: 575, parkid: 174, parkName: "peggy e. baker park", features: "picnic",},
        {id: 576, parkid: 174, parkName: "peggy e. baker park", features: "restroom",},
        {id: 577, parkid: 174, parkName: "peggy e. baker park", features: "playground",},
        {id: 578, parkid: 174, parkName: "peggy e. baker park", features: "basketball",},
        {id: 579, parkid: 174, parkName: "peggy e. baker park", features: "baseball",},
        {id: 580, parkid: 174, parkName: "peggy e. baker park", features: "dog park",},
        {id: 581, parkid: 174, parkName: "peggy e. baker park", features: "walking",},
        {id: 582, parkid: 174, parkName: "peggy e. baker park", features: "little library",},
        {id: 583, parkid: 175, parkName: "morgan conservation park", features: "hiking",},
        {id: 584, parkid: 175, parkName: "morgan conservation park", features: "picnic",},
        {id: 585, parkid: 175, parkName: "morgan conservation park", features: "restroom",},
        {id: 586, parkid: 176, parkName: "54 acre multii-use park", features: "soccer",},
        {id: 587, parkid: 176, parkName: "54 acre multii-use park", features: "multiifield",},
        {id: 588, parkid: 177, parkName: "celebration park", features: "",},
        {id: 589, parkid: 178, parkName: "creasey mahan nature preserve", features: "manor",},
        {id: 590, parkid: 178, parkName: "creasey mahan nature preserve", features: "nature center",},
        {id: 591, parkid: 178, parkName: "creasey mahan nature preserve", features: "gardens",},
        {id: 592, parkid: 178, parkName: "creasey mahan nature preserve", features: "hiking",},
        {id: 593, parkid: 178, parkName: "creasey mahan nature preserve", features: "park",},
        {id: 594, parkid: 179, parkName: "peewee valley central park", features: "walking",},
        {id: 595, parkid: 180, parkName: "walsh park", features: "playground",},
        {id: 596, parkid: 180, parkName: "walsh park", features: "swings",},
        {id: 597, parkid: 180, parkName: "walsh park", features: "picnic",},
        {id: 598, parkid: 180, parkName: "walsh park", features: "restroom",},
        {id: 599, parkid: 180, parkName: "walsh park", features: "baseball",},
        {id: 600, parkid: 181, parkName: "wilborn park", features: "playground",},
        {id: 601, parkid: 181, parkName: "wilborn park", features: "swings",},
        {id: 602, parkid: 181, parkName: "wilborn park", features: "fishing",},
        {id: 603, parkid: 181, parkName: "wilborn park", features: "walking",},
        {id: 604, parkid: 181, parkName: "wilborn park", features: "hiking",},
        {id: 605, parkid: 181, parkName: "wilborn park", features: "restroom",},
        {id: 606, parkid: 181, parkName: "wilborn park", features: "picnic",},
        {id: 607, parkid: 182, parkName: "shirley's arbor", features: "retention pond",},
        {id: 608, parkid: 182, parkName: "shirley's arbor", features: "exercise stations",},
        {id: 609, parkid: 182, parkName: "shirley's arbor", features: "park benches",},
        {id: 610, parkid: 182, parkName: "shirley's arbor", features: "walking",},
        {id: 611, parkid: 182, parkName: "shirley's arbor", features: "multiifield",},
        {id: 612, parkid: 183, parkName: "chapel lake park", features: "fishing",},
        {id: 613, parkid: 183, parkName: "chapel lake park", features: "picnic",},
        {id: 614, parkid: 183, parkName: "chapel lake park", features: "playground",},
        {id: 615, parkid: 183, parkName: "chapel lake park", features: "walking",},
        {id: 616, parkid: 183, parkName: "chapel lake park", features: "hiking",},
        {id: 617, parkid: 183, parkName: "chapel lake park", features: "restroom",},
        {id: 618, parkid: 184, parkName: "perrin family park", features: "catherine's teddy bear place",},
        {id: 619, parkid: 184, parkName: "perrin family park", features: "sandbox",},
        {id: 620, parkid: 184, parkName: "perrin family park", features: "playground",},
        {id: 621, parkid: 184, parkName: "perrin family park", features: "picnic",},
        {id: 622, parkid: 184, parkName: "perrin family park", features: "walking",},
        {id: 623, parkid: 185, parkName: "glossbrenner public garden", features: "gardens",},
        {id: 624, parkid: 185, parkName: "glossbrenner public garden", features: "benches",},
        {id: 625, parkid: 186, parkName: "harmony park", features: "musical instruments",},
        {id: 626, parkid: 186, parkName: "harmony park", features: "murals",},
        {id: 627, parkid: 186, parkName: "harmony park", features: "stage",},
        {id: 628, parkid: 187, parkName: "big 4 station park", features: "farmers market",},
        {id: 629, parkid: 187, parkName: "big 4 station park", features: "playground",},
        {id: 630, parkid: 187, parkName: "big 4 station park", features: "benches",},
        {id: 631, parkid: 187, parkName: "big 4 station park", features: "picnic",},
        {id: 632, parkid: 187, parkName: "big 4 station park", features: "walking",},
        {id: 633, parkid: 188, parkName: "jeffersonville skate park", features: "skatepark",},
        {id: 634, parkid: 188, parkName: "jeffersonville skate park", features: "walking",},
        {id: 635, parkid: 189, parkName: "shirley hall park", features: "football",},
        {id: 636, parkid: 189, parkName: "shirley hall park", features: "walking",},
        {id: 637, parkid: 189, parkName: "shirley hall park", features: "restroom",},
        {id: 638, parkid: 189, parkName: "shirley hall park", features: "concessions",},
        {id: 639, parkid: 190, parkName: "woehrle athletic complex", features: "concessions",},
        {id: 640, parkid: 190, parkName: "woehrle athletic complex", features: "soccer",},
        {id: 641, parkid: 190, parkName: "woehrle athletic complex", features: "football",},
        {id: 642, parkid: 190, parkName: "woehrle athletic complex", features: "playground",},
        {id: 643, parkid: 190, parkName: "woehrle athletic complex", features: "drinking fountain",},
        {id: 644, parkid: 190, parkName: "woehrle athletic complex", features: "conference",},
        {id: 645, parkid: 191, parkName: "riverstage", features: "stage",},
        {id: 646, parkid: 191, parkName: "riverstage", features: "walking",},
        {id: 647, parkid: 191, parkName: "riverstage", features: "benches",},
        {id: 648, parkid: 192, parkName: "nachand fieldhouse", features: "exercise stations",},
        {id: 649, parkid: 192, parkName: "nachand fieldhouse", features: "volleyball",},
        {id: 650, parkid: 192, parkName: "nachand fieldhouse", features: "basketball",},
        {id: 651, parkid: 192, parkName: "nachand fieldhouse", features: "walking",},
        {id: 652, parkid: 192, parkName: "nachand fieldhouse", features: "restroom",},
        {id: 653, parkid: 193, parkName: "jeffersonville aquatic center", features: "swimming",},
        {id: 654, parkid: 193, parkName: "jeffersonville aquatic center", features: "restroom",},
        {id: 655, parkid: 194, parkName: "veterans memorial park", features: "memorials",},
        {id: 656, parkid: 194, parkName: "veterans memorial park", features: "benches",},
        {id: 657, parkid: 195, parkName: "w. f. throckmorton park", features: "benches",},
        {id: 658, parkid: 195, parkName: "w. f. throckmorton park", features: "picnic",},
        {id: 659, parkid: 195, parkName: "w. f. throckmorton park", features: "playground",},
        {id: 660, parkid: 195, parkName: "w. f. throckmorton park", features: "tennis",},
        {id: 661, parkid: 196, parkName: "samuel g. shannon memorial park", features: "baseball",},
        {id: 662, parkid: 196, parkName: "samuel g. shannon memorial park", features: "restroom",},
        {id: 663, parkid: 197, parkName: "richard l. vissing park", features: "walking",},
        {id: 664, parkid: 197, parkName: "richard l. vissing park", features: "baseball",},
        {id: 665, parkid: 197, parkName: "richard l. vissing park", features: "restroom",},
        {id: 666, parkid: 197, parkName: "richard l. vissing park", features: "playground",},
        {id: 667, parkid: 197, parkName: "richard l. vissing park", features: "basketball",},
        {id: 668, parkid: 217, parkName: "allison brook park", features: "benches",},
        {id: 669, parkid: 217, parkName: "allison brook park", features: "playground",},
        {id: 670, parkid: 217, parkName: "allison brook park", features: "walking",},
        {id: 671, parkid: 198, parkName: "highland dog park", features: "dog park",},
        {id: 672, parkid: 198, parkName: "highland dog park", features: "benches",},
        {id: 673, parkid: 198, parkName: "highland dog park", features: "picnic",},
        {id: 674, parkid: 198, parkName: "highland dog park", features: "basketball",},
        {id: 675, parkid: 198, parkName: "highland dog park", features: "playground",},
        {id: 676, parkid: 199, parkName: "john wilcoxson park", features: "playground",},
        {id: 677, parkid: 199, parkName: "john wilcoxson park", features: "picnic",},
        {id: 678, parkid: 199, parkName: "john wilcoxson park", features: "benches",},
        {id: 679, parkid: 200, parkName: "richard b. wathen park", features: "playground",},
        {id: 680, parkid: 200, parkName: "richard b. wathen park", features: "restroom",},
        {id: 681, parkid: 200, parkName: "richard b. wathen park", features: "pond",},
        {id: 682, parkid: 200, parkName: "richard b. wathen park", features: "picnic",},
        {id: 683, parkid: 201, parkName: "luther f. warder park", features: "gazebo",},
        {id: 684, parkid: 201, parkName: "luther f. warder park", features: "statue",},
        {id: 685, parkid: 201, parkName: "luther f. warder park", features: "walking",},
        {id: 686, parkid: 202, parkName: "steamboat park", features: "little library",},
        {id: 687, parkid: 202, parkName: "steamboat park", features: "picnic",},
        {id: 688, parkid: 202, parkName: "steamboat park", features: "benches",},
        {id: 689, parkid: 203, parkName: "s. harlan vogt park", features: "picnic",},
        {id: 690, parkid: 203, parkName: "s. harlan vogt park", features: "benches",},
        {id: 691, parkid: 204, parkName: "preservation park", features: "benches",},
        {id: 692, parkid: 204, parkName: "preservation park", features: "train station",},
        {id: 693, parkid: 205, parkName: "port fulton park", features: "playground",},
        {id: 694, parkid: 205, parkName: "port fulton park", features: "picnic",},
        {id: 695, parkid: 205, parkName: "port fulton park", features: "restroom",},
        {id: 696, parkid: 205, parkName: "port fulton park", features: "benches",},
        {id: 697, parkid: 206, parkName: "poppy park", features: "playground",},
        {id: 698, parkid: 208, parkName: "lottie oglesby park", features: "walking",},
        {id: 699, parkid: 208, parkName: "lottie oglesby park", features: "basketball",},
        {id: 700, parkid: 208, parkName: "lottie oglesby park", features: "benches",},
        {id: 701, parkid: 209, parkName: "kyle vissing park", features: "basketball",},
        {id: 702, parkid: 209, parkName: "kyle vissing park", features: "pond",},
        {id: 703, parkid: 209, parkName: "kyle vissing park", features: "playground",},
        {id: 704, parkid: 210, parkName: "pamela j inman park", features: "playground",},
        {id: 705, parkid: 210, parkName: "pamela j inman park", features: "picnic",},
        {id: 706, parkid: 211, parkName: "henry landsen park", features: "benches",},
        {id: 707, parkid: 211, parkName: "henry landsen park", features: "gazebo",},
        {id: 708, parkid: 211, parkName: "henry landsen park", features: "walking",},
        {id: 709, parkid: 211, parkName: "henry landsen park", features: "restroom",},
        {id: 710, parkid: 212, parkName: "gaither park", features: "sculpture",},
        {id: 711, parkid: 212, parkName: "gaither park", features: "benches",},
        {id: 712, parkid: 213, parkName: "forest park", features: "benches",},
        {id: 713, parkid: 213, parkName: "forest park", features: "picnic",},
        {id: 714, parkid: 213, parkName: "forest park", features: "playground",},
        {id: 715, parkid: 214, parkName: "james t. duffy landing", features: "boat ramp",},
        {id: 716, parkid: 214, parkName: "james t. duffy landing", features: "restroom",},
        {id: 717, parkid: 214, parkName: "james t. duffy landing", features: "playground",},
        {id: 718, parkid: 215, parkName: "connie sellmer park", features: "playground",},
        {id: 719, parkid: 215, parkName: "connie sellmer park", features: "benches",},
        {id: 720, parkid: 215, parkName: "connie sellmer park", features: "picnic",},
        {id: 721, parkid: 216, parkName: "bob hedge park", features: "playground",},
        {id: 722, parkid: 216, parkName: "bob hedge park", features: "exercise stations",},
        {id: 723, parkid: 216, parkName: "bob hedge park", features: "picnic",},
        {id: 724, parkid: 216, parkName: "bob hedge park", features: "little library",},
        {id: 725, parkid: 218, parkName: "ashland park", features: "playground",},
        {id: 726, parkid: 218, parkName: "ashland park", features: "picnic",},
        {id: 727, parkid: 218, parkName: "ashland park", features: "walking",},
        {id: 728, parkid: 219, parkName: "beechwood park", features: "playground",},
        {id: 729, parkid: 219, parkName: "beechwood park", features: "basketball",},
        {id: 730, parkid: 219, parkName: "beechwood park", features: "picnic",},
        {id: 731, parkid: 220, parkName: "cedar park", features: "basketball",},
        {id: 732, parkid: 220, parkName: "cedar park", features: "playground",},
        {id: 733, parkid: 221, parkName: "colgate park", features: "basketball",},
        {id: 734, parkid: 221, parkName: "colgate park", features: "playground",},
        {id: 735, parkid: 221, parkName: "colgate park", features: "tennis",},
        {id: 736, parkid: 221, parkName: "colgate park", features: "picnic",},
        {id: 737, parkid: 221, parkName: "colgate park", features: "swimming",},
        {id: 738, parkid: 222, parkName: "gaskell park", features: "picnic",},
        {id: 739, parkid: 222, parkName: "gaskell park", features: "playground",},
        {id: 740, parkid: 222, parkName: "gaskell park", features: "basketball",},
        {id: 741, parkid: 223, parkName: "gateway park", features: "restroom",},
        {id: 742, parkid: 223, parkName: "gateway park", features: "playground",},
        {id: 743, parkid: 223, parkName: "gateway park", features: "splash pad",},
        {id: 744, parkid: 223, parkName: "gateway park", features: "event lawn",},
        {id: 745, parkid: 223, parkName: "gateway park", features: "stage",},
        {id: 746, parkid: 223, parkName: "gateway park", features: "baseball",},
        {id: 747, parkid: 223, parkName: "gateway park", features: "walking",},
        {id: 748, parkid: 224, parkName: "lapping park", features: "golf",},
        {id: 749, parkid: 224, parkName: "lapping park", features: "softball",},
        {id: 750, parkid: 224, parkName: "lapping park", features: "concessions",},
        {id: 751, parkid: 224, parkName: "lapping park", features: "restroom",},
        {id: 752, parkid: 224, parkName: "lapping park", features: "walking",},
        {id: 753, parkid: 224, parkName: "lapping park", features: "disc golf",},
        {id: 754, parkid: 224, parkName: "lapping park", features: "basketball",},
        {id: 755, parkid: 224, parkName: "lapping park", features: "horseshoes",},
        {id: 756, parkid: 224, parkName: "lapping park", features: "volleyball",},
        {id: 757, parkid: 224, parkName: "lapping park", features: "picnic",},
        {id: 758, parkid: 224, parkName: "lapping park", features: "amphitheatre",},
        {id: 759, parkid: 225, parkName: "lewis and clark park", features: "george rogers clark cabin",},
        {id: 760, parkid: 226, parkName: "parkwood park", features: "baseball",},
        {id: 761, parkid: 226, parkName: "parkwood park", features: "football",},
        {id: 762, parkid: 226, parkName: "parkwood park", features: "soccer",},
        {id: 763, parkid: 226, parkName: "parkwood park", features: "playground",},
        {id: 764, parkid: 227, parkName: "ray lawrence park", features: "tennis",},
        {id: 765, parkid: 227, parkName: "ray lawrence park", features: "picnic",},
        {id: 766, parkid: 227, parkName: "ray lawrence park", features: "tennis",},
        {id: 767, parkid: 227, parkName: "ray lawrence park", features: "pickleball",},
        {id: 768, parkid: 227, parkName: "ray lawrence park", features: "playground",},
        {id: 769, parkid: 228, parkName: "anderson park", features: "softball",},
        {id: 770, parkid: 228, parkName: "anderson park", features: "restroom",},
        {id: 771, parkid: 228, parkName: "anderson park", features: "concessions",},
        {id: 772, parkid: 229, parkName: "bicknell park", features: "picnic",},
        {id: 773, parkid: 229, parkName: "bicknell park", features: "basketball",},
        {id: 774, parkid: 229, parkName: "bicknell park", features: "walking",},
        {id: 775, parkid: 229, parkName: "bicknell park", features: "playground",},
        {id: 776, parkid: 229, parkName: "bicknell park", features: "restroom",},
        {id: 777, parkid: 229, parkName: "bicknell park", features: "multiifield",},
        {id: 778, parkid: 230, parkName: "billy herman park", features: "baseball",},
        {id: 779, parkid: 230, parkName: "billy herman park", features: "walking",},
        {id: 780, parkid: 230, parkName: "billy herman park", features: "restroom",},
        {id: 781, parkid: 230, parkName: "billy herman park", features: "concessions",},
        {id: 782, parkid: 231, parkName: "binford park", features: "concessions",},
        {id: 783, parkid: 231, parkName: "binford park", features: "restroom",},
        {id: 784, parkid: 231, parkName: "binford park", features: "basketball",},
        {id: 785, parkid: 231, parkName: "binford park", features: "playground",},
        {id: 786, parkid: 231, parkName: "binford park", features: "soccer",},
        {id: 787, parkid: 232, parkName: "cannon acres soccer field", features: "soccer",},
        {id: 788, parkid: 234, parkName: "divison street park", features: "basketball",},
        {id: 789, parkid: 233, parkName: "cherry valley golf course", features: "golf",},
        {id: 790, parkid: 235, parkName: "fairmont park", features: "picnic",},
        {id: 791, parkid: 235, parkName: "fairmont park", features: "baseball",},
        {id: 792, parkid: 235, parkName: "fairmont park", features: "playground",},
        {id: 793, parkid: 235, parkName: "fairmont park", features: "basketball",},
        {id: 794, parkid: 235, parkName: "fairmont park", features: "walking",},
        {id: 795, parkid: 236, parkName: "griffin receration center", features: "restroom",},
        {id: 796, parkid: 236, parkName: "griffin receration center", features: "exercise stations",},
        {id: 797, parkid: 236, parkName: "griffin receration center", features: "softball",},
        {id: 798, parkid: 236, parkName: "griffin receration center", features: "basketball",},
        {id: 799, parkid: 236, parkName: "griffin receration center", features: "volleyball",},
        {id: 800, parkid: 236, parkName: "griffin receration center", features: "disc golf",},
        {id: 801, parkid: 236, parkName: "griffin receration center", features: "horseshoes",},
        {id: 802, parkid: 237, parkName: "joe kraft park", features: "playground",},
        {id: 803, parkid: 237, parkName: "joe kraft park", features: "baseball",},
        {id: 804, parkid: 237, parkName: "joe kraft park", features: "basketball",},
        {id: 805, parkid: 238, parkName: "millerwood park", features: "basketball",},
        {id: 806, parkid: 238, parkName: "millerwood park", features: "walking",},
        {id: 807, parkid: 238, parkName: "millerwood park", features: "playground",},
        {id: 808, parkid: 239, parkName: "new albany dog park", features: "dog park",},
        {id: 809, parkid: 239, parkName: "new albany dog park", features: "swings",},
        {id: 810, parkid: 239, parkName: "new albany dog park", features: "gazebo",},
        {id: 811, parkid: 239, parkName: "new albany dog park", features: "benches",},
        {id: 812, parkid: 240, parkName: "ritter park", features: "playground",},
        {id: 813, parkid: 240, parkName: "ritter park", features: "picnic",},
        {id: 814, parkid: 240, parkName: "ritter park", features: "basketball",},
        {id: 815, parkid: 240, parkName: "ritter park", features: "benches",},
        {id: 816, parkid: 240, parkName: "ritter park", features: "volleyball",},
        {id: 817, parkid: 240, parkName: "ritter park", features: "walking",},
        {id: 818, parkid: 240, parkName: "ritter park", features: "multiifield",},
        {id: 819, parkid: 241, parkName: "river run family waterpark", features: "swimming",},
        {id: 820, parkid: 241, parkName: "river run family waterpark", features: "splash pad",},
        {id: 821, parkid: 241, parkName: "river run family waterpark", features: "lazy river",},
        {id: 822, parkid: 242, parkName: "sertoma park", features: "picnic",},
        {id: 823, parkid: 242, parkName: "sertoma park", features: "playground",},
        {id: 824, parkid: 242, parkName: "sertoma park", features: "basketball",},
        {id: 825, parkid: 242, parkName: "sertoma park", features: "volleyball",},
        {id: 826, parkid: 242, parkName: "sertoma park", features: "baseball",},
        {id: 827, parkid: 242, parkName: "sertoma park", features: "restroom",},
        {id: 828, parkid: 243, parkName: "silver street park", features: "football",},
        {id: 829, parkid: 243, parkName: "silver street park", features: "soccer",},
        {id: 830, parkid: 243, parkName: "silver street park", features: "basketball",},
        {id: 831, parkid: 243, parkName: "silver street park", features: "skatepark",},
        {id: 832, parkid: 243, parkName: "silver street park", features: "splash pad",},
        {id: 833, parkid: 243, parkName: "silver street park", features: "playground",},
        {id: 834, parkid: 243, parkName: "silver street park", features: "walking",},
        {id: 835, parkid: 243, parkName: "silver street park", features: "picnic",},
        {id: 836, parkid: 243, parkName: "silver street park", features: "baseball",},
        {id: 837, parkid: 243, parkName: "silver street park", features: "entertainment pavillion",},
        {id: 838, parkid: 244, parkName: "valley view golf club", features: "golf",},
        {id: 839, parkid: 247, parkName: "campbell woodland nature trails", features: "walking",},
        {id: 840, parkid: 247, parkName: "campbell woodland nature trails", features: "hiking",},
        {id: 841, parkid: 247, parkName: "campbell woodland nature trails", features: "benches",},
        {id: 842, parkid: 247, parkName: "campbell woodland nature trails", features: "gazebo",},
        {id: 843, parkid: 245, parkName: "bicentennial park", features: "stage",},
        {id: 844, parkid: 246, parkName: "riverfront amphitheater", features: "amphitheatre",},
        {id: 845, parkid: 248, parkName: "galena-lamb park", features: "picnic",},
        {id: 846, parkid: 248, parkName: "galena-lamb park", features: "restroom",},
        {id: 847, parkid: 248, parkName: "galena-lamb park", features: "softball",},
        {id: 848, parkid: 248, parkName: "galena-lamb park", features: "basketball",},
        {id: 849, parkid: 248, parkName: "galena-lamb park", features: "football",},
        {id: 850, parkid: 248, parkName: "galena-lamb park", features: "soccer",},
        {id: 851, parkid: 248, parkName: "galena-lamb park", features: "playground",},
        {id: 852, parkid: 249, parkName: "garry e. cavan park", features: "picnic",},
        {id: 853, parkid: 249, parkName: "garry e. cavan park", features: "disc golf",},
        {id: 854, parkid: 249, parkName: "garry e. cavan park", features: "tennis",},
        {id: 855, parkid: 249, parkName: "garry e. cavan park", features: "playground",},
        {id: 856, parkid: 249, parkName: "garry e. cavan park", features: "horseshoes",},
        {id: 857, parkid: 249, parkName: "garry e. cavan park", features: "restroom",},
        {id: 858, parkid: 249, parkName: "garry e. cavan park", features: "basketball",},
        {id: 859, parkid: 249, parkName: "garry e. cavan park", features: "multiifield",},
        {id: 860, parkid: 250, parkName: "greenville park", features: "picnic",},
        {id: 861, parkid: 250, parkName: "greenville park", features: "restroom",},
        {id: 862, parkid: 250, parkName: "greenville park", features: "playground",},
        {id: 863, parkid: 250, parkName: "greenville park", features: "basketball",},
        {id: 864, parkid: 250, parkName: "greenville park", features: "pickleball",},
        {id: 865, parkid: 250, parkName: "greenville park", features: "walking",},
        {id: 866, parkid: 250, parkName: "greenville park", features: "softball",},
        {id: 867, parkid: 251, parkName: "herman collier park", features: "basketball",},
        {id: 868, parkid: 251, parkName: "herman collier park", features: "restroom",},
        {id: 869, parkid: 251, parkName: "herman collier park", features: "picnic",},
        {id: 870, parkid: 251, parkName: "herman collier park", features: "horseshoes",},
        {id: 871, parkid: 252, parkName: "letty walter park", features: "basketball",},
        {id: 872, parkid: 252, parkName: "letty walter park", features: "football",},
        {id: 873, parkid: 252, parkName: "letty walter park", features: "soccer",},
        {id: 874, parkid: 252, parkName: "letty walter park", features: "picnic",},
        {id: 875, parkid: 252, parkName: "letty walter park", features: "baseball",},
        {id: 876, parkid: 252, parkName: "letty walter park", features: "tennis",},
        {id: 877, parkid: 252, parkName: "letty walter park", features: "playground",},
        {id: 878, parkid: 253, parkName: "kevin hammersmith memorial park", features: "picnic",},
        {id: 879, parkid: 253, parkName: "kevin hammersmith memorial park", features: "basketball",},
        {id: 880, parkid: 253, parkName: "kevin hammersmith memorial park", features: "amphitheatre",},
        {id: 881, parkid: 253, parkName: "kevin hammersmith memorial park", features: "baseball",},
        {id: 882, parkid: 253, parkName: "kevin hammersmith memorial park", features: "playground",},
        {id: 883, parkid: 253, parkName: "kevin hammersmith memorial park", features: "walking",},
        {id: 884, parkid: 254, parkName: "sam peden community park", features: "fishing",},
        {id: 885, parkid: 254, parkName: "sam peden community park", features: "picnic",},
        {id: 886, parkid: 254, parkName: "sam peden community park", features: "walking",},
        {id: 887, parkid: 254, parkName: "sam peden community park", features: "horseshoes",},
        {id: 888, parkid: 254, parkName: "sam peden community park", features: "volleyball",},
        {id: 889, parkid: 254, parkName: "sam peden community park", features: "soccer",},
        {id: 890, parkid: 254, parkName: "sam peden community park", features: "tennis",},
        {id: 891, parkid: 254, parkName: "sam peden community park", features: "basketball",},
        {id: 892, parkid: 254, parkName: "sam peden community park", features: "restroom",},
        {id: 893, parkid: 254, parkName: "sam peden community park", features: "playground",},
        {id: 894, parkid: 255, parkName: "southern iN sports center", features: "basketball",},
        {id: 895, parkid: 255, parkName: "southern iN sports center", features: "volleyball",},
        {id: 896, parkid: 255, parkName: "southern iN sports center", features: "exercise stations",},
        {id: 897, parkid: 255, parkName: "southern iN sports center", features: "restroom",},
        {id: 898, parkid: 256, parkName: "falls of the ohio state park", features: "education center",},
        {id: 899, parkid: 256, parkName: "falls of the ohio state park", features: "fossils",},
        {id: 900, parkid: 256, parkName: "falls of the ohio state park", features: "hiking",},
        {id: 901, parkid: 256, parkName: "falls of the ohio state park", features: "fishing",},
        {id: 902, parkid: 256, parkName: "falls of the ohio state park", features: "walking",},
        {id: 903, parkid: 257, parkName: "deam lake state recreational area", features: "hiking",},
        {id: 904, parkid: 257, parkName: "deam lake state recreational area", features: "picnic",},
        {id: 905, parkid: 257, parkName: "deam lake state recreational area", features: "camping",},
        {id: 906, parkid: 257, parkName: "deam lake state recreational area", features: "rowboats",},
        {id: 907, parkid: 257, parkName: "deam lake state recreational area", features: "fishing",},
        {id: 908, parkid: 257, parkName: "deam lake state recreational area", features: "hunting",},
        {id: 909, parkid: 257, parkName: "deam lake state recreational area", features: "beach",},
        {id: 910, parkid: 257, parkName: "deam lake state recreational area", features: "swimming",},
        {id: 911, parkid: 257, parkName: "deam lake state recreational area", features: "education center",},
        {id: 912, parkid: 258, parkName: "charlestown state park", features: "hiking",},
        {id: 913, parkid: 258, parkName: "charlestown state park", features: "picnic",},
        {id: 914, parkid: 258, parkName: "charlestown state park", features: "fishing",},
        {id: 915, parkid: 258, parkName: "charlestown state park", features: "playground",},
        {id: 916, parkid: 258, parkName: "charlestown state park", features: "camping",},
        {id: 917, parkid: 259, parkName: "clark state forest", features: "camping",},
        {id: 918, parkid: 259, parkName: "clark state forest", features: "hunting",},
        {id: 919, parkid: 259, parkName: "clark state forest", features: "fishing",},
        {id: 920, parkid: 259, parkName: "clark state forest", features: "shooting range",},
        {id: 921, parkid: 259, parkName: "clark state forest", features: "playground",},
        {id: 922, parkid: 259, parkName: "clark state forest", features: "baseball",},
        {id: 923, parkid: 259, parkName: "clark state forest", features: "tennis",},
        {id: 924, parkid: 259, parkName: "clark state forest", features: "basketball",},
        {id: 925, parkid: 259, parkName: "clark state forest", features: "picnic",},
        {id: 926, parkid: 259, parkName: "clark state forest", features: "firetower",},
        {id: 927, parkid: 260, parkName: "harrison-crawford state forest", features: "camping",},
        {id: 928, parkid: 260, parkName: "harrison-crawford state forest", features: "fishing",},
        {id: 929, parkid: 260, parkName: "harrison-crawford state forest", features: "boat ramp",},
        {id: 930, parkid: 260, parkName: "harrison-crawford state forest", features: "hunting",},
        {id: 931, parkid: 261, parkName: "o'bannon woods state park", features: "caves",},
        {id: 932, parkid: 261, parkName: "o'bannon woods state park", features: "pioneer farmstead",},
        {id: 933, parkid: 261, parkName: "o'bannon woods state park", features: "swimming",},
        {id: 934, parkid: 261, parkName: "o'bannon woods state park", features: "education center",},
        {id: 935, parkid: 261, parkName: "o'bannon woods state park", features: "picnic",},
        {id: 936, parkid: 261, parkName: "o'bannon woods state park", features: "horse trails",},
        {id: 937, parkid: 261, parkName: "o'bannon woods state park", features: "fishing",},
        {id: 938, parkid: 261, parkName: "o'bannon woods state park", features: "boat ramp",},
        {id: 939, parkid: 261, parkName: "o'bannon woods state park", features: "hiking",},
        {id: 940, parkid: 261, parkName: "o'bannon woods state park", features: "mountain biking ",},
        {id: 941, parkid: 261, parkName: "o'bannon woods state park", features: "camping",},
        {id: 942, parkid: 262, parkName: "hayswood nature reserve", features: "hiking",},
        {id: 943, parkid: 262, parkName: "hayswood nature reserve", features: "picnic",},
        {id: 944, parkid: 262, parkName: "hayswood nature reserve", features: "restroom",},
        {id: 945, parkid: 262, parkName: "hayswood nature reserve", features: "fishing",},
        {id: 946, parkid: 262, parkName: "hayswood nature reserve", features: "walking",},
        {id: 947, parkid: 262, parkName: "hayswood nature reserve", features: "playground",},
        {id: 948, parkid: 262, parkName: "hayswood nature reserve", features: "horseshoes",},
        {id: 949, parkid: 262, parkName: "hayswood nature reserve", features: "multiifield",},
        {id: 950, parkid: 263, parkName: "rhoads pool", features: "swimming",},
        {id: 951, parkid: 263, parkName: "rhoads pool", features: "basketball",},
        {id: 952, parkid: 263, parkName: "rhoads pool", features: "tennis",},
        {id: 953, parkid: 263, parkName: "rhoads pool", features: "volleyball",},
        {id: 954, parkid: 263, parkName: "rhoads pool", features: "playground",},
        {id: 955, parkid: 263, parkName: "rhoads pool", features: "picnic",},
        {id: 956, parkid: 264, parkName: "south harrison", features: "camping",},
        {id: 957, parkid: 264, parkName: "south harrison", features: "swimming",},
        {id: 958, parkid: 264, parkName: "south harrison", features: "basketball",},
        {id: 959, parkid: 264, parkName: "south harrison", features: "baseball",},
        {id: 960, parkid: 264, parkName: "south harrison", features: "tennis",},
        {id: 961, parkid: 264, parkName: "south harrison", features: "playground",},
        {id: 962, parkid: 264, parkName: "south harrison", features: "walking",},
        {id: 963, parkid: 264, parkName: "south harrison", features: "picnic",},
        {id: 964, parkid: 264, parkName: "south harrison", features: "restroom",},
        {id: 965, parkid: 264, parkName: "south harrison", features: "observatory",},
        {id: 966, parkid: 265, parkName: "buffalo trace", features: "camping",},
        {id: 967, parkid: 265, parkName: "buffalo trace", features: "inn",},
        {id: 968, parkid: 265, parkName: "buffalo trace", features: "swimming",},
        {id: 969, parkid: 265, parkName: "buffalo trace", features: "fishing",},
        {id: 970, parkid: 265, parkName: "buffalo trace", features: "boat ramp",},
        {id: 971, parkid: 265, parkName: "buffalo trace", features: "basketball",},
        {id: 972, parkid: 265, parkName: "buffalo trace", features: "tennis",},
        {id: 973, parkid: 265, parkName: "buffalo trace", features: "baseball",},
        {id: 974, parkid: 265, parkName: "buffalo trace", features: "volleyball",},
        {id: 975, parkid: 265, parkName: "buffalo trace", features: "disc golf",},
        {id: 976, parkid: 265, parkName: "buffalo trace", features: "mountain biking ",},
        {id: 977, parkid: 265, parkName: "buffalo trace", features: "walking",},
        {id: 978, parkid: 265, parkName: "buffalo trace", features: "playground",},
        {id: 979, parkid: 265, parkName: "buffalo trace", features: "petting zoo",},
        {id: 980, parkid: 265, parkName: "buffalo trace", features: "picnic",},
        {id: 981, parkid: 265, parkName: "buffalo trace", features: "restroom",},
        {id: 982, parkid: 266, parkName: "noe's", features: "basketball",},
        {id: 983, parkid: 266, parkName: "noe's", features: "playground",},
        {id: 984, parkid: 266, parkName: "noe's", features: "picnic",},
        {id: 985, parkid: 267, parkName: "gresham", features: "playground",},
        {id: 986, parkid: 267, parkName: "gresham", features: "picnic",},
        {id: 987, parkid: 268, parkName: "battle of corydon", features: "walking",},
        {id: 988, parkid: 269, parkName: "the hubbard house", features: "log cabin",},
        {id: 989, parkid: 270, parkName: "morvin's landing", features: "historical",},
        {id: 990, parkid: 270, parkName: "morvin's landing", features: "boat ramp",},
        {id: 991, parkid: 270, parkName: "morvin's landing", features: "underground railroad site",},
        {id: 992, parkid: 271, parkName: "the overlook park", features: "picnic",},
        {id: 993, parkid: 279, parkName: "lake shelby park & campground", features: "camping",},
        {id: 994, parkid: 279, parkName: "lake shelby park & campground", features: "picnic",},
        {id: 995, parkid: 279, parkName: "lake shelby park & campground", features: "canoeing",},
        {id: 996, parkid: 279, parkName: "lake shelby park & campground", features: "fishing",},
        {id: 997, parkid: 279, parkName: "lake shelby park & campground", features: "walking",},
        {id: 998, parkid: 279, parkName: "lake shelby park & campground", features: "hiking",},
        {id: 999, parkid: 279, parkName: "lake shelby park & campground", features: "playground",},
        {id: 1000, parkid: 278, parkName: "shelbyville greenway", features: "biking",},
        {id: 1001, parkid: 278, parkName: "shelbyville greenway", features: "hiking",},
        {id: 1002, parkid: 278, parkName: "shelbyville greenway", features: "walking",},
        {id: 1003, parkid: 277, parkName: "shelbyville skate park", features: "skatepark",},
        {id: 1004, parkid: 276, parkName: "finchville park", features: "hiking",},
        {id: 1005, parkid: 276, parkName: "finchville park", features: "kite flying",},
        {id: 1006, parkid: 276, parkName: "finchville park", features: "picnic",},
        {id: 1007, parkid: 276, parkName: "finchville park", features: "walking",},
        {id: 1008, parkid: 276, parkName: "finchville park", features: "playground",},
        {id: 1009, parkid: 275, parkName: "shelby trails park", features: "hiking",},
        {id: 1010, parkid: 275, parkName: "shelby trails park", features: "horseback riding",},
        {id: 1011, parkid: 274, parkName: "red orchard park", features: "playground",},
        {id: 1012, parkid: 274, parkName: "red orchard park", features: "kite flying",},
        {id: 1013, parkid: 274, parkName: "red orchard park", features: "horseback riding",},
        {id: 1014, parkid: 274, parkName: "red orchard park", features: "hiking",},
        {id: 1015, parkid: 274, parkName: "red orchard park", features: "walking",},
        {id: 1016, parkid: 274, parkName: "red orchard park", features: "dog park",},
        {id: 1017, parkid: 273, parkName: "clear creek park", features: "golf",},
        {id: 1018, parkid: 273, parkName: "clear creek park", features: "camping",},
        {id: 1019, parkid: 273, parkName: "clear creek park", features: "canoeing",},
        {id: 1020, parkid: 273, parkName: "clear creek park", features: "concerts",},
        {id: 1021, parkid: 273, parkName: "clear creek park", features: "fireworks",},
        {id: 1022, parkid: 273, parkName: "clear creek park", features: "dog park",},
        {id: 1023, parkid: 273, parkName: "clear creek park", features: "fishing",},
        {id: 1024, parkid: 273, parkName: "clear creek park", features: "exercise stations",},
        {id: 1025, parkid: 273, parkName: "clear creek park", features: "walking",},
        {id: 1026, parkid: 273, parkName: "clear creek park", features: "hiking",},
        {id: 1027, parkid: 273, parkName: "clear creek park", features: "horseback riding",},
        {id: 1028, parkid: 273, parkName: "clear creek park", features: "kite flying",},
        {id: 1029, parkid: 280, parkName: "battletown park", features: "picnic",},
        {id: 1030, parkid: 280, parkName: "battletown park", features: "playground",},
        {id: 1031, parkid: 281, parkName: "brandenburg riverfront park", features: "playground",},
        {id: 1032, parkid: 281, parkName: "brandenburg riverfront park", features: "walking",},
        {id: 1033, parkid: 281, parkName: "brandenburg riverfront park", features: "soccer",},
        {id: 1034, parkid: 281, parkName: "brandenburg riverfront park", features: "amphitheatre",},
        {id: 1035, parkid: 281, parkName: "brandenburg riverfront park", features: "bandstand",},
        {id: 1036, parkid: 281, parkName: "brandenburg riverfront park", features: "picnic",},
        {id: 1037, parkid: 281, parkName: "brandenburg riverfront park", features: "chess",},
        {id: 1038, parkid: 281, parkName: "brandenburg riverfront park", features: "re-enactment",},
        {id: 1039, parkid: 281, parkName: "brandenburg riverfront park", features: "christmas decorations",},
        {id: 1040, parkid: 156, parkName: "brown park", features: "christmas decorations",},
        {id: 1041, parkid: 97, parkName: "iroquois", features: "halloween decorations",},
        {id: 1042, parkid: 97, parkName: "iroquois", features: "christmas decorations",},
        {id: 1043, parkid: 282, parkName: "buttermilk falls trail", features: "walking",},
        {id: 1044, parkid: 282, parkName: "buttermilk falls trail", features: "hiking",},
        {id: 1045, parkid: 282, parkName: "buttermilk falls trail", features: "biking",},
        {id: 1046, parkid: 282, parkName: "buttermilk falls trail", features: "benches",},
        {id: 1047, parkid: 282, parkName: "buttermilk falls trail", features: "picnic",},
        {id: 1048, parkid: 283, parkName: "concordia park", features: "boat ramp",},
        {id: 1049, parkid: 283, parkName: "concordia park", features: "picnic",},
        {id: 1050, parkid: 283, parkName: "concordia park", features: "camping",},
        {id: 1051, parkid: 284, parkName: "dianna's park", features: "playground",},
        {id: 1052, parkid: 285, parkName: "flaherty community park", features: "baseball",},
        {id: 1053, parkid: 285, parkName: "flaherty community park", features: "picnic",},
        {id: 1054, parkid: 286, parkName: "meade-olin park", features: "baseball",},
        {id: 1055, parkid: 286, parkName: "meade-olin park", features: "basketball",},
        {id: 1056, parkid: 286, parkName: "meade-olin park", features: "soccer",},
        {id: 1057, parkid: 286, parkName: "meade-olin park", features: "picnic",},
        {id: 1058, parkid: 286, parkName: "meade-olin park", features: "restroom",},
        {id: 1059, parkid: 286, parkName: "meade-olin park", features: "disc golf",},
        {id: 1060, parkid: 286, parkName: "meade-olin park", features: "playground",},
        {id: 1061, parkid: 288, parkName: "wolf creek park", features: "boat ramp",},
        {id: 1062, parkid: 290, parkName: "bernheim arboretum and research forest", features: "sculpture",},
        {id: 1063, parkid: 290, parkName: "bernheim arboretum and research forest", features: "playground",},
        {id: 1064, parkid: 290, parkName: "bernheim arboretum and research forest", features: "restroom",},
        {id: 1065, parkid: 290, parkName: "bernheim arboretum and research forest", features: "picnic",},
        {id: 1066, parkid: 290, parkName: "bernheim arboretum and research forest", features: "education center",},
        {id: 1067, parkid: 290, parkName: "bernheim arboretum and research forest", features: "walking",},
        {id: 1068, parkid: 290, parkName: "bernheim arboretum and research forest", features: "hiking",},
        {id: 1069, parkid: 5, parkName: "ben washer", features: "picnic",},
        {id: 1070, parkid: 5, parkName: "ben washer", features: "playground",},
        {id: 1071, parkid: 14, parkName: "cliff", features: "playground",},
        {id: 1072, parkid: 35, parkName: "charles young", features: "playground",},
        {id: 1073, parkid: 37, parkName: "iroquois golf course", features: "golf",},
        {id: 1074, parkid: 40, parkName: "sun valley golf course", features: "golf",},
        {id: 1075, parkid: 49, parkName: "long run cemetary", features: "cemetary",},
        {id: 1076, parkid: 53, parkName: "memorial", features: "bench",},
        {id: 1077, parkid: 68, parkName: "twin park", features: "open space",},
        {id: 1078, parkid: 71, parkName: "wayside", features: "bench",},
        {id: 1079, parkid: 85, parkName: "crescent hill golf course", features: "golf",},
        {id: 1080, parkid: 92, parkName: "long run golf course", features: "golf",},
        {id: 1081, parkid: 99, parkName: "cherokee golf course", features: "golf",},
        {id: 1082, parkid: 108, parkName: "bobby nichols golf course", features: "golf",},
        {id: 1083, parkid: 110, parkName: "churchill", features: "playground",},
        {id: 1084, parkid: 121, parkName: "eva bandman", features: "cyclocross course",},
        {id: 1085, parkid: 127, parkName: "castlewood open space", features: "open space",},
        {id: 1086, parkid: 128, parkName: "california open space", features: "open space",},
        {id: 1087, parkid: 130, parkName: "rose farm", features: "bench",},
        {id: 1088, parkid: 133, parkName: "clifton heights greenway", features: "walking",},
        {id: 1089, parkid: 134, parkName: "cYrill allgeier community center", features: "community center",},
        {id: 1090, parkid: 134, parkName: "cYrill allgeier community center", features: "baseball",},
        {id: 1091, parkid: 136, parkName: "patriots peace memorial", features: "memorial",},
        {id: 1092, parkid: 137, parkName: "buechel parcel", features: "natural area",},
        {id: 1093, parkid: 138, parkName: "mahoney", features: "future development",},
        {id: 1094, parkid: 139, parkName: "peterson", features: "natural area",},
        {id: 1095, parkid: 140, parkName: "jefferson memorial parcel 22", features: "natural area",},
        {id: 1096, parkid: 141, parkName: "southern parkway", features: "olmsted",},
        {id: 1097, parkid: 142, parkName: "eastern parkway", features: "olmsted",},
        {id: 1098, parkid: 143, parkName: "Northwestern parkway", features: "olmsted",},
        {id: 1099, parkid: 144, parkName: "southwestern parkway", features: "olmsted",},
        {id: 1100, parkid: 145, parkName: "algonquin parkway", features: "olmsted",},
        {id: 1101, parkid: 152, parkName: "galvin court", features: "natural area",},
        {id: 1102, parkid: 162, parkName: "jeffersontown memorial park", features: "restroom",},
        {id: 1103, parkid: 162, parkName: "jeffersontown memorial park", features: "picnic",},
        {id: 1104, parkid: 162, parkName: "jeffersontown memorial park", features: "playground",},
        {id: 1105, parkid: 162, parkName: "jeffersontown memorial park", features: "baseball",},
        {id: 1106, parkid: 162, parkName: "jeffersontown memorial park", features: "basketball",},
        {id: 1107, parkid: 162, parkName: "jeffersontown memorial park", features: "walking",},
        {id: 1108, parkid: 162, parkName: "jeffersontown memorial park", features: "veteran memorial",},
        {id: 1109, parkid: 162, parkName: "jeffersontown memorial park", features: "helicopter",},
        {id: 1110, parkid: 162, parkName: "jeffersontown memorial park", features: "tank",},
        {id: 1111, parkid: 163, parkName: "david l armstrong recreation center", features: "restroom",},
        {id: 1112, parkid: 163, parkName: "david l armstrong recreation center", features: "basketball",},
        {id: 1113, parkid: 164, parkName: "skyview", features: "baseball",},
        {id: 1114, parkid: 164, parkName: "skyview", features: "spraypad",},
        {id: 1115, parkid: 164, parkName: "skyview", features: "walking",},
        {id: 1116, parkid: 164, parkName: "skyview", features: "running",},
        {id: 1117, parkid: 164, parkName: "skyview", features: "restroom",},
        {id: 1118, parkid: 164, parkName: "skyview", features: "football",},
        {id: 1119, parkid: 165, parkName: "plainview swim center", features: "swimming",},
        {id: 1120, parkid: 165, parkName: "plainview swim center", features: "restrooms",},
        {id: 1121, parkid: 166, parkName: "waterfront", features: "running",},
        {id: 1122, parkid: 166, parkName: "waterfront", features: "walking",},
        {id: 1123, parkid: 166, parkName: "waterfront", features: "playground",},
        {id: 1124, parkid: 166, parkName: "waterfront", features: "sculpture",},
        {id: 1125, parkid: 166, parkName: "waterfront", features: "multiifield",},
        {id: 1126, parkid: 166, parkName: "waterfront", features: "picnic",},
        {id: 1127, parkid: 166, parkName: "waterfront", features: "canoeing",},
        {id: 1128, parkid: 166, parkName: "waterfront", features: "concert venue",},
        {id: 1129, parkid: 207, parkName: "meadows park", features: "natural area",},
        



        
        
]

const featuresList = [];

for (i in parks) {
    let pName = highlights[i].parkName
    if (featuresList.includes(pName) !== true) {
        featuresList.push(pName)        
    }
    
}
for (i in parks) {
    let feature = parks[i].features
    if (featuresList.includes(feature) !== true ) {
        featuresList.push(feature)
    } 
}