const parks = [
    {id: 1,	parkName: '35th street', 	address: "814 SOUTH 35TH ST",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 2,	parkName: "crescent hill",	address: "3110 BROWNSBORO RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 3, parkName: "algonquin",	address: "1614 CYPRESS ST",	city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 4, parkName: "bellevue",	address: "4711 BELLEVUE AVE",	city: "louisville", county: "jefferson", zipCode: "40215", visited: false, favorite: false,},
            {id: 5, parkName: "ben washer",	address: "519 WEST KENTUCKY ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 6, parkName: "bingham",	address: " 160 CORAL AVE",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 7, parkName: "bradley",	address: "2516 BRADLEY AVE",	city: "louisville", county: "jefferson", zipCode: "40217", visited: false, favorite: false,},
            {id: 8, parkName: "buechel",	address: "247 ALPHA AVE",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 9, parkName: "camp taylor",	address: "4201 LEE AVE",	city: "louisville", county: "jefferson", zipCode: "40213", visited: false, favorite: false,},
            {id: 10, parkName: "cane run",	address: "4816 CANE RUN RD", city: "louisville", county: "jefferson", zipCode: "40216", visited: false, favorite: false,},
            {id: 11, parkName: "caperton swamp",	address: "3916 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 12, parkName: "central",	address: "1340 SOUTH FOURTH ST", city: "louisville", county: "jefferson", zipCode: "40208", visited: false, favorite: false,},
            {id: 13, parkName: "chickasaw",	address: "1200 SOUTHWESTERN PKWY",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 14, parkName: "cliff",	address: "4666 CLIFF AVE",	city: "louisville", county: "jefferson", zipCode: "40215", visited: false, favorite: false,},
            {id: 15, parkName: "clifton", address: "133 NORTH CHARLTON ST",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 16, parkName: "carrie gaulbert cox",	address: "3730 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 17, parkName: "douglass",	address: "2305 DOUGLASS BLVD",	city: "louisville", county: "jefferson", zipCode: "40205", visited: false, favorite: false,},
            {id: 18, parkName: "eastover",	address: "118 SACRED HEART LN",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 19, parkName: "fairdale mini", address: "10714 WEST MANSLICK RD",	city: 'fairdale', county: 'jefferson', zipCode: "40118", visited: false, favorite: false,},
            {id: 20, parkName: "flaget field",	address: "4425 GREENWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 21, parkName: "german-paristown",	address: "1134 EAST KENTUCKY ST",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 22, parkName: "gnandinger", address: "103 ELLISON AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 23, parkName: "william harrison",	address: "3232 OLEANDA AVE",	city: "louisville", county: "jefferson", zipCode: "40215", visited: false, favorite: false,},
            {id: 24, parkName: "hopewell",	address: "509 NORTH BIRCHWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 25, parkName: "nelson hornbeck",	address: "709 FAIRDALE RD",	city: "louisville", county: "jefferson", zipCode: "40118", visited: false, favorite: false,},
            {id: 26, parkName: "hounz ln",	address: "2300 HOUNZ LN",	city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 27, parkName: "irish hill",	address: "1131 LEXINGTON RD",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 28, parkName: "louis b. israel", address: "4708 SOUTH FIRST ST",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 29, parkName: "hays kennedy",	address: "7303 BEACHLAND BEACH RD",	city: "prospect", county: "jefferson", zipCode: "40059", visited: false, favorite: false,},
            {id: 30, parkName: "kennedy court",	address: "225 KENNEDY AVE",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 31, parkName: "klondike",	address: "3809 KLONDIKE LN",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 32, parkName: "lake dreamland", address: "4400 LAKE DREAMLAND RD",	city: "louisville", county: "jefferson", zipCode: "40216", visited: false, favorite: false,},
            {id: 34, parkName: "seneca golf course",	 address: "2300 PEE WEE REESE RD",	city: "louisville", county: "jefferson", zipCode: "40205", visited: false, favorite: false,},
            {id: 35, parkName: "charles young",	address: "2721 LYTLE ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 36, parkName: "roberson run",	address: "8205 JUDGE BLVD",	city: "louisville", county: "jefferson", zipCode: "40219", visited: false, favorite: false,},
            {id: 37, parkName: "iroquois golf course",	address: "1501 RUNDILL RD",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 38, parkName: "norfolk acres",	address: "4300 CORAM WAY",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 39, parkName: "california",	address: "1104 SOUTH 16TH ST",	city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 40, parkName: "sun valley golf course", address: "6505 BETHANY LN",	city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            {id: 41, parkName: "laporte",	address: "2529 BANK ST", city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 42, parkName: "elliot square",	address: "630 SOUTH 28TH ST",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 43, parkName: "emerson",	address: "1100 SYLVIA ST",	city: "louisville", county: "jefferson", zipCode: "40217", visited: false, favorite: false,},
            {id: 44, parkName: "mcneely lake",	address: "10500 CEDAR CREEK RD",	city: "louisville", county: "jefferson", zipCode: "40229", visited: false, favorite: false,},
            {id: 45, parkName: "boone square",	address: "1935 ROWAN ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 46, parkName: "old walnut / beecher",	address: "904 WEST MUHAMMAD ALI BLVD",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 47, parkName: "slevin",	address: "341 NORTH 25TH ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 48, parkName: "russell lee",	address: "3701 SOUTHERN AVE",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},	 	
            {id: 50, parkName: "david armstrong extreme", address: "148 NORTH CLAY ST",	city: "louisville", county: "jefferson", zipCode: "40202", visited: false, favorite: false,},
            {id: 51, parkName: "magnolia", address: "1407 SOUTH SECOND ST",	city: "louisville", county: "jefferson", zipCode: "40208", visited: false, favorite: false,},
            {id: 52, parkName: "medora",	address: "6210 PENDLETON RD",	city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            {id: 53, parkName: "memorial",	address: "971 SOUTH FOURTH ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 54, parkName: "g.g. moore",	address: "626 M ST",	city: "louisville", county: "jefferson", zipCode: "40208", visited: false, favorite: false,},
            {id: 55, parkName: "parkhill",	address: "1703 SOUTH 13TH ST",	city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 56, parkName: "patterson",	address: "1418 MORTON AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 57, parkName: "peewee",	address: "2913 KLONDIKE LN",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 58, parkName: "huston quin",	address: "4105 SOUTH FIRST ST",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 59, parkName: "ginny reichard",	address: "1001 FRANKLIN ST",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 60, parkName: "riverside gardens",	address: "2899 LEES LN",	city: "louisville", county: "jefferson", zipCode: "40216", visited: false, favorite: false,},
            {id: 61, parkName: "riverview",	address: "8202 GREENWOOD RD",	city: "louisville", county: "jefferson", zipCode: "40258", visited: false, favorite: false,},
            {id: 62, parkName: "riverside, the farnsley-moreman landing",	address: "7410 MOORMAN RD",	city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            {id: 63, parkName: "rubel", address: "667 BARRET AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 64, parkName: "shawnee",	address: "4501 WEST BROADWAY",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 65, parkName: "shelby",	address: "600 EAST OAK ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 66, parkName: "story avenue",	address: "1531 STORY AVE",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 67, parkName: "syvlania",	address: "6650 SYLVANIA RD",	city: "louisville", county: "jefferson", zipCode: "40258", visited: false, favorite: false,},
            {id: 68, parkName: "twin park",	address: "3145 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 69, parkName: "tyler",	address: "1501 CASTLEWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 70, parkName: "watterson lake",	address: "1714 SOUTH WHEATMORE DR",	city: "louisville", county: "jefferson", zipCode: "40215", visited: false, favorite: false,},
            {id: 71, parkName: "wayside",	address: "3190 SOUTH THIRD ST",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 72, parkName: "willow",	address:  "1402 WILLOW AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 73, parkName: "george rogers clark",	address: "1024 THRUSTON AVE",	city: "louisville", county: "jefferson", zipCode: "40217", visited: false, favorite: false,},
            {id: 74, parkName: "cherokee",	address: "745 COCHRAN HILL RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 75, parkName: "jefferson memorial forest",	address: "11311 MITCHELL HILL",	city: "fairdale", county: "jefferson", zipCode: "40118", visited: false, favorite: false,},
            {id: 76, parkName: "e. leland taylor",	address: "317 NORTH 38TH ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 77, parkName: "shawnee golf course",	address: "460 NORTHWESTERN PKWY",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 78, parkName: "william britt",	address: "2801 MAGAZINE ST",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 79, parkName: "portland wharf",	address: "719 NORTH 32ND ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 80, parkName: "portland",	address: "640 NORTH 27TH ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 81, parkName: "westonia",	 address: "2900 ROWAN ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 82, parkName: "highview",	address: "7201 OUTER LOOP",	city: "louisville", county: "jefferson", zipCode: "40228", visited: false, favorite: false,},
            {id: 83, parkName: "sheppard",	 address: "1601 MAGAZINE ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 84, parkName: "okolona",	address: "1114 CLAY AVE",	city: "louisville", county: "jefferson", zipCode: "40219", visited: false, favorite: false,},
            {id: 85, parkName: "crescent hill golf course",	address: "3110 BROWNSBORO RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 86, parkName: "farnsley",	address: "3100 WEDGEWOOD WAY", city: "louisville", county: "jefferson", zipCode: "40220", visited: false, favorite: false,},
            {id: 87, parkName: "crosby",	address: "11500 CEDARDALE RD", city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 88, parkName: "victory",	address: "1051 SOUTH 23RD ST", city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 89, parkName: "st louis",	address: "2023 ST LOUIS AVE", city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 90, parkName: "des pres",	address: "4709 LOWE RD", city: "louisville", county: "jefferson", zipCode: "40220", visited: false, favorite: false,},
            {id: 91, parkName: "ivy court",	 address: "3245 LARKWOOD AVE", city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 92, parkName: "long run golf course",	address: "1605 FLAT ROCK RD", city: "louisville", county: "jefferson", zipCode: "40245", visited: false, favorite: false,},
            {id: 93, parkName: "sun valley",	address: "6505 BETHANY LN", city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            {id: 94, parkName: "charlie vettiner golf course",	address: "10207 MARY DELL LN", city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 95, parkName: "waverly",	 address: "4800 WAVERLY park RD", city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 96, parkName: "charlie vettiner",	address: "5550 charlie vettiner park RD", city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 97, parkName: "iroquois",	address: "2120 RUNDILL RD", city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: true,},
            {id: 98, parkName: "seneca",	address: "3151 PEE WEE REESE RD",	city: "louisville", county: "jefferson", zipCode: "40205", visited: false, favorite: true,},
            {id: 99, parkName: "cherokee golf course",	address: "2501 ALEXANDER RD",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 100,	parkName: "thurman hutchins",	address: "3734 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 101,	parkName: "baxter square",	address: "301 SOUTH 12TH ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 102,	parkName: "long run",	address: "1605 FLAT ROCK RD",	city: "louisville", county: "jefferson", zipCode: "40245", visited: false, favorite: false,},
            {id: 103,	parkName: "auburndale",	address: "7260 SOUTHSIDE DR",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 104,	parkName: "ballard",	address: "525 CALDWELL ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: false, favorite: false,},
            {id: 105,	parkName: "berrytown",	address: "1300 HEAFER RD",	city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 106,	parkName: "black mudd",	address: "1708 RANGELAND RD",	city: "louisville", county: "jefferson", zipCode: "40219", visited: false, favorite: false,},
            {id: 107,	parkName: "blue lick",	address: "4114 MUD LN",	city: "louisville", county: "jefferson", zipCode: "40229", visited: false, favorite: false,},
            {id: 108,	parkName: "bobby nichols golf course",	 address: "4301 EAST PAGES LN",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 109,	parkName: "breslin",	address: "1388 LEXINGTON RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 110,	parkName: "churchill",	address: "2649 HELM ST",	city: "louisville", county: "jefferson", zipCode: "40209", visited: false, favorite: false,},
            {id: 111,	parkName: "fairmont falls",	address: "9800 THIXTON LN",	city: "louisville", county: "jefferson", zipCode: "40291", visited: false, favorite: false,},
            {id: 112,	parkName: "farman",	address: "100 FARMAN CT",	city: "louisville", county: "jefferson", zipCode: "40219", visited: false, favorite: false,},
            {id: 113,	parkName: "fern creek",	address: "8703 FERNDALE RD",	city: "louisville", county: "jefferson", zipCode: "40291", visited: false, favorite: false,},
            {id: 114,	parkName: "fisherman's",	address: "5607 OLD HEADY RD",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 115,	parkName: "joe creason",	address: "1297 TREVILIAN WAY",	city: "louisville", county: "jefferson", zipCode: "40213", visited: false, favorite: false,},
            {id: 116,	parkName: "lannan",	address: "901 NORTH 26TH ST",	city: "louisville", county: "jefferson", zipCode: "40212", visited: false, favorite: false,},
            {id: 117,	parkName: "petersburg",	address: "5008 EAST INDIAN TR",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 118,	parkName: "south central",	address: "2400 COLORADO AVE",	city: "louisville", county: "jefferson", zipCode: "40208", visited: false, favorite: false,},
            {id: 119,	parkName: "toonerville trolley",	address: "218 EAST OAK ST",	city: "louisville", county: "jefferson", zipCode: "40203", visited: true, favorite: false,},
            {id: 120,	parkName: "wyandotte",	address: "1104 BEECHER ST",	city: "louisville", county: "jefferson", zipCode: "40215", visited: false, favorite: false,},
            {id: 121,	parkName: "eva bandman",	address: "1701 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 122,	parkName: "beargrass creek greenway at irish hill",	address: "2001 LEXINGTON RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 123,	parkName: "WILLIAM B. STANSBURY",	address: "2302 SOUTH THIRD ST",	city: "louisville", county: "jefferson", zipCode: "40208", visited: false, favorite: false,},
            {id: 124,	parkName: "A.B. SAWYER",	address: "9300 WHIPPS MILL RD",	city: "louisville", county: "jefferson", zipCode: "40242", visited: false, favorite: false,},
            {id: 125,	parkName: "LOCUST GROVE",	address: "561 BLANKENBAKER LANE",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 126,	parkName: "BEECHMONT TOT LOT",	 address: "205 WEST WELLINGTON AVE",	city: "louisville", county: "jefferson", zipCode: "40214", visited: false, favorite: false,},
            {id: 127,	parkName: "CASTLEWOOD OPEN SPACE",	address: "1406 CASTLEWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40204", visited: false, favorite: false,},
            {id: 128,	parkName: "CALIFORNIA LEISURE OPEN SPACE",	address: "963 DIXIE HWY",	city: "louisville", county: "jefferson", zipCode: "40210", visited: false, favorite: false,},
            {id: 129,	parkName: "parkLAND PLAYGROUND",	address: "3200 GREENWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40211", visited: false, favorite: false,},
            {id: 130, parkName: "ROSE FARM",	address: "4500 ROSE FARM DR",	city: "louisville", county: "jefferson", zipCode: "40258", visited: false, favorite: false,},
            {id: 131,	parkName: "WATSON LANE TRAILHEAD",	address: "7600 WATSON LN",	city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            {id: 132,	parkName: "SCHUFF LANE GREENWAY",	address: "SCHUFF LANE",	city: "louisville", county: "jefferson", zipCode: "40205", visited: false, favorite: false,},
            {id: 133,	parkName: "CLIFTON HEIGHTS GREENWAY",	address: "620R N BIRCHWOOD AVE",	city: "louisville", county: "jefferson", zipCode: "40206", visited: true, favorite: false,},
            {id: 134,	parkName: "CYRIL ALLGEIER COMMUNITY CENTER",	address: "4101 CADILLAC CT",	city: "louisville", county: "jefferson", zipCode: "40213", visited: false, favorite: false,},
            {id: 135,	parkName: "BECKLEY CREEK park",	address: "1400 S BECKLEY STATION RD",	city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 136,	parkName: "PATRIOTS PEACE memorial",	address: "3742 UPPER RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 137,	parkName: "BUECHEL PARCEL",	address: "1029 SOUTHERN AVE",	city: "louisville", county: "jefferson", zipCode: "40218", visited: false, favorite: false,},
            {id: 138,	parkName: "MAHONEY",	address: "10903 BRENTLINGER",	city: "louisville", county: "jefferson", zipCode: "40291", visited: false, favorite: false,},
            {id: 139,	parkName: "PETERSON",	address: "15101 TAYLORSVILLE RD",	city: "fisherville", county: "jefferson", zipCode: "40023", visited: false, favorite: false,},
            {id: 140,	parkName: "jefferson memorial PARCEL 22",	address: "13111 MEDORA RD",	city: "louisville", county: "jefferson", zipCode: "40272", visited: false, favorite: false,},
            /*{id: 141,	parkName: "SOUTHERN parkWAY	 	", visited: false, favorite: false,},
            {id: 142,	parkName: EASTERN parkWAY	 	", visited: false, favorite: false,},
            {id: 143,	parkName: NORTHWESTERN parkWAY	 	", visited: false, favorite: false,},
            {id: 144,	parkName: SOUTHWESTERN parkWAY	 	", visited: false, favorite: false,},
            {id: 145,	parkName: ALGONQUIN parkWAY	 	", visited: false, favorite: false,},*/
            {id: 146,	parkName: "POPE LICK park",	address: "4002 South Pope Lick Rd",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 147,	parkName: "TURKEY RUN",	address: "8203 Stout Rd",	city: "louisville", county: "jefferson", zipCode: "40291", visited: false, favorite: true,},
            {id: 148,	parkName: "BROAD RUN",	address: "11551 Bardstown Rd",	city: "louisville", county: "jefferson", zipCode: "40291", visited: false, favorite: false,},
            {id: 149,	parkName: "A.B. SAWYER GREENWAY",	address: "1100 forest BRIDGE RD",	city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 150,	parkName: "louisville CHAMPIONS SOCCER",	address: "2100 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 151,	parkName: "louisville CHAMPIONS",	address: "2700 RIVER RD",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 152,	parkName: "GALVIN COURT",	address: "6100 GALVIN COURT",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 153,	parkName: "THE STRAND",	address: "6510 Echo Trail",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 154,	parkName: "QUAIL CHASE golf course", 	address: "7000 COOPER CHAPEL ROAD",	city: "louisville", county: "jefferson", zipCode: "40229", visited: false, favorite: false,},
            {id: 155,	parkName: "ARTHUR K. DRAUT park",	address: "4701 Bowling Blvd",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 156,	parkName: "Brown park",	address: "1000 Browns Lane",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 157,	parkName: "Community park",	address: "310 Ten Pin Lane",	city: "louisville", county: "jefferson", zipCode: "40207", visited: false, favorite: false,},
            {id: 158,	parkName: "Warwick park",	address: "521 Kentucky Ave",	city: "louisville", county: "jefferson", zipCode: "40222", visited: false, favorite: false,},
            {id: 159,	parkName: "Hal Warheim park",	address: "1832 Overlook Terrace",	city: "louisville", county: "jefferson", zipCode: "40205", visited: false, favorite: false,},
            {id: 160,	parkName: "ROBSION park",	address: "1 Robsion park Dr",	city: "louisville", county: "jefferson", zipCode: "40222", visited: false, favorite: false,},
            {id: 161,	parkName: "AUBURN park",	address: "9208 Auburn Ave",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 162,	parkName: "jeffersontown memorial park",	address: "10707 Taylorsville Rd",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 163,	parkName: "David L Armstrong Recreation Center",	address: "3015 Bluebird Lane",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 164,	parkName: "Skyview park",	address: "2700 Watterson Trail",	city: "louisville", county: "jefferson", zipCode: "40299", visited: false, favorite: false,},
            {id: 165,	parkName: "Plainview Swim Center",	address: "10235 Timberwood Circle",	city: "louisville", county: "jefferson", zipCode: "40223", visited: false, favorite: false,},
            {id: 166,	parkName: "Waterfront park",	address: "1101 River Rd",	city: "louisville", county: "jefferson", zipCode: "40206", visited: false, favorite: false,},
            {id: 167,	parkName: "Mount Washington  Community park",	address: "176 park View Ave",	city: "mount washingtion", county: "bullitt", zipCode: "40047", visited: false, favorite: false,},
            {id: 168,	parkName: "Lindsay Duvall park",	address: "100 Newman Way",	city: "mount washingtion", county: "bullitt", zipCode: "40047", visited: false, favorite: false,},
            {id: 169,	parkName: "Frank Cornell park",	address: "977 Waterford Rd",	city: "mount washingtion", county: "bullitt", zipCode: "40047", visited: true, favorite: false,},
            {id: 170,	parkName: "Maples park",	address: "6826 W Hwy 22",	city: "crestwood", county: "oldham", zipCode: "40014", visited: false, favorite: false,},
            {id: 171,	parkName: "Briar Hill park",	address: "7400 E Orchard Gras Blvd",	city: "crestwood", county: "oldham", zipCode: "40014", visited: false, favorite: false,},
            {id: 172,	parkName: "Wendell Moore park",	address: "1551 Hwy 393",	city: "la grange", county: "oldham", zipCode: "40031", visited: false, favorite: false,},
            {id: 173,	parkName: "Schamback park",	address: "6617 Main St",	city: "westport", county: "oldham", zipCode: "40077", visited: false, favorite: false,},
            {id: 174,	parkName: "Peggy E. Baker park",	address: "6887 Rte 2858",	city: "crestwood", county: "oldham", zipCode: "40014", visited: false, favorite: false,},
            {id: 175,	parkName: "Morgan Conservation park",	address: "1200 Kentucky 524",	city: "la grange", county: "oldham", zipCode: "40031", visited: false, favorite: false,},
            {id: 176,	parkName: "54 Acre Multi-Use park",	address: "3930 Highway 146",	city: "la grange", county: "oldham", zipCode: "40031", visited: false, favorite: false,},
            {id: 177,	parkName: "Celebration park",	address: "Apple Patch Way",	city: "crestwood", county: "oldham", zipCode: "40014", visited: false, favorite: false,},
            {id: 178,	parkName: "Creasey Mahan Nature Preserve",	address: "12501 Harmony Landing Rd",	city: "goshen", county: "oldham", zipCode: "40026", visited: false, favorite: false,},
            {id: 179,	parkName: "PeWee valley Central park",	address: "105 Central Avenue",	city: "pewee valley", county: "oldham", zipCode: "40056", visited: false, favorite: false,},
            {id: 180,	parkName: "Walsh park",	address: "600 North 4th St",	city: "la grange", county: "oldham", zipCode: "40031", visited: false, favorite: false,},
            {id: 181,	parkName: "Wilborn park",	address: "201 Lakeshore Dr",	city: "la grange", county: "oldham", zipCode: "40031", visited: false, favorite: false,},
            {id: 182,	parkName: "Shirley's Arbor",	address: "3501 Woehrle Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 183,	parkName: "Chapel Lake park",	address: "5801 New Chapel Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 184,	parkName: "Perrin Family park",	address: "414 Perrin Ln",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 185,	parkName: "Glossbrenner Public Garden",	address: "191 W Chestnut St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 186,	parkName: "Harmony park",	address: "1710 E 10th St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 187,	parkName: "Big 4 Station park",	address: "Big Four Pedestrian Bridge",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 188,	parkName: "jeffersonville Skate park",	address: "2107 Middle Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 189,	parkName: "Shirley Hall park",	address: "1203 Charlestown Pike",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: true, favorite: false,},
            {id: 190,	parkName: "Woehrle Athletic Complex",	address: "4200 Charlestown Pike",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 191,	parkName: "Riverstage",	address: "100 W Riverside Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 192,	parkName: "Nachand Fieldhouse",	address: "601 E Court Ave",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 193,	parkName: "jeffersonville Aquatic Center",	address: "2107 Middle Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 194,	parkName: "Veterans memorial park",	address: "301 Mulberry St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 195,	parkName: "W.F. Throckmorton park",	address: "44 Beechwood Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 196,	parkName: "Samuel G. Shannon memorial park",	address: "501 Crestview Ct",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 197,	parkName: "Richard L. Vissing park",	address: "2728 Vissing park Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 198,	parkName: "Highland Dog park",	address: "1300 Spruce Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 199,	parkName: "John Wilcoxson park",	address: "44 Beechwood Rd",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 200,	parkName: "Ricard B. Wathen park",	address: "29 Regina Ave",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 201,	parkName: "Luther F. Warder park",	address: "109 E Court Ave",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 202,	parkName: "Steamboat park",	address: "320 Division St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 203,	parkName: "S. Harlan Vogt park",	address: "133 E park Pl",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 204,	parkName: "Preservation park",	address: "120 W Market St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 205,	parkName: "Port Fulton park	201 W High St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 206,	parkName: "Poppy park",	address: "2100 Poppy Pl",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 207,	parkName: "Meadows park",	address: "4503 Fallow Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 208,	parkName: "Lottie Oglesby park",	address: "610 Martha Ave",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 209,	parkName: "Kyle Vissing park",	address: "22 forest Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 210,	parkName: "Pamela J Inman park",	address: "2128 Robin Ln",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 211,	parkName: "Henry Landsen park",	address: "201 E 15th St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 212,	parkName: "Gaither park",	address: "1499 E 8th St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 213,	parkName: "forest park",	address: "140 forest Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 214,	parkName: "James T. Duffy's Landing",	address: "2610 Utica Pike",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 215,	parkName: "Connie Sellmer park",	address: "1904 Oakridge Dr",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 216,	parkName: "Bob Hedge park",	address: "926 French St",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: true,},
            {id: 217,	parkName: "Allison Brook park",	address: "1701 Allison Ln",	city: "jeffersonville", county: "clark", zipCode: "47130", visited: false, favorite: false,},
            {id: 218,	parkName: "Ashland park",	address: "430 E Riverside Dr",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 219,	parkName: "Beechwood park",	address: "1200 Beechwood Dr",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 220,	parkName: "Cedar park",	address: "1630 Horn St",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 221,	parkName: "Colgate park",	address: "800 S clark Blvd",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 222,	parkName: "Gaskell park",	address: "1629 Briarwood Dr",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 223,	parkName: "Gateway park",	address: "500 Little League Blvd",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: true,},
            {id: 224,	parkName: "Lapping park",	address: "2404 Greentree N",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 225,	parkName: "Lewis and clark park",	address: "1240 harrison Ave",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 226,	parkName: "parkwood park",	address: "1415 Kilmer Way",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 227,	parkName: "Ray Lawrence park",	address: "1021 Irving Dr",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 228,	parkName: "Anderson park",	address: "711 Hildreth St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 229,	parkName: "Bicknell park",	address: "315 Silver St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 230,	parkName: "Billy Herman park",	address: "600 Scribner Dr",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 231,	parkName: "Binford park",	address: "1701 Graybrook Lane",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 232,	parkName: "Cannon Acres Soccer Field",	address: "1935 Budd Rd",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 233,	parkName: "Cherry valley golf course",	address: "	",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 234,	parkName: "Divison Street",	address: "1728 Division St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 235,	parkName: "Fairmont park",	address: "1725 Abbie Dell",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 236,	parkName: "Griffin Recreation Center",	address: "1140 Griffin Street",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 237,	parkName: "Joe Kraft park",	address: "500 W 7th St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 238,	parkName: "Millerwood park",	address: "1759 Millerwood Dr",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 239,	parkName: "new albany Dog park",	address: "1935 Budd Rd",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 240,	parkName: "Ritter park",	address: "1218 Culbertson Ave",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 241,	parkName: "River Run Family Waterpark",	address: "224 W Daisy Ln",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 242,	parkName: "Sertoma park",	address: "1315 Mill Ln",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 243,	parkName: "Silver Street park",	address: "2043 Silver St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 244,	parkName: "valley View Golf park",	address: "3748 Lawrence Banet Rd",	city: "new albany", county: "floyd", zipCode: "47119", visited: false, favorite: false,},
            {id: 245,	parkName: "Bicentennial park",	address: "118 E Spring St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 246,	parkName: "Riverfront Amphitheater",	address: "290 E Water St",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 247,	parkName: "Campbell Woodland Nature Trails",	address: "3500 Budd Rd",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 248,	parkName: "Galena-Lamb park",	address: "6220 Highway 150",	city: "new albany", county: "floyd", zipCode: "47119", visited: false, favorite: false,},
            {id: 249,	parkName: "Garry E. Cavan park",	address: "6485 corydon Ridge Rd",	city: "new albany", county: "floyd", zipCode: "47122", visited: false, favorite: false,},
            {id: 250,	parkName: "Greenville park",	address: "6455 Buttontown Rd",	city: "new albany", county: "floyd", zipCode: "47124", visited: false, favorite: false,},
            {id: 251,	parkName: "Herman Collier park",	address: "3905 Fiske Ave",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 252,	parkName: "Letty Walter park",	address: "5345 Saint Mary's Rd",	city: "new albany", county: "floyd", zipCode: "47119", visited: false, favorite: false,},
            {id: 253,	parkName: "Kevin Hammersmith memorial park",	address: "440 Lewis Endres parkway",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 254,	parkName: "Sam Peden Community park",	address: "3037 Grant Line Rd",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 255,	parkName: "Southern IN Sports Center",	address: "620 park East Blvd",	city: "new albany", county: "floyd", zipCode: "47150", visited: false, favorite: false,},
            {id: 256,	parkName: "Falls of the Ohio State park",	address: "201 W. Riverside Dr",	city: "clarksville", county: "clark", zipCode: "47129", visited: false, favorite: false,},
            {id: 257,	parkName: "Deam Lake State Recreation Area",	address: "1217 Deam Lake Rd off Hwy 60", city: "borden", county: "clark",	zipCode: "47106", visited: false, favorite: false,},
            {id: 258,	parkName: "Charlestown State park",	address: "12500 Indiana 62", city: "charlestown", county: "clark",	zipCode: "47111", visited: false, favorite: false,},
            {id: 259,	parkName: "clark State forest",	address: "PO BOX 119", city: "henryville", county: "clark",	zipCode: "47126", visited: false, favorite: false,},
            {id: 260,	parkName: "harrison-Crawford State forest",	address: "7240 Old forest Road SW", city: "corydon", county: "harrison",	zipCode: "47112", visited: false, favorite: false,},
            {id: 261,	parkName: "O'Bannon Woods State park",	address: "7234 Old forest Road SW", city: "corydon", county: "harrison",	zipCode: "47112", visited: false, favorite: false,},
            {id: 262,	parkName: "Hayswood Nature Reserve",	address: "755 Hwy 135 NW", city: "corydon", county: "harrison",	zipCode: "47112", visited: false, favorite: false,},
            {id: 263,	parkName: "Rhoads Pool",	address: "2105 Poolside Dr NW", city: "corydon", county: "harrison",	zipCode: "47112", visited: false, favorite: false,},
            {id: 264,	parkName: "South harrison",	address: "8750 South harrison park Dr SE", city: "laconia", county: "harrison",	zipCode: "47135", visited: false, favorite: false,},
            {id: 265,	parkName: "Buffalo Trace",	address: "1540 HWY 150 NE", city: "palmyra", county: "harrison",	zipCode: "47164", visited: false, favorite: false,},
            {id: 266,	parkName: "Noe's",	address: "12825 HWY 111 SE", city: "elizabeth", county: "harrison",	zipCode: "47117", visited: false, favorite: false,},
            {id: 267,	parkName: "Gresham",	address: "7570 Main St NE", city: "lanesville", county: "harrison",	zipCode: "47136", visited: false, favorite: false,},
            {id: 268,	parkName: "Battle of corydon",	address: "100 Old Hwy 135 SW", city: "corydon", county: "harrison",	zipCode: "47112", visited: false, favorite: false,},
            {id: 269,	parkName: "The Hubbard House",	address: "1553 Old State Rd 64 NE", city: "new salisbury", county: "harrison",	zipCode: "47161", visited: false, favorite: false,},
            {id: 270,	parkName: "Morvin's Landing",	address: "12982 Morvin's Landing Road", city: "mauckport", county: "harrison",	zipCode: "47142", visited: false, favorite: false,},
            {id: 271,	parkName: "The Overlook park",	address: "2397 Overlook Dr SW", city: "mauckport", county: "harrison",	zipCode: "47142", visited: false, favorite: false,},
            {id: 272,	parkName: "Lebanon Junction memorial park",	address: "423 S Poplar St", city: "lebanon junction", county: "bullitt",	zipCode: "40150", visited: false, favorite: false,},
            {id: 273,	parkName: "Clear Creek park",	address: "717 Burks Branch",	city: "shelbyville", county: "shelby", zipCode: "40065", visited: false, favorite: false,},
            {id: 274,	parkName: "Red Orchard park",	address: "704 Kentucky St",	city: "shelbyville", county: "shelby", zipCode: "40065", visited: false, favorite: false,},
            {id: 275,	parkName: "shelby trails park",	address: "5063 Aiken Road",	city: "simpsonville", county: "shelby", zipCode: "40067", visited: false, favorite: false,},
            {id: 276,	parkName: "finchville park",	address: "5311 Taylorsville Rd",	city: "finchville", county: "shelby", zipCode: "40022", visited: false, favorite: false,},
            {id: 277,	parkName: "shelbyville Skate park",	address: "1145 Washington St",	city: "shelbyville", county: "shelby", zipCode: "40065", visited: false, favorite: false,},
            {id: 278,	parkName: "shelbyville Greeenway Trail",	address: "97 7th St",	city: "shelbyville", county: "shelby", zipCode: "40065", visited: false, favorite: false,},
            {id: 279,	parkName: "lake shelby park and campground",	address: "1433 Burks Branch Rd",	city: "shelbyville", county: "shelby", zipCode: "40065", visited: false, favorite: false,},
            {id: 280,	parkName: "battletown park",	address: "75 Lawson Creek Rd",	city: "battletown", county: 'meade',  zipCode: "40104", visited: false, favorite: false,},
            {id: 281,	parkName: "brandenburg riverfront park",	address: "Main Street",city: "brandenburg", county: "meade",	zipCode: "40108", visited: false, favorite: false,},
            {id: 282,	parkName: "buttermilk falls trail",	address: "	",city: "brandenburg", county: "meade",	zipCode: "40108", visited: false, favorite: false,},
            {id: 283,	parkName: "concordia park",	address: " ", city: 'concordia', county: 'meade', zipCode: "40157", visited: false, favorite: false,},
            {id: 284,	parkName: "dianna's park",	address: "515 Broadway", city: "brandenburg", county: "meade",	zipCode: "40108", visited: false, favorite: false,},
            {id: 285,	parkName: "flaherty community park",	address: "", city: 'flaherty', county: 'meade', zipCode: "40175", visited: false, favorite: false,},
            {id: 286,	parkName: "meade-olin park",	address: "163 Moremen Rd", city: "brandenburg",county: 'meade',	zipCode: "40108", visited: false, favorite: false,},
            {id: 287,	parkName: "otter creek recreation area",	address: "850 Otter Creek park Rd", city: "brandenburg", county: "meade", zipCode: "40108", visited: false, favorite: false,},		
            //{id: 288,	parkName: "Wolf Creek park",	address: "", zipCode: "", visited: false, favorite: false,},		
            {id: 289,	parkName: "ymca camp piomingo",	address: "1950 Otter Creek park Rd", city: "brandenburg", county: "meade", zipCode: "40108", visited: false, favorite: false,}, 				
            {id: 290,	parkName: "bernheim arboretum and research forest",	address: "2075 Clermont Rd", city: "clermont", county: "bullitt", zipCode: "40110", visited: false, favorite: false,},
            {id: 291, parkName: "waterford community park", address: "", city: "taylorsville", county: "spencer", zipCode: " ", visited: false, favorite: false,},
            {id: 291, parkName: "ray jewell park", address: "", city: "taylorsville", county: "spencer", zipCode: " ", visited: false, favorite: false,},
            {id: 291, parkName: "taylorsville lake state park", address: "", city: "taylorsville", county: "spencer", zipCode: " ", visited: false, favorite: false,},
            {id: 291, parkName: "spencer county fairgrounds", address: "895 Fairgrounds Rd", city: "taylorsville", county: "spencer", zipCode: "40071", visited: false, favorite: false,},	       
]
const parkNames = [];
for (i in parks) {
    let pName = parks[i].parkName
    parkNames.push(pName)
}
const cities = [];
for (i in parks) {
    let cityName = parks[i].city
    if (cities.includes(cityName) !== true) {
    cities.push(cityName)
 }
}
console.log(cities)

const counties = [];
for (i in parks) {
    let countyName = parks[i].county
    if (counties.includes(countyName) !== true) {
        counties.push(countyName)
    }
}
console.log(counties)

const zipCodes = [];
for (i in parks) {
    let zipCodeNumber = parks[i].zipCode
    if (zipCodes.includes(zipCodeNumber) !== true) {
        zipCodes.push(zipCodeNumber)
    }
}
const masterList = [];

for (i in parks) {
    let pName = parks[i].parkName
    masterList.push(pName)
}
for (i in parks) {
    let cityName = parks[i].city
    if (masterList.includes(cityName) !== true ) {
        masterList.push(cityName)
    } 
}

for (i in parks) {
    let countyName = parks[i].county
    if (masterList.includes(countyName) !== true) {
        masterList.push(countyName)
    }
}
for (i in parks) {
    let zipCodeNumber = parks[i].zipCode
    if (masterList.includes(zipCodeNumber) !== true) {
        masterList.push(zipCodeNumber)
    }
}
console.log(masterList)