const app = new Vue ({
	el: '#app',
	data() {
		return {
			selectedPark: "",
            selectedZipCode: "40202",
            parks: [
			{id: 1,	parkName: '35TH STREET', 	address: "814 SOUTH 35TH ST",	zipCode: "40211", visited: false,},
            {id: 2,	parkName: "CRESCENT HILL",	address: "3110 BROWNSBORO RD",	zipCode: "40206", visited: false,},
            {id: 3, parkName: "ALGONQUIN",	address: "1614 CYPRESS ST",	zipCode: "40210", visited: false,},
            {id: 4, parkName: "BELLEVUE",	address: "4711 BELLEVUE AVE",	zipCode: "40215", visited: false,},
            {id: 5, parkName: "BEN WASHER",	address: "519 WEST KENTUCKY ST",	zipCode: "40203", visited: false,},
            {id: 6, parkName: "BINGHAM",	address: " 160 CORAL AVE",	zipCode: "40206", visited: false,},
            {id: 7, parkName: "BRADLEY",	address: "2516 BRADLEY AVE",	zipCode: "40217", visited: false,},
            {id: 8, parkName: "BUECHEL",	address: "247 ALPHA AVE",	zipCode: "40218", visited: false,},
            {id: 9, parkName: "CAMP TAYLOR",	address: "4201 LEE AVE",	zipCode: "40213", visited: false,},
            {id: 10, parkName: "CANE RUN",	address: "4816 CANE RUN RD", zipCode: "40216", visited: false,},
            {id: 11, parkName: "CAPERTON SWAMP",	address: "3916 RIVER RD",	zipCode: "40207", visited: false,},
            {id: 12, parkName: "CENTRAL",	address: "1340 SOUTH FOURTH ST", zipCode: "40208", visited: false,},
            {id: 13, parkName: "CHICKASAW",	address: "1200 SOUTHWESTERN PKWY",	zipCode: "40211", visited: false,},
            {id: 14, parkName: "CLIFF",	address: "4666 CLIFF AVE",	zipCode: "40215", visited: false,},
            {id: 15, parkName: "CLIFTON", address: "133 NORTH CHARLTON ST",	zipCode: "40206", visited: false,},
            {id: 16, parkName: "CARRIE GAULBERT COX",	address: "3730 RIVER RD",	zipCode: "40207", visited: false,},
            {id: 17, parkName: "DOUGLASS",	address: "2305 DOUGLASS BLVD",	zipCode: "40205", visited: false,},
            {id: 18, parkName: "EASTOVER",	address: "118 SACRED HEART LN",	zipCode: "40206", visited: false,},
            {id: 19, parkName: "FAIRDALE MINI", address: "10714 WEST MANSLICK RD",	zipCode: "40118", visited: false,},
            {id: 20, parkName: "FLAGET FIELD",	address: "4425 GREENWOOD AVE",	zipCode: "40211", visited: false,},
            {id: 21, parkName: "GERMAN-PARISTOWN",	address: "1134 EAST KENTUCKY ST",	zipCode: "40204", visited: false,},
            {id: 22, parkName: "GNADINGER", address: "103 ELLISON AVE",	zipCode: "40204", visited: false,},
            {id: 23, parkName: "WILLIAM HARRISON",	address: "3232 OLEANDA AVE",	zipCode: "40215", visited: false,},
            {id: 24, parkName: "HOPEWELL",	address: "509 NORTH BIRCHWOOD AVE",	zipCode: "40206", visited: false,},
            {id: 25, parkName: "NELSON HORNBECK",	address: "709 FAIRDALE RD",	zipCode: "40118", visited: false,},
            {id: 26, parkName: "HOUNZ LANE",	address: "2300 HOUNZ LN",	zipCode: "40223", visited: false,},
            {id: 27, parkName: "IRISH HILL",	address: "1131 LEXINGTON RD",	zipCode: "40204", visited: false,},
            {id: 28, parkName: "LOUIS B. ISRAEL", address: "4708 SOUTH FIRST ST",	zipCode: "40214", visited: false,},
            {id: 29, parkName: "HAYS KENNEDY",	address: "7303 BEACHLAND BEACH RD",	zipCode: "40059", visited: false,},
            {id: 30, parkName: "KENNEDY COURT",	address: "225 KENNEDY AVE",	zipCode: "40206", visited: false,},
            {id: 31, parkName: "KLONDIKE",	address: "3809 KLONDIKE LN",	zipCode: "40218", visited: false,},
            {id: 32, parkName: "LAKE DREAMLAND", address: "4400 LAKE DREAMLAND RD",	zipCode: "40216", visited: false,},
            {id: 34, parkName: "SENECA GOLF COURSE",	 address: "2300 PEE WEE REESE RD",	zipCode: "40205", visited: false,},
            {id: 35, parkName: "CHARLES YOUNG",	address: "2721 LYTLE ST",	zipCode: "40212", visited: false,},
            {id: 36, parkName: "ROBERSON RUN",	address: "8205 JUDGE BLVD",	zipCode: "40219", visited: false,},
            {id: 37, parkName: "IROQUOIS GOLF COURSE",	address: "1501 RUNDILL RD",	zipCode: "40214", visited: false,},
            {id: 38, parkName: "NORFOLK ACRES",	address: "4300 CORAM WAY",	zipCode: "40218", visited: false,},
            {id: 39, parkName: "CALIFORNIA",	address: "1104 SOUTH 16TH ST",	zipCode: "40210", visited: false,},
            {id: 40, parkName: "SUN VALLEY GOLF COURSE", address: "6505 BETHANY LN",	zipCode: "40272", visited: false,},
            {id: 41, parkName: "LAPORTE",	address: "2529 BANK ST",	zipCode: "40212", visited: false,},
            {id: 42, parkName: "ELLIOT SQUARE",	address: "630 SOUTH 28TH ST",	zipCode: "40211", visited: false,},
            {id: 43, parkName: "EMERSON",	address: "1100 SYLVIA ST",	zipCode: "40217", visited: false,},
            {id: 44, parkName: "MCNEELY LAKE",	address: "10500 CEDAR CREEK RD",	zipCode: "40229", visited: false,},
            {id: 45, parkName: "BOONE SQUARE",	address: "1935 ROWAN ST",	zipCode: "40203", visited: false,},
            {id: 46, parkName: "OLD WALNUT / BEECHER",	address: "904 WEST MUHAMMAD ALI BLVD",	zipCode: "40203", visited: false,},
            {id: 47, parkName: "SLEVIN",	address: "341 NORTH 25TH ST",	zipCode: "40212", visited: false,},
            {id: 48, parkName: "RUSSELL LEE",	address: "3701 SOUTHERN AVE",	zipCode: "40211", visited: false,},	 	
            {id: 50, parkName: "DAVID ARMSTRONG EXTREME", address: "148 NORTH CLAY ST",	zipCode: "40202", visited: false,},
            {id: 51, parkName: "MAGNOLIA", address: "1407 SOUTH SECOND ST",	zipCode: "40208", visited: false,},
            {id: 52, parkName: "MEDORA",	address: "6210 PENDLETON RD",	zipCode: "40272", visited: false,},
            {id: 53, parkName: "MEMORIAL",	address: "971 SOUTH FOURTH ST",	zipCode: "40203", visited: false,},
            {id: 54, parkName: "G.G. MOORE",	address: "626 M ST",	zipCode: "40208", visited: false,},
            {id: 55, parkName: "PARKHILL",	address: "1703 SOUTH 13TH ST",	zipCode: "40210", visited: false,},
            {id: 56, parkName: "PATTERSON",	address: "1418 MORTON AVE",	zipCode: "40204", visited: false,},
            {id: 57, parkName: "PEEWEE",	address: "2913 KLONDIKE LN",	zipCode: "40218", visited: false,},
            {id: 58, parkName: "HUSTON QUIN",	address: "4105 SOUTH FIRST ST",	zipCode: "40214", visited: false,},
            {id: 59, parkName: "GINNY REICHARD",	address: "1001 FRANKLIN ST",	zipCode: "40206", visited: false,},
            {id: 60, parkName: "RIVERSIDE GARDENS",	address: "2899 LEES LN",	zipCode: "40216", visited: false,},
            {id: 61, parkName: "RIVERVIEW",	address: "8202 GREENWOOD RD",	zipCode: "40258", visited: false,},
            {id: 62, parkName: "RIVERSIDE, THE FARNSLEY-MOREMAN LANDING",	address: "7410 MOORMAN RD",	zipCode: "40272", visited: false,},
            {id: 63, parkName: "RUBEL", address: "667 BARRET AVE",	zipCode: "40204", visited: false,},
            {id: 64, parkName: "SHAWNEE",	address: "4501 WEST BROADWAY",	zipCode: "40211", visited: false,},
            {id: 65, parkName: "SHELBY",	address: "600 EAST OAK ST",	zipCode: 40203, visited: false,},
            {id: 66, parkName: "STORY AVENUE",	address: "1531 STORY AVE",	zipCode: 40206, visited: false,},
            {id: 67, parkName: "SYLVANIA",	address: "6650 SYLVANIA RD",	zipCode: 40258, visited: false,},
            {id: 68, parkName: "TWIN PARK",	address: "3145 RIVER RD",	zipCode: 40207, visited: false,},
            {id: 69, parkName: "TYLER",	address: "1501 CASTLEWOOD AVE",	zipCode: 40204, visited: false,},
            {id: 70, parkName: "WATTERSON LAKE",	address: "1714 SOUTH WHEATMORE DR",	zipCode: 40215, visited: false,},
            {id: 71, parkName: "WAYSIDE",	address: "3190 SOUTH THIRD ST",	zipCode: 40214, visited: false,},
            {id: 72, parkName: "WILLOW",	address:  "1402 WILLOW AVE",	zipCode: 40204, visited: false,},
            {id: 73, parkName: "GEORGE ROGERS CLARK",	address: "1024 THRUSTON AVE",	zipCode: 40217, visited: false,},
            {id: 74, parkName: "CHEROKEE",	address: "745 COCHRAN HILL RD",	zipCode: 40206, visited: false,},
            {id: 75, parkName: "JEFFERSON MEMORIAL FOREST",	address: "11311 MITCHELL HILL",	zipCode: 40118, visited: false,},
            {id: 76, parkName: "E. LELAND TAYLOR",	address: "317 NORTH 38TH ST",	zipCode: 40212, visited: false,},
            {id: 77, parkName: "SHAWNEE GOLF COURSE",	address: "460 NORTHWESTERN PKWY",	zipCode: 40212, visited: false,},
            {id: 78, parkName: "WILLIAM BRITT",	address: "2801 MAGAZINE ST",	zipCode: 40211, visited: false,},
            {id: 79, parkName: "PORTLAND WHARF",	address: "719 NORTH 32ND ST",	zipCode: 40212, visited: false,},
            {id: 80, parkName: "PORTLAND",	address: "640 NORTH 27TH ST",	zipCode: 40212, visited: false,},
            {id: 81, parkName: "WESTONIA",	 address: "2900 ROWAN ST",	zipCode: 40212, visited: false,},
            {id: 82, parkName: "HIGHVIEW",	address: "7201 OUTER LOOP",	zipCode: 40228, visited: false,},
            {id: 83, parkName: "SHEPPARD",	 address: "1601 MAGAZINE ST",	zipCode: 40203, visited: false,},
            {id: 84, parkName: "OKOLONA",	address: "1114 CLAY AVE",	zipCode: 40219, visited: false,},
            {id: 85, parkName: "CRESCENT HILL GOLF COURSE",	address: "3110 BROWNSBORO RD",	zipCode: 40206, visited: false,},
            {id: 86, parkName: "FARNSLEY",	address: "3100 WEDGEWOOD WAY", zipCode: 40220, visited: false,},
            {id: 87, parkName: "CROSBY",	address: "11500 CEDARDALE RD", zipCode: 40223, visited: false,},
            {id: 88, parkName: "VICTORY",	address: "1051 SOUTH 23RD ST", zipCode: 40210, visited: false,},
            {id: 89, parkName: "ST LOUIS",	address: "2023 ST LOUIS AVE", zipCode: 40210, visited: false,},
            {id: 90, parkName: "DES PRES",	address: "4709 LOWE RD", zipCode: 40220, visited: false,},
            {id: 91, parkName: "IVY COURT",	 address: "3245 LARKWOOD AVE", zipCode: 40212, visited: false,},
            {id: 92, parkName: "LONG RUN GOLF COURSE",	address: "1605 FLAT ROCK RD", zipCode: 40245, visited: false,},
            {id: 93, parkName: "SUN VALLEY",	address: "6505 BETHANY LN", zipCode: 40272, visited: false,},
            {id: 94, parkName: "CHARLIE VETTINER GOLF COURSE",	address: "10207 MARY DELL LN", zipCode: 40299, visited: false,},
            {id: 95, parkName: "WAVERLY",	 address: "4800 WAVERLY PARK RD", zipCode: 40214, visited: false,},
            {id: 96, parkName: "CHARLIE VETTINER",	address: "5550 CHARLIE VETTINER PARK RD", zipCode: 40299, visited: false,},
            {id: 97, parkName: "IROQUOIS",	address: "2120 RUNDILL RD", zipCode: 40214, visited: false,},
            {id: 98, parkname: "SENECA",	address: "3151 PEE WEE REESE RD",	zipCode: "40205", visited: false,},
            {id: 99, parkName: "CHEROKEE GOLF COURSE",	address: "2501 ALEXANDER RD",	zipCode: "40204", visited: false,},
            {id: 100,	parkName: "THURMAN HUTCHINS",	address: "3734 RIVER RD",	zipCode: "40207", visited: false,},
            {id: 101,	parkName: "BAXTER SQUARE",	address: "301 SOUTH 12TH ST",	zipCode: "40203", visited: false,},
            {id: 102,	parkName: "LONG RUN",	address: "1605 FLAT ROCK RD",	zipCode: "40245", visited: false,},
            {id: 103,	parkName: "AUBURNDALE",	address: "7260 SOUTHSIDE DR",	zipCode: "40214", visited: false,},
            {id: 104,	parkName: "BALLARD",	address: "525 CALDWELL ST",	zipCode: "40203", visited: false,},
            {id: 105,	parkName: "BERRYTOWN",	address: "1300 HEAFER RD",	zipCode: "40223", visited: false,},
            {id: 106,	parkName: "BLACK MUDD",	address: "1708 RANGELAND RD",	zipCode: "40219", visited: false,},
            {id: 107,	parkName: "BLUE LICK",	address: "4114 MUD LN",	zipCode: "40229", visited: false,},
            {id: 108,	parkName: "BOBBY NICHOLS GOLF COURSE",	 address: "4301 EAST PAGES LN",	zipCode: "40214", visited: false,},
            {id: 109,	parkName: "BRESLIN",	address: "1388 LEXINGTON RD",	zipCode: "40206", visited: false,},
            {id: 110,	parkName: "CHURCHILL",	address: "2649 HELM ST",	zipCode: "40209", visited: false,},
            {id: 111,	parkName: "FAIRMONT FALLS",	address: "9800 THIXTON LN",	zipCode: "40291", visited: false,},
            {id: 112,	parkName: "FARMAN",	address: "100 FARMAN CT",	zipCode: "40219", visited: false,},
            {id: 113,	parkName: "FERN CREEK",	address: "8703 FERNDALE RD",	zipCode: "40291", visited: false,},
            {id: 114,	parkName: "FISHERMAN'S",	address: "5607 OLD HEADY RD",	zipCode: "40299", visited: false,},
            {id: 115,	parkName: "JOE CREASON",	address: "1297 TREVILIAN WAY",	zipCode: "40213", visited: false,},
            {id: 116,	parkName: "LANNAN",	address: "901 NORTH 26TH ST",	zipCode: "40212", visited: false,},
            {id: 117,	parkName: "PETERSBURG",	address: "5008 EAST INDIAN TR",	zipCode: "40218", visited: false,},
            {id: 118,	parkName: "SOUTH CENTRAL",	address: "2400 COLORADO AVE",	zipCode: "40208", visited: false,},
            {id: 119,	parkName: "TOONERVILLE TROLLEY",	address: "218 EAST OAK ST",	zipCode: "40203", visited: false,},
            {id: 120,	parkName: "WYANDOTTE",	address: "1104 BEECHER ST",	zipCode: "40215", visited: false,},
            {id: 121,	parkName: "EVA BANDMAN",	address: "1701 RIVER RD",	zipCode: "40206", visited: false,},
            {id: 122,	parkName: "BEARGRASS CREEK GREENWAY AT IRISH HILL",	address: "2001 LEXINGTON RD",	zipCode: "40206", visited: false,},
            {id: 123,	parkName: "WILLIAM B. STANSBURY",	address: "2302 SOUTH THIRD ST",	zipCode: "40208", visited: false,},
            {id: 124,	parkName: "A.B. SAWYER",	address: "9300 WHIPPS MILL RD",	zipCode: "40242", visited: false,},
            {id: 125,	parkName: "LOCUST GROVE",	address: "561 BLANKENBAKER LANE",	zipCode: "40207", visited: false,},
            {id: 126,	parkName: "BEECHMONT TOT LOT",	 address: "205 WEST WELLINGTON AVE",	zipCode: "40214", visited: false,},
            {id: 127,	parkName: "CASTLEWOOD OPEN SPACE",	address: "1406 CASTLEWOOD AVE",	zipCode: "40204", visited: false,},
            {id: 128,	parkName: "CALIFORNIA LEISURE OPEN SPACE",	address: "963 DIXIE HWY",	zipCode: "40210", visited: false,},
            {id: 129,	parkName: "PARKLAND PLAYGROUND",	address: "3200 GREENWOOD AVE",	zipCode: "40211", visited: false,},
            {id: 130, parkName: "ROSE FARM",	address: "4500 ROSE FARM DR",	zipCode: "40258", visited: false,},
            {id: 131,	parkName: "WATSON LANE TRAILHEAD",	address: "7600 WATSON LN",	zipCode: "40272", visited: false,},
            {id: 132,	parkName: "SCHUFF LANE GREENWAY",	address: "SCHUFF LANE",	zipCode: "40205", visited: false,},
            {id: 133,	parkName: "CLIFTON HEIGHTS GREENWAY",	address: "620R N BIRCHWOOD AVE",	zipCode: "40206", visited: false,},
            {id: 134,	parkName: "CYRIL ALLGEIER COMMUNITY CENTER",	address: "4101 CADILLAC CT",	zipCode: "40213", visited: false,},
            {id: 135,	parkName: "BECKLEY CREEK PARK",	address: "1400 S BECKLEY STATION RD",	zipCode: "40223", visited: false,},
            {id: 136,	parkName: "PATRIOTS PEACE MEMORIAL",	address: "3742 UPPER RIVER RD",	zipCode: "40207", visited: false,},
            {id: 137,	parkName: "BUECHEL PARCEL",	address: "1029 SOUTHERN AVE",	zipCode: "40218", visited: false,},
            {id: 138,	parkName: "MAHONEY",	address: "10903 BRENTLINGER",	zipCode: "40291", visited: false,},
            {id: 139,	parkName: "PETERSON",	address: "15101 TAYLORSVILLE RD",	zipCode: "40023", visited: false,},
            {id: 140,	parkName: "JEFFERSON MEMORIAL PARCEL 22",	address: "13111 MEDORA RD",	zipCode: "40272", visited: false,},
            /*{id: 141,	parkName: "SOUTHERN PARKWAY	 	", visited: false,},
            {id: 142,	parkName: EASTERN PARKWAY	 	", visited: false,},
            {id: 143,	parkName: NORTHWESTERN PARKWAY	 	", visited: false,},
            {id: 144,	parkName: SOUTHWESTERN PARKWAY	 	", visited: false,},
            {id: 145,	parkName: ALGONQUIN PARKWAY	 	", visited: false,},*/
            {id: 146,	parkName: "POPE LICK PARK",	address: "4002 South Pope Lick Rd",	zipCode: "40299", visited: false,},
            {id: 147,	parkName: "TURKEY RUN",	address: "8203 Stout Rd",	zipCode: "40291", visited: false,},
            {id: 148,	parkName: "BROAD RUN",	address: "11551 Bardstown Rd",	zipCode: "40291", visited: false,},
            {id: 149,	parkName: "A.B. SAWYER GREENWAY",	address: "1100 FOREST BRIDGE RD",	zipCode: "40223", visited: false,},
            {id: 150,	parkName: "LOUISVILLE CHAMPIONS SOCCER",	address: "2100 RIVER RD",	zipCode: "40206", visited: false,},
            {id: 151,	parkName: "LOUISVILLE CHAMPIONS",	address: "2700 RIVER RD",	zipCode: "40206", visited: false,},
            {id: 152,	parkName: "GALVIN COURT",	address: "6100 GALVIN COURT",	zipCode: "40299", visited: false,},
            {id: 153,	parkName: "THE STRAND",	address: "6510 Echo Trail",	zipCode: "40299", visited: false,},
            {id: 154,	parkName: "QUAIL CHASE GOLF COURSE", 	address: "7000 COOPER CHAPEL ROAD",	zipCode: "40229", visited: false,},
            {id: 155,	parkName: "ARTHUR K. DRAUT PARK",	address: "4701 Bowling Blvd",	zipCode: "40207", visited: false,},
            {id: 156,	parkName: "Brown Park",	address: "1000 Browns Lane",	zipCode: "40207", visited: false,},
            {id: 157,	parkName: "Community Park",	address: "310 Ten Pin Lane",	zipCode: "40207", visited: false,},
            {id: 158,	parkName: "Warwick Park",	address: "521 Kentucky Ave",	zipCode: "40222", visited: false,},
            {id: 159,	parkName: "Hal Warheim Park",	address: "1832 Overlook Terrace",	zipCode: "40205", visited: false,},
            {id: 160,	parkName: "ROBSION Park",	address: "1 Robsion Park Dr",	zipCode: "40222", visited: false,},
            {id: 161,	parkName: "AUBURN PARK",	address: "9208 Auburn Ave",	zipCode: "40299", visited: false,},
            {id: 162,	parkName: "Jeffersontown Memorial Park",	address: "10707 Taylorsville Rd",	zipCode: "40299", visited: false,},
            {id: 163,	parkName: "David L Armstrong Recreation Center",	address: "3015 Bluebird Lane",	zipCode: "40299", visited: false,},
            {id: 164,	parkName: "Skyview Park",	address: "2700 Watterson Trail",	zipCode: "40299", visited: false,},
            {id: 165,	parkName: "Plainview Swim Center",	address: "10235 Timberwood Circle",	zipCode: "40223", visited: false,},
            {id: 166,	parkName: "Waterfront Park",	address: "1101 River Rd",	zipCode: "40206", visited: false,},
            {id: 167,	parkName: "Mount Washington  Community Park",	address: "176 Park View Ave",	zipCode: "40047", visited: false,},
            {id: 168,	parkName: "Lindsay Duvall Park",	address: "100 Newman Way",	zipCode: "40047", visited: false,},
            {id: 169,	parkName: "Frank Cornell Park",	address: "977 Waterford Rd",	zipCode: "40047", visited: false,},
            {id: 170,	parkName: "Maples Park",	address: "6826 W Hwy 22",	zipCode: "40014", visited: false,},
            {id: 171,	parkName: "Briar Hill Park",	address: "7400 E Orchard Gras Blvd",	zipCode: "40014", visited: false,},
            {id: 172,	parkName: "Wendell Moore Park",	address: "1551 Hwy 393",	zipCode: "40031", visited: false,},
            {id: 173,	parkName: "Schamback Park",	address: "6617 Main St",	zipCode: "40077", visited: false,},
            {id: 174,	parkName: "Peggy E. Baker Park",	address: "6887 Rte 2858",	zipCode: "40014", visited: false,},
            {id: 175,	parkName: "Morgan Conservation Park",	address: "1200 Kentucky 524",	zipCode: "40031", visited: false,},
            {id: 176,	parkName: "54 Acre Multi-Use Park",	address: "3930 Highway 146",	zipCode: "40031", visited: false,},
            {id: 177,	parkName: "Celebration Park",	address: "",	zipCode: "", visited: false,},
            {id: 178,	parkName: "Creasey Mahan Nature Preserve",	address: "12501 Harmony Landing Rd",	zipCode: "40026", visited: false,},
            {id: 179,	parkName: "PeeWee Valley Central Park",	address: "105 Central Avenue",	zipCode: "", visited: false,},
            {id: 180,	parkName: "Walsh Park",	address: "600 North 4th St",	zipCode: "40031", visited: false,},
            {id: 181,	parkName: "Wilborn Park",	address: "201 Lakeshore Dr",	zipCode: "40031", visited: false,},
            {id: 182,	parkName: "Shirley's Arbor",	address: "3501 Woehrle Rd",	zipCode: "47130", visited: false,},
            {id: 183,	parkName: "Chapel Lake Park",	address: "5801 New Chapel Rd",	zipCode: "47130", visited: false,},
            {id: 184,	parkName: "Perrin Family Park",	address: "414 Perrin Ln",	zipCode: "47130", visited: false,},
            {id: 185,	parkName: "Glossbrenner Public Garden",	address: "191 W Chestnut St",	zipCode: "47130", visited: false,},
            {id: 186,	parkName: "Harmony Park",	address: "1710 E 10th St",	zipCode: "47130", visited: false,},
            {id: 187,	parkName: "Big 4 Station Park",	address: "Big Four Pedestrian Bridge",	zipCode: "47130", visited: false,},
            {id: 188,	parkName: "Jeffersonville Skate Park",	address: "2107 Middle Rd",	zipCode: "47130", visited: false,},
            {id: 189,	parkName: "Shirley Hall Park",	address: "1203 Charlestown Pike",	zipCode: "47130", visited: false,},
            {id: 190,	parkName: "Woehrle Athletic Complex",	address: "4200 Charlestown Pike",	zipCode: "47130", visited: false,},
            {id: 191,	parkName: "Riverstage",	address: "100 W Riverside Dr",	zipCode: "47130", visited: false,},
            {id: 192,	parkName: "Nachand Fieldhouse",	address: "601 E Court Ave",	zipCode: "47130", visited: false,},
            {id: 193,	parkName: "Jeffersonville Aquatic Center",	address: "2107 Middle Rd",	zipCode: "47130", visited: false,},
            {id: 194,	parkName: "Veterans Memorial Park",	address: "301 Mulberry St",	zipCode: "47130", visited: false,},
            {id: 195,	parkName: "W.F. Throckmorton Park",	address: "44 Beechwood Rd",	zipCode: "47130", visited: false,},
            {id: 196,	parkName: "Samuel G. Shannon Memorial Park",	address: "501 Crestview Ct",	zipCode: "47130", visited: false,},
            {id: 197,	parkName: "Richard L. Vissing Park",	address: "2728 Vissing Park Rd",	zipCode: "47130", visited: false,},
            {id: 198,	parkName: "Highland Dog Park",	address: "1300 Spruce Dr",	zipCode: "47130", visited: false,},
            {id: 199,	parkName: "John Wilcoxson Park",	address: "44 Beechwood Rd",	zipCode: "47130", visited: false,},
            {id: 200,	parkName: "Ricard B. Wathen Park",	address: "29 Regina Ave",	zipCode: "47130", visited: false,},
            {id: 201,	parkName: "Luther F. Warder Park",	address: "109 E Court Ave",	zipCode: "47130", visited: false,},
            {id: 202,	parkName: "Steamboat Park",	address: "320 Division St",	zipCode: "47130", visited: false,},
            {id: 203,	parkName: "S. Harlan Vogt Park",	address: "133 E Park Pl",	zipCode: "47130", visited: false,},
            {id: 204,	parkName: "Preservation Park",	address: "120 W Market St",	zipCode: "47130", visited: false,},
            {id: 205,	parkName: "Port Fulton Park	201 W High St",	zipCode: "47130", visited: false,},
            {id: 206,	parkName: "Poppy Park",	address: "2100 Poppy Pl",	zipCode: "47130", visited: false,},
            {id: 207,	parkName: "Meadows Park",	address: "4503 Fallow Dr",	zipCode: "47130", visited: false,},
            {id: 208,	parkName: "Lottie Oglesby Park",	address: "610 Martha Ave",	zipCode: "47130", visited: false,},
            {id: 209,	parkName: "Kyle Vissing Park",	address: "22 Forest Dr",	zipCode: "47130", visited: false,},
            {id: 210,	parkName: "Pamela J Inman Park",	address: "2128 Robin Ln",	zipCode: "47130", visited: false,},
            {id: 211,	parkName: "Henry Landsen Park",	address: "201 E 15th St",	zipCode: "47130", visited: false,},
            {id: 212,	parkName: "Gaither Park",	address: "1499 E 8th St",	zipCode: "47130", visited: false,},
            {id: 213,	parkName: "Forest Park",	address: "140 Forest Dr",	zipCode: "47130", visited: false,},
            {id: 214,	parkName: "James T. Duffy's Landing",	address: "2610 Utica Pike",	zipCode: "47130", visited: false,},
            {id: 215,	parkName: "Connie Sellmer Park",	address: "1904 Oakridge Dr",	zipCode: "47130", visited: false,},
            {id: 216,	parkName: "Bob Hedge Park",	address: "926 French St",	zipCode: "47130", visited: false,},
            {id: 217,	parkName: "Allison Brook Park",	address: "1701 Allison Ln",	zipCode: "47130", visited: false,},
            {id: 218,	parkName: "Ashland Park",	address: "430 E Riverside Dr",	zipCode: "47129", visited: false,},
            {id: 219,	parkName: "Beechwood Park",	address: "1200 Beechwood Dr",	zipCode: "47129", visited: false,},
            {id: 220,	parkName: "Cedar Park",	address: "1630 Horn St",	zipCode: "47129", visited: false,},
            {id: 221,	parkName: "Colgate Park",	address: "800 S Clark Blvd",	zipCode: "47129", visited: false,},
            {id: 222,	parkName: "Gaskell Park",	address: "1629 Briarwood Dr",	zipCode: "47129", visited: false,},
            {id: 223,	parkName: "Gateway Park",	address: "500 Little League Blvd",	zipCode: "47129", visited: false,},
            {id: 224,	parkName: "Lapping Park",	address: "2404 Greentree N",	zipCode: "47129", visited: false,},
            {id: 225,	parkName: "Lewis and Clark Park",	address: "1240 Harrison Ave",	zipCode: "47129", visited: false,},
            {id: 226,	parkName: "Parkwood Park",	address: "1415 Kilmer Way",	zipCode: "47129", visited: false,},
            {id: 227,	parkName: "Ray Lawrence Park",	address: "1021 Irving Dr",	zipCode: "47129", visited: false,},
            {id: 228,	parkName: "Anderson Park",	address: "711 Hildreth St",	zipCode: "47150", visited: false,},
            {id: 229,	parkName: "Bicknell Park",	address: "315 Silver St",	zipCode: "47150", visited: false,},
            {id: 230,	parkName: "Billy Herman Park",	address: "600 Scribner Dr",	zipCode: "47150", visited: false,},
            {id: 231,	parkName: "Binford Park",	address: "1701 Graybrook Lane",	zipCode: "47150", visited: false,},
            {id: 232,	parkName: "Cannon Acres Soccer Field",	address: "1935 Budd Rd",	zipCode: "47150", visited: false,},
            {id: 233,	parkName: "Cherry Valley Golf Course",	address: "	",	zipCode: "47150", visited: false,},
            {id: 234,	parkName: "Divison Street",	address: "1728 Division St",	zipCode: "47150", visited: false,},
            {id: 235,	parkName: "Fairmont Park",	address: "1725 Abbie Dell",	zipCode: "47150", visited: false,},
            {id: 236,	parkName: "Griffin Recreation Center",	address: "1140 Griffin Street",	zipCode: "47150", visited: false,},
            {id: 237,	parkName: "Joe Kraft Park",	address: "500 W 7th St",	zipCode: "47150", visited: false,},
            {id: 238,	parkName: "Millerwood Park",	address: "1759 Millerwood Dr",	zipCode: "47150", visited: false,},
            {id: 239,	parkName: "New Albany Dog Park",	address: "1935 Budd Rd",	zipCode: "47150", visited: false,},
            {id: 240,	parkName: "Ritter Park",	address: "1218 Culbertson Ave",	zipCode: "47150", visited: false,},
            {id: 241,	parkName: "River Run Family Waterpark",	address: "224 W Daisy Ln",	zipCode: "47150", visited: false,},
            {id: 242,	parkName: "Sertoma Park",	address: "1315 Mill Ln",	zipCode: "47150", visited: false,},
            {id: 243,	parkName: "Silver Street Park",	address: "2043 Silver St",	zipCode: "47150", visited: false,},
            {id: 244,	parkName: "Valley View Golf Park",	address: "3748 Lawrence Banet Rd",	zipCode: "47119", visited: false,},
            {id: 245,	parkName: "Bicentennial Park",	address: "118 E Spring St",	zipCode: "47150", visited: false,},
            {id: 246,	parkName: "Riverfront Amphitheater",	address: "290 E Water St",	zipCode: "47150", visited: false,},
            {id: 247,	parkName: "Campbell Woodland Nature Trails",	address: "3500 Budd Rd",	zipCode: "47150", visited: false,},
            {id: 248,	parkName: "Galena-Lamb Park",	address: "6220 Highway 150",	zipCode: "47119", visited: false,},
            {id: 249,	parkName: "Garry E. Cavan Park",	address: "6485 Corydon Ridge Rd",	zipCode: "47122", visited: false,},
            {id: 250,	parkName: "Greenville Park",	address: "6455 Buttontown Rd",	zipCode: "47124", visited: false,},
            {id: 251,	parkName: "Herman Collier Park",	address: "3905 Fiske Ave",	zipCode: "47150", visited: false,},
            {id: 252,	parkName: "Letty Walter Park",	address: "5345 Saint Mary's Rd",	zipCode: "47119", visited: false,},
            {id: 253,	parkName: "Kevin Hammersmith Memorial Park",	address: "440 Lewis Endres Parkway",	zipCode: "47150", visited: false,},
            {id: 254,	parkName: "Sam Peden Community Park",	address: "3037 Grant Line Rd",	zipCode: "47150", visited: false,},
            {id: 255,	parkName: "Southern IN Sports Center",	address: "620 Park East Blvd",	zipCode: "47150", visited: false,},
            {id: 256,	parkName: "Falls of the Ohio State Park",	address: "201 W. Riverside Dr",	zipCode: "47129", visited: false,},
            {id: 257,	parkName: "Deam Lake State Recreation Area",	address: "1217 Deam Lake Rd off Hwy 60",	zipCode: "47106", visited: false,},
            {id: 258,	parkName: "Charlestown State Park",	address: "12500 Indiana 62",	zipCode: "47111", visited: false,},
            {id: 259,	parkName: "Clark State Forest",	address: "PO BOX 119",	zipCode: "47126", visited: false,},
            {id: 260,	parkName: "Harrison-Crawford State Forest",	address: "7240 Old Forest Road SW",	zipCode: "47112", visited: false,},
            {id: 261,	parkName: "O'Bannon Woods State Park",	address: "7234 Old Forest Road SW",	zipCode: "47112", visited: false,},
            {id: 262,	parkName: "Hayswood Nature Reserve",	address: "755 Hwy 135 NW",	zipCode: "47112", visited: false,},
            {id: 263,	parkName: "Rhoads Pool",	address: "2105 Poolside Dr NW",	zipCode: "47112", visited: false,},
            {id: 264,	parkName: "South Harrison",	address: "8750 South Harrison Park Dr SE",	zipCode: "47135", visited: false,},
            {id: 265,	parkName: "Buffalo Trace",	address: "1540 HWY 150 NE",	zipCode: "47164", visited: false,},
            {id: 266,	parkName: "Noe's",	address: "12825 HWY 111 SE",	zipCode: "47117", visited: false,},
            {id: 267,	parkName: "Gresham",	address: "7570 Main St NE",	zipCode: "47136", visited: false,},
            {id: 268,	parkName: "Battle of Corydon",	address: "100 Old Hwy 135 SW",	zipCode: "47112", visited: false,},
            {id: 269,	parkName: "The Hubbard House",	address: "1553 Old State Rd 64 NE",	zipCode: "47161", visited: false,},
            {id: 270,	parkName: "Morvin's Landing",	address: "12982 Morvin's Landing Road",	zipCode: "47142", visited: false,},
            {id: 271,	parkName: "The Overlook Park",	address: "2397 Overlook Dr SW",	zipCode: "47142", visited: false,},
            {id: 272,	parkName: "Lebanon Junction Memorial Park",	address: "423 S Poplar St",	zipCode: "40150", visited: false,},
            {id: 273,	parkName: "Clear Creek Park",	address: "717 Burks Branch",	zipCode: "40065", visited: false,},
            {id: 274,	parkName: "Red Orchard Park",	address: "704 Kentucky St",	zipCode: "40065", visited: false,},
            {id: 275,	parkName: "Shelby Trails Park",	address: "5063 Aiken Road",	zipCode: "40067", visited: false,},
            {id: 276,	parkName: "Finchville Park",	address: "5311 Taylorsville Rd",	zipCode: "40022", visited: false,},
            {id: 277,	parkName: "Shelbyville Skate Park",	address: "1145 Washington St",	zipCode: "40065", visited: false,},
            {id: 278,	parkName: "Shelbyville Greeenway Trail",	address: "97 7th St",	zipCode: "40065", visited: false,},
            {id: 279,	parkName: "Lake Shelby Park and Campground",	address: "1433 Burks Branch Rd",	zipCode: "40065", visited: false,},
            {id: 280,	parkName: "Battletown Park",	address: "75 Lawson Creek Rd",	zipCode: "40104", visited: false,},
            {id: 281,	parkName: "Brandenburg Riverfront Park",	address: "Main Street",	zipCode: "40108", visited: false,},
            {id: 282,	parkName: "Buttermilk Falls Trail",	address: "	",	zipCode: "40108", visited: false,},
            {id: 283,	parkName: "Concordia Park",	address: "",zipCode: " ", visited: false,},
            {id: 284,	parkName: "Dianna's Park",	address: "515 Broadway",	zipCode: "40108", visited: false,},
            {id: 285,	parkName: "Flaherty Community Park",	address: "", zipCode: " ", visited: false,},
            {id: 286,	parkName: "Meade-Olin Park",	address: "163 Moremen Rd",	zipCode: "40108", visited: false,},
            {id: 287,	parkName: "Otter Creek Recreation Area",	address: "", zipCode: "", visited: false,},		
            {id: 288,	parkName: "Wolf Creek Park",	address: "", zipCode: "", visited: false,},		
            {id: 289,	parkName: "YMCA Camp Piomingo",	address: "", zipCode: "", visited: false,}, 				
            {id: 290,	parkName: "Bernheim Arboretum and Research Forest",	address: "2075 Clermont Rd", zipCode: "40110", visited: false,},
			]
		}
	}
})